[2025-09-01 02:27:00,660] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: send_weather_to_kafka.stream_hdfs scheduled__2025-09-01T01:39:00.786183+00:00 [queued]>
[2025-09-01 02:27:00,670] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: send_weather_to_kafka.stream_hdfs scheduled__2025-09-01T01:39:00.786183+00:00 [queued]>
[2025-09-01 02:27:00,670] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2025-09-01 02:27:00,670] {taskinstance.py:1357} INFO - Starting attempt 2 of 2
[2025-09-01 02:27:00,670] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2025-09-01 02:27:00,680] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): stream_hdfs> on 2025-09-01 01:39:00.786183+00:00
[2025-09-01 02:27:00,683] {standard_task_runner.py:52} INFO - Started process 5197 to run task
[2025-09-01 02:27:00,686] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'send_weather_to_kafka', 'stream_hdfs', 'scheduled__2025-09-01T01:39:00.786183+00:00', '--job-id', '435', '--raw', '--subdir', 'DAGS_FOLDER/dag_meteo.py', '--cfg-path', '/tmp/tmpnxqxdpga', '--error-file', '/tmp/tmp7xob7bug']
[2025-09-01 02:27:00,687] {standard_task_runner.py:80} INFO - Job 435: Subtask stream_hdfs
[2025-09-01 02:27:00,705] {logging_mixin.py:115} WARNING - /home/***/.local/lib/python3.7/site-packages/***/configuration.py:470 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-09-01 02:27:00,759] {task_command.py:369} INFO - Running <TaskInstance: send_weather_to_kafka.stream_hdfs scheduled__2025-09-01T01:39:00.786183+00:00 [running]> on host e66737cfc193
[2025-09-01 02:27:00,917] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=send_weather_to_kafka
AIRFLOW_CTX_TASK_ID=stream_hdfs
AIRFLOW_CTX_EXECUTION_DATE=2025-09-01T01:39:00.786183+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2025-09-01T01:39:00.786183+00:00
[2025-09-01 02:27:00,918] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2025-09-01 02:27:00,919] {subprocess.py:74} INFO - Running command: ['bash', '-c', '\n/home/***/.local/bin/spark-submit   --master local[*]   --conf spark.hadoop.fs.defaultFS=hdfs://namenode:9000   --conf spark.hadoop.dfs.client.use.datanode.hostname=true   --conf spark.sql.adaptive.enabled=false   --packages org.apache.spark:spark-sql-kafka-0-10_2.12:3.3.1   /opt/***/scripts/pyspark/streaming.py']
[2025-09-01 02:27:00,932] {subprocess.py:85} INFO - Output:
[2025-09-01 02:27:00,943] {subprocess.py:92} INFO - /opt/spark-3.3.1-bin-hadoop3/bin/load-spark-env.sh: line 68: ps: command not found
[2025-09-01 02:27:02,112] {subprocess.py:92} INFO - :: loading settings :: url = jar:file:/opt/spark-3.3.1-bin-hadoop3/jars/ivy-2.5.0.jar!/org/apache/ivy/core/settings/ivysettings.xml
[2025-09-01 02:27:02,232] {subprocess.py:92} INFO - Ivy Default Cache set to: /home/***/.ivy2/cache
[2025-09-01 02:27:02,232] {subprocess.py:92} INFO - The jars for the packages stored in: /home/***/.ivy2/jars
[2025-09-01 02:27:02,238] {subprocess.py:92} INFO - org.apache.spark#spark-sql-kafka-0-10_2.12 added as a dependency
[2025-09-01 02:27:02,239] {subprocess.py:92} INFO - :: resolving dependencies :: org.apache.spark#spark-submit-parent-85b36966-e274-4ae3-9b54-6e794ca2bcc9;1.0
[2025-09-01 02:27:02,239] {subprocess.py:92} INFO - 	confs: [default]
[2025-09-01 02:27:02,344] {subprocess.py:92} INFO - 	found org.apache.spark#spark-sql-kafka-0-10_2.12;3.3.1 in central
[2025-09-01 02:27:02,411] {subprocess.py:92} INFO - 	found org.apache.spark#spark-token-provider-kafka-0-10_2.12;3.3.1 in central
[2025-09-01 02:27:02,442] {subprocess.py:92} INFO - 	found org.apache.kafka#kafka-clients;2.8.1 in central
[2025-09-01 02:27:02,472] {subprocess.py:92} INFO - 	found org.lz4#lz4-java;1.8.0 in central
[2025-09-01 02:27:02,496] {subprocess.py:92} INFO - 	found org.xerial.snappy#snappy-java;1.1.8.4 in central
[2025-09-01 02:27:02,513] {subprocess.py:92} INFO - 	found org.slf4j#slf4j-api;1.7.32 in central
[2025-09-01 02:27:02,539] {subprocess.py:92} INFO - 	found org.apache.hadoop#hadoop-client-runtime;3.3.2 in central
[2025-09-01 02:27:02,552] {subprocess.py:92} INFO - 	found org.spark-project.spark#unused;1.0.0 in central
[2025-09-01 02:27:02,577] {subprocess.py:92} INFO - 	found org.apache.hadoop#hadoop-client-api;3.3.2 in central
[2025-09-01 02:27:02,597] {subprocess.py:92} INFO - 	found commons-logging#commons-logging;1.1.3 in central
[2025-09-01 02:27:02,612] {subprocess.py:92} INFO - 	found com.google.code.findbugs#jsr305;3.0.0 in central
[2025-09-01 02:27:02,626] {subprocess.py:92} INFO - 	found org.apache.commons#commons-pool2;2.11.1 in central
[2025-09-01 02:27:02,654] {subprocess.py:92} INFO - :: resolution report :: resolve 401ms :: artifacts dl 14ms
[2025-09-01 02:27:02,654] {subprocess.py:92} INFO - 	:: modules in use:
[2025-09-01 02:27:02,655] {subprocess.py:92} INFO - 	com.google.code.findbugs#jsr305;3.0.0 from central in [default]
[2025-09-01 02:27:02,655] {subprocess.py:92} INFO - 	commons-logging#commons-logging;1.1.3 from central in [default]
[2025-09-01 02:27:02,655] {subprocess.py:92} INFO - 	org.apache.commons#commons-pool2;2.11.1 from central in [default]
[2025-09-01 02:27:02,655] {subprocess.py:92} INFO - 	org.apache.hadoop#hadoop-client-api;3.3.2 from central in [default]
[2025-09-01 02:27:02,655] {subprocess.py:92} INFO - 	org.apache.hadoop#hadoop-client-runtime;3.3.2 from central in [default]
[2025-09-01 02:27:02,655] {subprocess.py:92} INFO - 	org.apache.kafka#kafka-clients;2.8.1 from central in [default]
[2025-09-01 02:27:02,655] {subprocess.py:92} INFO - 	org.apache.spark#spark-sql-kafka-0-10_2.12;3.3.1 from central in [default]
[2025-09-01 02:27:02,655] {subprocess.py:92} INFO - 	org.apache.spark#spark-token-provider-kafka-0-10_2.12;3.3.1 from central in [default]
[2025-09-01 02:27:02,655] {subprocess.py:92} INFO - 	org.lz4#lz4-java;1.8.0 from central in [default]
[2025-09-01 02:27:02,655] {subprocess.py:92} INFO - 	org.slf4j#slf4j-api;1.7.32 from central in [default]
[2025-09-01 02:27:02,655] {subprocess.py:92} INFO - 	org.spark-project.spark#unused;1.0.0 from central in [default]
[2025-09-01 02:27:02,655] {subprocess.py:92} INFO - 	org.xerial.snappy#snappy-java;1.1.8.4 from central in [default]
[2025-09-01 02:27:02,655] {subprocess.py:92} INFO - 	---------------------------------------------------------------------
[2025-09-01 02:27:02,655] {subprocess.py:92} INFO - 	|                  |            modules            ||   artifacts   |
[2025-09-01 02:27:02,655] {subprocess.py:92} INFO - 	|       conf       | number| search|dwnlded|evicted|| number|dwnlded|
[2025-09-01 02:27:02,655] {subprocess.py:92} INFO - 	---------------------------------------------------------------------
[2025-09-01 02:27:02,655] {subprocess.py:92} INFO - 	|      default     |   12  |   0   |   0   |   0   ||   12  |   0   |
[2025-09-01 02:27:02,656] {subprocess.py:92} INFO - 	---------------------------------------------------------------------
[2025-09-01 02:27:02,663] {subprocess.py:92} INFO - :: retrieving :: org.apache.spark#spark-submit-parent-85b36966-e274-4ae3-9b54-6e794ca2bcc9
[2025-09-01 02:27:02,663] {subprocess.py:92} INFO - 	confs: [default]
[2025-09-01 02:27:02,672] {subprocess.py:92} INFO - 	0 artifacts copied, 12 already retrieved (0kB/10ms)
[2025-09-01 02:27:02,848] {subprocess.py:92} INFO - 25/09/01 02:27:02 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
[2025-09-01 02:27:03,630] {subprocess.py:92} INFO - 25/09/01 02:27:03 INFO SparkContext: Running Spark version 3.3.1
[2025-09-01 02:27:03,645] {subprocess.py:92} INFO - 25/09/01 02:27:03 INFO ResourceUtils: ==============================================================
[2025-09-01 02:27:03,646] {subprocess.py:92} INFO - 25/09/01 02:27:03 INFO ResourceUtils: No custom resources configured for spark.driver.
[2025-09-01 02:27:03,646] {subprocess.py:92} INFO - 25/09/01 02:27:03 INFO ResourceUtils: ==============================================================
[2025-09-01 02:27:03,646] {subprocess.py:92} INFO - 25/09/01 02:27:03 INFO SparkContext: Submitted application: KafkaToHDFSWeather
[2025-09-01 02:27:03,660] {subprocess.py:92} INFO - 25/09/01 02:27:03 INFO ResourceProfile: Default ResourceProfile created, executor resources: Map(cores -> name: cores, amount: 1, script: , vendor: , memory -> name: memory, amount: 1024, script: , vendor: , offHeap -> name: offHeap, amount: 0, script: , vendor: ), task resources: Map(cpus -> name: cpus, amount: 1.0)
[2025-09-01 02:27:03,668] {subprocess.py:92} INFO - 25/09/01 02:27:03 INFO ResourceProfile: Limiting resource is cpu
[2025-09-01 02:27:03,668] {subprocess.py:92} INFO - 25/09/01 02:27:03 INFO ResourceProfileManager: Added ResourceProfile id: 0
[2025-09-01 02:27:03,703] {subprocess.py:92} INFO - 25/09/01 02:27:03 INFO SecurityManager: Changing view acls to: ***
[2025-09-01 02:27:03,703] {subprocess.py:92} INFO - 25/09/01 02:27:03 INFO SecurityManager: Changing modify acls to: ***
[2025-09-01 02:27:03,703] {subprocess.py:92} INFO - 25/09/01 02:27:03 INFO SecurityManager: Changing view acls groups to:
[2025-09-01 02:27:03,704] {subprocess.py:92} INFO - 25/09/01 02:27:03 INFO SecurityManager: Changing modify acls groups to:
[2025-09-01 02:27:03,704] {subprocess.py:92} INFO - 25/09/01 02:27:03 INFO SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users  with view permissions: Set(***); groups with view permissions: Set(); users  with modify permissions: Set(***); groups with modify permissions: Set()
[2025-09-01 02:27:03,853] {subprocess.py:92} INFO - 25/09/01 02:27:03 INFO Utils: Successfully started service 'sparkDriver' on port 36413.
[2025-09-01 02:27:03,871] {subprocess.py:92} INFO - 25/09/01 02:27:03 INFO SparkEnv: Registering MapOutputTracker
[2025-09-01 02:27:03,891] {subprocess.py:92} INFO - 25/09/01 02:27:03 INFO SparkEnv: Registering BlockManagerMaster
[2025-09-01 02:27:03,901] {subprocess.py:92} INFO - 25/09/01 02:27:03 INFO BlockManagerMasterEndpoint: Using org.apache.spark.storage.DefaultTopologyMapper for getting topology information
[2025-09-01 02:27:03,901] {subprocess.py:92} INFO - 25/09/01 02:27:03 INFO BlockManagerMasterEndpoint: BlockManagerMasterEndpoint up
[2025-09-01 02:27:03,904] {subprocess.py:92} INFO - 25/09/01 02:27:03 INFO SparkEnv: Registering BlockManagerMasterHeartbeat
[2025-09-01 02:27:03,916] {subprocess.py:92} INFO - 25/09/01 02:27:03 INFO DiskBlockManager: Created local directory at /tmp/blockmgr-dfda9eb4-1b4a-47ce-a8ac-04427970a95f
[2025-09-01 02:27:03,925] {subprocess.py:92} INFO - 25/09/01 02:27:03 INFO MemoryStore: MemoryStore started with capacity 434.4 MiB
[2025-09-01 02:27:03,935] {subprocess.py:92} INFO - 25/09/01 02:27:03 INFO SparkEnv: Registering OutputCommitCoordinator
[2025-09-01 02:27:04,063] {subprocess.py:92} INFO - 25/09/01 02:27:04 INFO Utils: Successfully started service 'SparkUI' on port 4040.
[2025-09-01 02:27:04,087] {subprocess.py:92} INFO - 25/09/01 02:27:04 INFO SparkContext: Added JAR file:///home/***/.ivy2/jars/org.apache.spark_spark-sql-kafka-0-10_2.12-3.3.1.jar at spark://e66737cfc193:36413/jars/org.apache.spark_spark-sql-kafka-0-10_2.12-3.3.1.jar with timestamp 1756693623625
[2025-09-01 02:27:04,087] {subprocess.py:92} INFO - 25/09/01 02:27:04 INFO SparkContext: Added JAR file:///home/***/.ivy2/jars/org.apache.spark_spark-token-provider-kafka-0-10_2.12-3.3.1.jar at spark://e66737cfc193:36413/jars/org.apache.spark_spark-token-provider-kafka-0-10_2.12-3.3.1.jar with timestamp 1756693623625
[2025-09-01 02:27:04,087] {subprocess.py:92} INFO - 25/09/01 02:27:04 INFO SparkContext: Added JAR file:///home/***/.ivy2/jars/org.apache.kafka_kafka-clients-2.8.1.jar at spark://e66737cfc193:36413/jars/org.apache.kafka_kafka-clients-2.8.1.jar with timestamp 1756693623625
[2025-09-01 02:27:04,087] {subprocess.py:92} INFO - 25/09/01 02:27:04 INFO SparkContext: Added JAR file:///home/***/.ivy2/jars/com.google.code.findbugs_jsr305-3.0.0.jar at spark://e66737cfc193:36413/jars/com.google.code.findbugs_jsr305-3.0.0.jar with timestamp 1756693623625
[2025-09-01 02:27:04,087] {subprocess.py:92} INFO - 25/09/01 02:27:04 INFO SparkContext: Added JAR file:///home/***/.ivy2/jars/org.apache.commons_commons-pool2-2.11.1.jar at spark://e66737cfc193:36413/jars/org.apache.commons_commons-pool2-2.11.1.jar with timestamp 1756693623625
[2025-09-01 02:27:04,087] {subprocess.py:92} INFO - 25/09/01 02:27:04 INFO SparkContext: Added JAR file:///home/***/.ivy2/jars/org.spark-project.spark_unused-1.0.0.jar at spark://e66737cfc193:36413/jars/org.spark-project.spark_unused-1.0.0.jar with timestamp 1756693623625
[2025-09-01 02:27:04,087] {subprocess.py:92} INFO - 25/09/01 02:27:04 INFO SparkContext: Added JAR file:///home/***/.ivy2/jars/org.apache.hadoop_hadoop-client-runtime-3.3.2.jar at spark://e66737cfc193:36413/jars/org.apache.hadoop_hadoop-client-runtime-3.3.2.jar with timestamp 1756693623625
[2025-09-01 02:27:04,087] {subprocess.py:92} INFO - 25/09/01 02:27:04 INFO SparkContext: Added JAR file:///home/***/.ivy2/jars/org.lz4_lz4-java-1.8.0.jar at spark://e66737cfc193:36413/jars/org.lz4_lz4-java-1.8.0.jar with timestamp 1756693623625
[2025-09-01 02:27:04,088] {subprocess.py:92} INFO - 25/09/01 02:27:04 INFO SparkContext: Added JAR file:///home/***/.ivy2/jars/org.xerial.snappy_snappy-java-1.1.8.4.jar at spark://e66737cfc193:36413/jars/org.xerial.snappy_snappy-java-1.1.8.4.jar with timestamp 1756693623625
[2025-09-01 02:27:04,088] {subprocess.py:92} INFO - 25/09/01 02:27:04 INFO SparkContext: Added JAR file:///home/***/.ivy2/jars/org.slf4j_slf4j-api-1.7.32.jar at spark://e66737cfc193:36413/jars/org.slf4j_slf4j-api-1.7.32.jar with timestamp 1756693623625
[2025-09-01 02:27:04,088] {subprocess.py:92} INFO - 25/09/01 02:27:04 INFO SparkContext: Added JAR file:///home/***/.ivy2/jars/org.apache.hadoop_hadoop-client-api-3.3.2.jar at spark://e66737cfc193:36413/jars/org.apache.hadoop_hadoop-client-api-3.3.2.jar with timestamp 1756693623625
[2025-09-01 02:27:04,088] {subprocess.py:92} INFO - 25/09/01 02:27:04 INFO SparkContext: Added JAR file:///home/***/.ivy2/jars/commons-logging_commons-logging-1.1.3.jar at spark://e66737cfc193:36413/jars/commons-logging_commons-logging-1.1.3.jar with timestamp 1756693623625
[2025-09-01 02:27:04,089] {subprocess.py:92} INFO - 25/09/01 02:27:04 INFO SparkContext: Added file file:///home/***/.ivy2/jars/org.apache.spark_spark-sql-kafka-0-10_2.12-3.3.1.jar at file:///home/***/.ivy2/jars/org.apache.spark_spark-sql-kafka-0-10_2.12-3.3.1.jar with timestamp 1756693623625
[2025-09-01 02:27:04,090] {subprocess.py:92} INFO - 25/09/01 02:27:04 INFO Utils: Copying /home/***/.ivy2/jars/org.apache.spark_spark-sql-kafka-0-10_2.12-3.3.1.jar to /tmp/spark-874531f6-9c60-47f6-9333-0599a12c44e3/userFiles-90458e71-e805-451e-a28d-6221004bc7a8/org.apache.spark_spark-sql-kafka-0-10_2.12-3.3.1.jar
[2025-09-01 02:27:04,098] {subprocess.py:92} INFO - 25/09/01 02:27:04 INFO SparkContext: Added file file:///home/***/.ivy2/jars/org.apache.spark_spark-token-provider-kafka-0-10_2.12-3.3.1.jar at file:///home/***/.ivy2/jars/org.apache.spark_spark-token-provider-kafka-0-10_2.12-3.3.1.jar with timestamp 1756693623625
[2025-09-01 02:27:04,098] {subprocess.py:92} INFO - 25/09/01 02:27:04 INFO Utils: Copying /home/***/.ivy2/jars/org.apache.spark_spark-token-provider-kafka-0-10_2.12-3.3.1.jar to /tmp/spark-874531f6-9c60-47f6-9333-0599a12c44e3/userFiles-90458e71-e805-451e-a28d-6221004bc7a8/org.apache.spark_spark-token-provider-kafka-0-10_2.12-3.3.1.jar
[2025-09-01 02:27:04,103] {subprocess.py:92} INFO - 25/09/01 02:27:04 INFO SparkContext: Added file file:///home/***/.ivy2/jars/org.apache.kafka_kafka-clients-2.8.1.jar at file:///home/***/.ivy2/jars/org.apache.kafka_kafka-clients-2.8.1.jar with timestamp 1756693623625
[2025-09-01 02:27:04,103] {subprocess.py:92} INFO - 25/09/01 02:27:04 INFO Utils: Copying /home/***/.ivy2/jars/org.apache.kafka_kafka-clients-2.8.1.jar to /tmp/spark-874531f6-9c60-47f6-9333-0599a12c44e3/userFiles-90458e71-e805-451e-a28d-6221004bc7a8/org.apache.kafka_kafka-clients-2.8.1.jar
[2025-09-01 02:27:04,111] {subprocess.py:92} INFO - 25/09/01 02:27:04 INFO SparkContext: Added file file:///home/***/.ivy2/jars/com.google.code.findbugs_jsr305-3.0.0.jar at file:///home/***/.ivy2/jars/com.google.code.findbugs_jsr305-3.0.0.jar with timestamp 1756693623625
[2025-09-01 02:27:04,111] {subprocess.py:92} INFO - 25/09/01 02:27:04 INFO Utils: Copying /home/***/.ivy2/jars/com.google.code.findbugs_jsr305-3.0.0.jar to /tmp/spark-874531f6-9c60-47f6-9333-0599a12c44e3/userFiles-90458e71-e805-451e-a28d-6221004bc7a8/com.google.code.findbugs_jsr305-3.0.0.jar
[2025-09-01 02:27:04,115] {subprocess.py:92} INFO - 25/09/01 02:27:04 INFO SparkContext: Added file file:///home/***/.ivy2/jars/org.apache.commons_commons-pool2-2.11.1.jar at file:///home/***/.ivy2/jars/org.apache.commons_commons-pool2-2.11.1.jar with timestamp 1756693623625
[2025-09-01 02:27:04,115] {subprocess.py:92} INFO - 25/09/01 02:27:04 INFO Utils: Copying /home/***/.ivy2/jars/org.apache.commons_commons-pool2-2.11.1.jar to /tmp/spark-874531f6-9c60-47f6-9333-0599a12c44e3/userFiles-90458e71-e805-451e-a28d-6221004bc7a8/org.apache.commons_commons-pool2-2.11.1.jar
[2025-09-01 02:27:04,119] {subprocess.py:92} INFO - 25/09/01 02:27:04 INFO SparkContext: Added file file:///home/***/.ivy2/jars/org.spark-project.spark_unused-1.0.0.jar at file:///home/***/.ivy2/jars/org.spark-project.spark_unused-1.0.0.jar with timestamp 1756693623625
[2025-09-01 02:27:04,119] {subprocess.py:92} INFO - 25/09/01 02:27:04 INFO Utils: Copying /home/***/.ivy2/jars/org.spark-project.spark_unused-1.0.0.jar to /tmp/spark-874531f6-9c60-47f6-9333-0599a12c44e3/userFiles-90458e71-e805-451e-a28d-6221004bc7a8/org.spark-project.spark_unused-1.0.0.jar
[2025-09-01 02:27:04,124] {subprocess.py:92} INFO - 25/09/01 02:27:04 INFO SparkContext: Added file file:///home/***/.ivy2/jars/org.apache.hadoop_hadoop-client-runtime-3.3.2.jar at file:///home/***/.ivy2/jars/org.apache.hadoop_hadoop-client-runtime-3.3.2.jar with timestamp 1756693623625
[2025-09-01 02:27:04,124] {subprocess.py:92} INFO - 25/09/01 02:27:04 INFO Utils: Copying /home/***/.ivy2/jars/org.apache.hadoop_hadoop-client-runtime-3.3.2.jar to /tmp/spark-874531f6-9c60-47f6-9333-0599a12c44e3/userFiles-90458e71-e805-451e-a28d-6221004bc7a8/org.apache.hadoop_hadoop-client-runtime-3.3.2.jar
[2025-09-01 02:27:04,145] {subprocess.py:92} INFO - 25/09/01 02:27:04 INFO SparkContext: Added file file:///home/***/.ivy2/jars/org.lz4_lz4-java-1.8.0.jar at file:///home/***/.ivy2/jars/org.lz4_lz4-java-1.8.0.jar with timestamp 1756693623625
[2025-09-01 02:27:04,145] {subprocess.py:92} INFO - 25/09/01 02:27:04 INFO Utils: Copying /home/***/.ivy2/jars/org.lz4_lz4-java-1.8.0.jar to /tmp/spark-874531f6-9c60-47f6-9333-0599a12c44e3/userFiles-90458e71-e805-451e-a28d-6221004bc7a8/org.lz4_lz4-java-1.8.0.jar
[2025-09-01 02:27:04,149] {subprocess.py:92} INFO - 25/09/01 02:27:04 INFO SparkContext: Added file file:///home/***/.ivy2/jars/org.xerial.snappy_snappy-java-1.1.8.4.jar at file:///home/***/.ivy2/jars/org.xerial.snappy_snappy-java-1.1.8.4.jar with timestamp 1756693623625
[2025-09-01 02:27:04,149] {subprocess.py:92} INFO - 25/09/01 02:27:04 INFO Utils: Copying /home/***/.ivy2/jars/org.xerial.snappy_snappy-java-1.1.8.4.jar to /tmp/spark-874531f6-9c60-47f6-9333-0599a12c44e3/userFiles-90458e71-e805-451e-a28d-6221004bc7a8/org.xerial.snappy_snappy-java-1.1.8.4.jar
[2025-09-01 02:27:04,153] {subprocess.py:92} INFO - 25/09/01 02:27:04 INFO SparkContext: Added file file:///home/***/.ivy2/jars/org.slf4j_slf4j-api-1.7.32.jar at file:///home/***/.ivy2/jars/org.slf4j_slf4j-api-1.7.32.jar with timestamp 1756693623625
[2025-09-01 02:27:04,154] {subprocess.py:92} INFO - 25/09/01 02:27:04 INFO Utils: Copying /home/***/.ivy2/jars/org.slf4j_slf4j-api-1.7.32.jar to /tmp/spark-874531f6-9c60-47f6-9333-0599a12c44e3/userFiles-90458e71-e805-451e-a28d-6221004bc7a8/org.slf4j_slf4j-api-1.7.32.jar
[2025-09-01 02:27:04,157] {subprocess.py:92} INFO - 25/09/01 02:27:04 INFO SparkContext: Added file file:///home/***/.ivy2/jars/org.apache.hadoop_hadoop-client-api-3.3.2.jar at file:///home/***/.ivy2/jars/org.apache.hadoop_hadoop-client-api-3.3.2.jar with timestamp 1756693623625
[2025-09-01 02:27:04,158] {subprocess.py:92} INFO - 25/09/01 02:27:04 INFO Utils: Copying /home/***/.ivy2/jars/org.apache.hadoop_hadoop-client-api-3.3.2.jar to /tmp/spark-874531f6-9c60-47f6-9333-0599a12c44e3/userFiles-90458e71-e805-451e-a28d-6221004bc7a8/org.apache.hadoop_hadoop-client-api-3.3.2.jar
[2025-09-01 02:27:04,171] {subprocess.py:92} INFO - 25/09/01 02:27:04 INFO SparkContext: Added file file:///home/***/.ivy2/jars/commons-logging_commons-logging-1.1.3.jar at file:///home/***/.ivy2/jars/commons-logging_commons-logging-1.1.3.jar with timestamp 1756693623625
[2025-09-01 02:27:04,171] {subprocess.py:92} INFO - 25/09/01 02:27:04 INFO Utils: Copying /home/***/.ivy2/jars/commons-logging_commons-logging-1.1.3.jar to /tmp/spark-874531f6-9c60-47f6-9333-0599a12c44e3/userFiles-90458e71-e805-451e-a28d-6221004bc7a8/commons-logging_commons-logging-1.1.3.jar
[2025-09-01 02:27:04,217] {subprocess.py:92} INFO - 25/09/01 02:27:04 INFO Executor: Starting executor ID driver on host e66737cfc193
[2025-09-01 02:27:04,221] {subprocess.py:92} INFO - 25/09/01 02:27:04 INFO Executor: Starting executor with user classpath (userClassPathFirst = false): ''
[2025-09-01 02:27:04,228] {subprocess.py:92} INFO - 25/09/01 02:27:04 INFO Executor: Fetching file:///home/***/.ivy2/jars/commons-logging_commons-logging-1.1.3.jar with timestamp 1756693623625
[2025-09-01 02:27:04,245] {subprocess.py:92} INFO - 25/09/01 02:27:04 INFO Utils: /home/***/.ivy2/jars/commons-logging_commons-logging-1.1.3.jar has been previously copied to /tmp/spark-874531f6-9c60-47f6-9333-0599a12c44e3/userFiles-90458e71-e805-451e-a28d-6221004bc7a8/commons-logging_commons-logging-1.1.3.jar
[2025-09-01 02:27:04,248] {subprocess.py:92} INFO - 25/09/01 02:27:04 INFO Executor: Fetching file:///home/***/.ivy2/jars/org.spark-project.spark_unused-1.0.0.jar with timestamp 1756693623625
[2025-09-01 02:27:04,248] {subprocess.py:92} INFO - 25/09/01 02:27:04 INFO Utils: /home/***/.ivy2/jars/org.spark-project.spark_unused-1.0.0.jar has been previously copied to /tmp/spark-874531f6-9c60-47f6-9333-0599a12c44e3/userFiles-90458e71-e805-451e-a28d-6221004bc7a8/org.spark-project.spark_unused-1.0.0.jar
[2025-09-01 02:27:04,252] {subprocess.py:92} INFO - 25/09/01 02:27:04 INFO Executor: Fetching file:///home/***/.ivy2/jars/org.apache.spark_spark-sql-kafka-0-10_2.12-3.3.1.jar with timestamp 1756693623625
[2025-09-01 02:27:04,255] {subprocess.py:92} INFO - 25/09/01 02:27:04 INFO Utils: /home/***/.ivy2/jars/org.apache.spark_spark-sql-kafka-0-10_2.12-3.3.1.jar has been previously copied to /tmp/spark-874531f6-9c60-47f6-9333-0599a12c44e3/userFiles-90458e71-e805-451e-a28d-6221004bc7a8/org.apache.spark_spark-sql-kafka-0-10_2.12-3.3.1.jar
[2025-09-01 02:27:04,258] {subprocess.py:92} INFO - 25/09/01 02:27:04 INFO Executor: Fetching file:///home/***/.ivy2/jars/org.apache.hadoop_hadoop-client-api-3.3.2.jar with timestamp 1756693623625
[2025-09-01 02:27:04,268] {subprocess.py:92} INFO - 25/09/01 02:27:04 INFO Utils: /home/***/.ivy2/jars/org.apache.hadoop_hadoop-client-api-3.3.2.jar has been previously copied to /tmp/spark-874531f6-9c60-47f6-9333-0599a12c44e3/userFiles-90458e71-e805-451e-a28d-6221004bc7a8/org.apache.hadoop_hadoop-client-api-3.3.2.jar
[2025-09-01 02:27:04,272] {subprocess.py:92} INFO - 25/09/01 02:27:04 INFO Executor: Fetching file:///home/***/.ivy2/jars/org.apache.hadoop_hadoop-client-runtime-3.3.2.jar with timestamp 1756693623625
[2025-09-01 02:27:04,286] {subprocess.py:92} INFO - 25/09/01 02:27:04 INFO Utils: /home/***/.ivy2/jars/org.apache.hadoop_hadoop-client-runtime-3.3.2.jar has been previously copied to /tmp/spark-874531f6-9c60-47f6-9333-0599a12c44e3/userFiles-90458e71-e805-451e-a28d-6221004bc7a8/org.apache.hadoop_hadoop-client-runtime-3.3.2.jar
[2025-09-01 02:27:04,290] {subprocess.py:92} INFO - 25/09/01 02:27:04 INFO Executor: Fetching file:///home/***/.ivy2/jars/org.slf4j_slf4j-api-1.7.32.jar with timestamp 1756693623625
[2025-09-01 02:27:04,290] {subprocess.py:92} INFO - 25/09/01 02:27:04 INFO Utils: /home/***/.ivy2/jars/org.slf4j_slf4j-api-1.7.32.jar has been previously copied to /tmp/spark-874531f6-9c60-47f6-9333-0599a12c44e3/userFiles-90458e71-e805-451e-a28d-6221004bc7a8/org.slf4j_slf4j-api-1.7.32.jar
[2025-09-01 02:27:04,294] {subprocess.py:92} INFO - 25/09/01 02:27:04 INFO Executor: Fetching file:///home/***/.ivy2/jars/org.lz4_lz4-java-1.8.0.jar with timestamp 1756693623625
[2025-09-01 02:27:04,295] {subprocess.py:92} INFO - 25/09/01 02:27:04 INFO Utils: /home/***/.ivy2/jars/org.lz4_lz4-java-1.8.0.jar has been previously copied to /tmp/spark-874531f6-9c60-47f6-9333-0599a12c44e3/userFiles-90458e71-e805-451e-a28d-6221004bc7a8/org.lz4_lz4-java-1.8.0.jar
[2025-09-01 02:27:04,298] {subprocess.py:92} INFO - 25/09/01 02:27:04 INFO Executor: Fetching file:///home/***/.ivy2/jars/org.apache.commons_commons-pool2-2.11.1.jar with timestamp 1756693623625
[2025-09-01 02:27:04,299] {subprocess.py:92} INFO - 25/09/01 02:27:04 INFO Utils: /home/***/.ivy2/jars/org.apache.commons_commons-pool2-2.11.1.jar has been previously copied to /tmp/spark-874531f6-9c60-47f6-9333-0599a12c44e3/userFiles-90458e71-e805-451e-a28d-6221004bc7a8/org.apache.commons_commons-pool2-2.11.1.jar
[2025-09-01 02:27:04,303] {subprocess.py:92} INFO - 25/09/01 02:27:04 INFO Executor: Fetching file:///home/***/.ivy2/jars/com.google.code.findbugs_jsr305-3.0.0.jar with timestamp 1756693623625
[2025-09-01 02:27:04,303] {subprocess.py:92} INFO - 25/09/01 02:27:04 INFO Utils: /home/***/.ivy2/jars/com.google.code.findbugs_jsr305-3.0.0.jar has been previously copied to /tmp/spark-874531f6-9c60-47f6-9333-0599a12c44e3/userFiles-90458e71-e805-451e-a28d-6221004bc7a8/com.google.code.findbugs_jsr305-3.0.0.jar
[2025-09-01 02:27:04,307] {subprocess.py:92} INFO - 25/09/01 02:27:04 INFO Executor: Fetching file:///home/***/.ivy2/jars/org.apache.spark_spark-token-provider-kafka-0-10_2.12-3.3.1.jar with timestamp 1756693623625
[2025-09-01 02:27:04,308] {subprocess.py:92} INFO - 25/09/01 02:27:04 INFO Utils: /home/***/.ivy2/jars/org.apache.spark_spark-token-provider-kafka-0-10_2.12-3.3.1.jar has been previously copied to /tmp/spark-874531f6-9c60-47f6-9333-0599a12c44e3/userFiles-90458e71-e805-451e-a28d-6221004bc7a8/org.apache.spark_spark-token-provider-kafka-0-10_2.12-3.3.1.jar
[2025-09-01 02:27:04,312] {subprocess.py:92} INFO - 25/09/01 02:27:04 INFO Executor: Fetching file:///home/***/.ivy2/jars/org.apache.kafka_kafka-clients-2.8.1.jar with timestamp 1756693623625
[2025-09-01 02:27:04,319] {subprocess.py:92} INFO - 25/09/01 02:27:04 INFO Utils: /home/***/.ivy2/jars/org.apache.kafka_kafka-clients-2.8.1.jar has been previously copied to /tmp/spark-874531f6-9c60-47f6-9333-0599a12c44e3/userFiles-90458e71-e805-451e-a28d-6221004bc7a8/org.apache.kafka_kafka-clients-2.8.1.jar
[2025-09-01 02:27:04,324] {subprocess.py:92} INFO - 25/09/01 02:27:04 INFO Executor: Fetching file:///home/***/.ivy2/jars/org.xerial.snappy_snappy-java-1.1.8.4.jar with timestamp 1756693623625
[2025-09-01 02:27:04,326] {subprocess.py:92} INFO - 25/09/01 02:27:04 INFO Utils: /home/***/.ivy2/jars/org.xerial.snappy_snappy-java-1.1.8.4.jar has been previously copied to /tmp/spark-874531f6-9c60-47f6-9333-0599a12c44e3/userFiles-90458e71-e805-451e-a28d-6221004bc7a8/org.xerial.snappy_snappy-java-1.1.8.4.jar
[2025-09-01 02:27:04,335] {subprocess.py:92} INFO - 25/09/01 02:27:04 INFO Executor: Fetching spark://e66737cfc193:36413/jars/org.apache.hadoop_hadoop-client-api-3.3.2.jar with timestamp 1756693623625
[2025-09-01 02:27:04,371] {subprocess.py:92} INFO - 25/09/01 02:27:04 INFO TransportClientFactory: Successfully created connection to e66737cfc193/172.20.0.18:36413 after 21 ms (0 ms spent in bootstraps)
[2025-09-01 02:27:04,375] {subprocess.py:92} INFO - 25/09/01 02:27:04 INFO Utils: Fetching spark://e66737cfc193:36413/jars/org.apache.hadoop_hadoop-client-api-3.3.2.jar to /tmp/spark-874531f6-9c60-47f6-9333-0599a12c44e3/userFiles-90458e71-e805-451e-a28d-6221004bc7a8/fetchFileTemp5200306467195508921.tmp
[2025-09-01 02:27:04,469] {subprocess.py:92} INFO - 25/09/01 02:27:04 INFO Utils: /tmp/spark-874531f6-9c60-47f6-9333-0599a12c44e3/userFiles-90458e71-e805-451e-a28d-6221004bc7a8/fetchFileTemp5200306467195508921.tmp has been previously copied to /tmp/spark-874531f6-9c60-47f6-9333-0599a12c44e3/userFiles-90458e71-e805-451e-a28d-6221004bc7a8/org.apache.hadoop_hadoop-client-api-3.3.2.jar
[2025-09-01 02:27:04,474] {subprocess.py:92} INFO - 25/09/01 02:27:04 INFO Executor: Adding file:/tmp/spark-874531f6-9c60-47f6-9333-0599a12c44e3/userFiles-90458e71-e805-451e-a28d-6221004bc7a8/org.apache.hadoop_hadoop-client-api-3.3.2.jar to class loader
[2025-09-01 02:27:04,474] {subprocess.py:92} INFO - 25/09/01 02:27:04 INFO Executor: Fetching spark://e66737cfc193:36413/jars/org.apache.hadoop_hadoop-client-runtime-3.3.2.jar with timestamp 1756693623625
[2025-09-01 02:27:04,475] {subprocess.py:92} INFO - 25/09/01 02:27:04 INFO Utils: Fetching spark://e66737cfc193:36413/jars/org.apache.hadoop_hadoop-client-runtime-3.3.2.jar to /tmp/spark-874531f6-9c60-47f6-9333-0599a12c44e3/userFiles-90458e71-e805-451e-a28d-6221004bc7a8/fetchFileTemp5620984300654019659.tmp
[2025-09-01 02:27:04,558] {subprocess.py:92} INFO - 25/09/01 02:27:04 INFO Utils: /tmp/spark-874531f6-9c60-47f6-9333-0599a12c44e3/userFiles-90458e71-e805-451e-a28d-6221004bc7a8/fetchFileTemp5620984300654019659.tmp has been previously copied to /tmp/spark-874531f6-9c60-47f6-9333-0599a12c44e3/userFiles-90458e71-e805-451e-a28d-6221004bc7a8/org.apache.hadoop_hadoop-client-runtime-3.3.2.jar
[2025-09-01 02:27:04,564] {subprocess.py:92} INFO - 25/09/01 02:27:04 INFO Executor: Adding file:/tmp/spark-874531f6-9c60-47f6-9333-0599a12c44e3/userFiles-90458e71-e805-451e-a28d-6221004bc7a8/org.apache.hadoop_hadoop-client-runtime-3.3.2.jar to class loader
[2025-09-01 02:27:04,564] {subprocess.py:92} INFO - 25/09/01 02:27:04 INFO Executor: Fetching spark://e66737cfc193:36413/jars/org.apache.kafka_kafka-clients-2.8.1.jar with timestamp 1756693623625
[2025-09-01 02:27:04,564] {subprocess.py:92} INFO - 25/09/01 02:27:04 INFO Utils: Fetching spark://e66737cfc193:36413/jars/org.apache.kafka_kafka-clients-2.8.1.jar to /tmp/spark-874531f6-9c60-47f6-9333-0599a12c44e3/userFiles-90458e71-e805-451e-a28d-6221004bc7a8/fetchFileTemp7646078087555165420.tmp
[2025-09-01 02:27:04,578] {subprocess.py:92} INFO - 25/09/01 02:27:04 INFO Utils: /tmp/spark-874531f6-9c60-47f6-9333-0599a12c44e3/userFiles-90458e71-e805-451e-a28d-6221004bc7a8/fetchFileTemp7646078087555165420.tmp has been previously copied to /tmp/spark-874531f6-9c60-47f6-9333-0599a12c44e3/userFiles-90458e71-e805-451e-a28d-6221004bc7a8/org.apache.kafka_kafka-clients-2.8.1.jar
[2025-09-01 02:27:04,582] {subprocess.py:92} INFO - 25/09/01 02:27:04 INFO Executor: Adding file:/tmp/spark-874531f6-9c60-47f6-9333-0599a12c44e3/userFiles-90458e71-e805-451e-a28d-6221004bc7a8/org.apache.kafka_kafka-clients-2.8.1.jar to class loader
[2025-09-01 02:27:04,582] {subprocess.py:92} INFO - 25/09/01 02:27:04 INFO Executor: Fetching spark://e66737cfc193:36413/jars/org.slf4j_slf4j-api-1.7.32.jar with timestamp 1756693623625
[2025-09-01 02:27:04,583] {subprocess.py:92} INFO - 25/09/01 02:27:04 INFO Utils: Fetching spark://e66737cfc193:36413/jars/org.slf4j_slf4j-api-1.7.32.jar to /tmp/spark-874531f6-9c60-47f6-9333-0599a12c44e3/userFiles-90458e71-e805-451e-a28d-6221004bc7a8/fetchFileTemp953800674795678428.tmp
[2025-09-01 02:27:04,584] {subprocess.py:92} INFO - 25/09/01 02:27:04 INFO Utils: /tmp/spark-874531f6-9c60-47f6-9333-0599a12c44e3/userFiles-90458e71-e805-451e-a28d-6221004bc7a8/fetchFileTemp953800674795678428.tmp has been previously copied to /tmp/spark-874531f6-9c60-47f6-9333-0599a12c44e3/userFiles-90458e71-e805-451e-a28d-6221004bc7a8/org.slf4j_slf4j-api-1.7.32.jar
[2025-09-01 02:27:04,587] {subprocess.py:92} INFO - 25/09/01 02:27:04 INFO Executor: Adding file:/tmp/spark-874531f6-9c60-47f6-9333-0599a12c44e3/userFiles-90458e71-e805-451e-a28d-6221004bc7a8/org.slf4j_slf4j-api-1.7.32.jar to class loader
[2025-09-01 02:27:04,588] {subprocess.py:92} INFO - 25/09/01 02:27:04 INFO Executor: Fetching spark://e66737cfc193:36413/jars/org.xerial.snappy_snappy-java-1.1.8.4.jar with timestamp 1756693623625
[2025-09-01 02:27:04,588] {subprocess.py:92} INFO - 25/09/01 02:27:04 INFO Utils: Fetching spark://e66737cfc193:36413/jars/org.xerial.snappy_snappy-java-1.1.8.4.jar to /tmp/spark-874531f6-9c60-47f6-9333-0599a12c44e3/userFiles-90458e71-e805-451e-a28d-6221004bc7a8/fetchFileTemp18323688393189451739.tmp
[2025-09-01 02:27:04,594] {subprocess.py:92} INFO - 25/09/01 02:27:04 INFO Utils: /tmp/spark-874531f6-9c60-47f6-9333-0599a12c44e3/userFiles-90458e71-e805-451e-a28d-6221004bc7a8/fetchFileTemp18323688393189451739.tmp has been previously copied to /tmp/spark-874531f6-9c60-47f6-9333-0599a12c44e3/userFiles-90458e71-e805-451e-a28d-6221004bc7a8/org.xerial.snappy_snappy-java-1.1.8.4.jar
[2025-09-01 02:27:04,598] {subprocess.py:92} INFO - 25/09/01 02:27:04 INFO Executor: Adding file:/tmp/spark-874531f6-9c60-47f6-9333-0599a12c44e3/userFiles-90458e71-e805-451e-a28d-6221004bc7a8/org.xerial.snappy_snappy-java-1.1.8.4.jar to class loader
[2025-09-01 02:27:04,598] {subprocess.py:92} INFO - 25/09/01 02:27:04 INFO Executor: Fetching spark://e66737cfc193:36413/jars/org.apache.spark_spark-sql-kafka-0-10_2.12-3.3.1.jar with timestamp 1756693623625
[2025-09-01 02:27:04,599] {subprocess.py:92} INFO - 25/09/01 02:27:04 INFO Utils: Fetching spark://e66737cfc193:36413/jars/org.apache.spark_spark-sql-kafka-0-10_2.12-3.3.1.jar to /tmp/spark-874531f6-9c60-47f6-9333-0599a12c44e3/userFiles-90458e71-e805-451e-a28d-6221004bc7a8/fetchFileTemp4862773931290838399.tmp
[2025-09-01 02:27:04,601] {subprocess.py:92} INFO - 25/09/01 02:27:04 INFO Utils: /tmp/spark-874531f6-9c60-47f6-9333-0599a12c44e3/userFiles-90458e71-e805-451e-a28d-6221004bc7a8/fetchFileTemp4862773931290838399.tmp has been previously copied to /tmp/spark-874531f6-9c60-47f6-9333-0599a12c44e3/userFiles-90458e71-e805-451e-a28d-6221004bc7a8/org.apache.spark_spark-sql-kafka-0-10_2.12-3.3.1.jar
[2025-09-01 02:27:04,605] {subprocess.py:92} INFO - 25/09/01 02:27:04 INFO Executor: Adding file:/tmp/spark-874531f6-9c60-47f6-9333-0599a12c44e3/userFiles-90458e71-e805-451e-a28d-6221004bc7a8/org.apache.spark_spark-sql-kafka-0-10_2.12-3.3.1.jar to class loader
[2025-09-01 02:27:04,605] {subprocess.py:92} INFO - 25/09/01 02:27:04 INFO Executor: Fetching spark://e66737cfc193:36413/jars/commons-logging_commons-logging-1.1.3.jar with timestamp 1756693623625
[2025-09-01 02:27:04,606] {subprocess.py:92} INFO - 25/09/01 02:27:04 INFO Utils: Fetching spark://e66737cfc193:36413/jars/commons-logging_commons-logging-1.1.3.jar to /tmp/spark-874531f6-9c60-47f6-9333-0599a12c44e3/userFiles-90458e71-e805-451e-a28d-6221004bc7a8/fetchFileTemp14936492857462974567.tmp
[2025-09-01 02:27:04,607] {subprocess.py:92} INFO - 25/09/01 02:27:04 INFO Utils: /tmp/spark-874531f6-9c60-47f6-9333-0599a12c44e3/userFiles-90458e71-e805-451e-a28d-6221004bc7a8/fetchFileTemp14936492857462974567.tmp has been previously copied to /tmp/spark-874531f6-9c60-47f6-9333-0599a12c44e3/userFiles-90458e71-e805-451e-a28d-6221004bc7a8/commons-logging_commons-logging-1.1.3.jar
[2025-09-01 02:27:04,610] {subprocess.py:92} INFO - 25/09/01 02:27:04 INFO Executor: Adding file:/tmp/spark-874531f6-9c60-47f6-9333-0599a12c44e3/userFiles-90458e71-e805-451e-a28d-6221004bc7a8/commons-logging_commons-logging-1.1.3.jar to class loader
[2025-09-01 02:27:04,610] {subprocess.py:92} INFO - 25/09/01 02:27:04 INFO Executor: Fetching spark://e66737cfc193:36413/jars/org.apache.spark_spark-token-provider-kafka-0-10_2.12-3.3.1.jar with timestamp 1756693623625
[2025-09-01 02:27:04,611] {subprocess.py:92} INFO - 25/09/01 02:27:04 INFO Utils: Fetching spark://e66737cfc193:36413/jars/org.apache.spark_spark-token-provider-kafka-0-10_2.12-3.3.1.jar to /tmp/spark-874531f6-9c60-47f6-9333-0599a12c44e3/userFiles-90458e71-e805-451e-a28d-6221004bc7a8/fetchFileTemp4463528153010961615.tmp
[2025-09-01 02:27:04,612] {subprocess.py:92} INFO - 25/09/01 02:27:04 INFO Utils: /tmp/spark-874531f6-9c60-47f6-9333-0599a12c44e3/userFiles-90458e71-e805-451e-a28d-6221004bc7a8/fetchFileTemp4463528153010961615.tmp has been previously copied to /tmp/spark-874531f6-9c60-47f6-9333-0599a12c44e3/userFiles-90458e71-e805-451e-a28d-6221004bc7a8/org.apache.spark_spark-token-provider-kafka-0-10_2.12-3.3.1.jar
[2025-09-01 02:27:04,615] {subprocess.py:92} INFO - 25/09/01 02:27:04 INFO Executor: Adding file:/tmp/spark-874531f6-9c60-47f6-9333-0599a12c44e3/userFiles-90458e71-e805-451e-a28d-6221004bc7a8/org.apache.spark_spark-token-provider-kafka-0-10_2.12-3.3.1.jar to class loader
[2025-09-01 02:27:04,615] {subprocess.py:92} INFO - 25/09/01 02:27:04 INFO Executor: Fetching spark://e66737cfc193:36413/jars/org.apache.commons_commons-pool2-2.11.1.jar with timestamp 1756693623625
[2025-09-01 02:27:04,616] {subprocess.py:92} INFO - 25/09/01 02:27:04 INFO Utils: Fetching spark://e66737cfc193:36413/jars/org.apache.commons_commons-pool2-2.11.1.jar to /tmp/spark-874531f6-9c60-47f6-9333-0599a12c44e3/userFiles-90458e71-e805-451e-a28d-6221004bc7a8/fetchFileTemp16291203712223191890.tmp
[2025-09-01 02:27:04,617] {subprocess.py:92} INFO - 25/09/01 02:27:04 INFO Utils: /tmp/spark-874531f6-9c60-47f6-9333-0599a12c44e3/userFiles-90458e71-e805-451e-a28d-6221004bc7a8/fetchFileTemp16291203712223191890.tmp has been previously copied to /tmp/spark-874531f6-9c60-47f6-9333-0599a12c44e3/userFiles-90458e71-e805-451e-a28d-6221004bc7a8/org.apache.commons_commons-pool2-2.11.1.jar
[2025-09-01 02:27:04,621] {subprocess.py:92} INFO - 25/09/01 02:27:04 INFO Executor: Adding file:/tmp/spark-874531f6-9c60-47f6-9333-0599a12c44e3/userFiles-90458e71-e805-451e-a28d-6221004bc7a8/org.apache.commons_commons-pool2-2.11.1.jar to class loader
[2025-09-01 02:27:04,621] {subprocess.py:92} INFO - 25/09/01 02:27:04 INFO Executor: Fetching spark://e66737cfc193:36413/jars/org.spark-project.spark_unused-1.0.0.jar with timestamp 1756693623625
[2025-09-01 02:27:04,621] {subprocess.py:92} INFO - 25/09/01 02:27:04 INFO Utils: Fetching spark://e66737cfc193:36413/jars/org.spark-project.spark_unused-1.0.0.jar to /tmp/spark-874531f6-9c60-47f6-9333-0599a12c44e3/userFiles-90458e71-e805-451e-a28d-6221004bc7a8/fetchFileTemp8743523981879630514.tmp
[2025-09-01 02:27:04,622] {subprocess.py:92} INFO - 25/09/01 02:27:04 INFO Utils: /tmp/spark-874531f6-9c60-47f6-9333-0599a12c44e3/userFiles-90458e71-e805-451e-a28d-6221004bc7a8/fetchFileTemp8743523981879630514.tmp has been previously copied to /tmp/spark-874531f6-9c60-47f6-9333-0599a12c44e3/userFiles-90458e71-e805-451e-a28d-6221004bc7a8/org.spark-project.spark_unused-1.0.0.jar
[2025-09-01 02:27:04,626] {subprocess.py:92} INFO - 25/09/01 02:27:04 INFO Executor: Adding file:/tmp/spark-874531f6-9c60-47f6-9333-0599a12c44e3/userFiles-90458e71-e805-451e-a28d-6221004bc7a8/org.spark-project.spark_unused-1.0.0.jar to class loader
[2025-09-01 02:27:04,626] {subprocess.py:92} INFO - 25/09/01 02:27:04 INFO Executor: Fetching spark://e66737cfc193:36413/jars/org.lz4_lz4-java-1.8.0.jar with timestamp 1756693623625
[2025-09-01 02:27:04,626] {subprocess.py:92} INFO - 25/09/01 02:27:04 INFO Utils: Fetching spark://e66737cfc193:36413/jars/org.lz4_lz4-java-1.8.0.jar to /tmp/spark-874531f6-9c60-47f6-9333-0599a12c44e3/userFiles-90458e71-e805-451e-a28d-6221004bc7a8/fetchFileTemp13166661605737244774.tmp
[2025-09-01 02:27:04,630] {subprocess.py:92} INFO - 25/09/01 02:27:04 INFO Utils: /tmp/spark-874531f6-9c60-47f6-9333-0599a12c44e3/userFiles-90458e71-e805-451e-a28d-6221004bc7a8/fetchFileTemp13166661605737244774.tmp has been previously copied to /tmp/spark-874531f6-9c60-47f6-9333-0599a12c44e3/userFiles-90458e71-e805-451e-a28d-6221004bc7a8/org.lz4_lz4-java-1.8.0.jar
[2025-09-01 02:27:04,634] {subprocess.py:92} INFO - 25/09/01 02:27:04 INFO Executor: Adding file:/tmp/spark-874531f6-9c60-47f6-9333-0599a12c44e3/userFiles-90458e71-e805-451e-a28d-6221004bc7a8/org.lz4_lz4-java-1.8.0.jar to class loader
[2025-09-01 02:27:04,634] {subprocess.py:92} INFO - 25/09/01 02:27:04 INFO Executor: Fetching spark://e66737cfc193:36413/jars/com.google.code.findbugs_jsr305-3.0.0.jar with timestamp 1756693623625
[2025-09-01 02:27:04,635] {subprocess.py:92} INFO - 25/09/01 02:27:04 INFO Utils: Fetching spark://e66737cfc193:36413/jars/com.google.code.findbugs_jsr305-3.0.0.jar to /tmp/spark-874531f6-9c60-47f6-9333-0599a12c44e3/userFiles-90458e71-e805-451e-a28d-6221004bc7a8/fetchFileTemp4901689694525203380.tmp
[2025-09-01 02:27:04,636] {subprocess.py:92} INFO - 25/09/01 02:27:04 INFO Utils: /tmp/spark-874531f6-9c60-47f6-9333-0599a12c44e3/userFiles-90458e71-e805-451e-a28d-6221004bc7a8/fetchFileTemp4901689694525203380.tmp has been previously copied to /tmp/spark-874531f6-9c60-47f6-9333-0599a12c44e3/userFiles-90458e71-e805-451e-a28d-6221004bc7a8/com.google.code.findbugs_jsr305-3.0.0.jar
[2025-09-01 02:27:04,640] {subprocess.py:92} INFO - 25/09/01 02:27:04 INFO Executor: Adding file:/tmp/spark-874531f6-9c60-47f6-9333-0599a12c44e3/userFiles-90458e71-e805-451e-a28d-6221004bc7a8/com.google.code.findbugs_jsr305-3.0.0.jar to class loader
[2025-09-01 02:27:04,647] {subprocess.py:92} INFO - 25/09/01 02:27:04 INFO Utils: Successfully started service 'org.apache.spark.network.netty.NettyBlockTransferService' on port 35041.
[2025-09-01 02:27:04,647] {subprocess.py:92} INFO - 25/09/01 02:27:04 INFO NettyBlockTransferService: Server created on e66737cfc193:35041
[2025-09-01 02:27:04,650] {subprocess.py:92} INFO - 25/09/01 02:27:04 INFO BlockManager: Using org.apache.spark.storage.RandomBlockReplicationPolicy for block replication policy
[2025-09-01 02:27:04,659] {subprocess.py:92} INFO - 25/09/01 02:27:04 INFO BlockManagerMaster: Registering BlockManager BlockManagerId(driver, e66737cfc193, 35041, None)
[2025-09-01 02:27:04,662] {subprocess.py:92} INFO - 25/09/01 02:27:04 INFO BlockManagerMasterEndpoint: Registering block manager e66737cfc193:35041 with 434.4 MiB RAM, BlockManagerId(driver, e66737cfc193, 35041, None)
[2025-09-01 02:27:04,664] {subprocess.py:92} INFO - 25/09/01 02:27:04 INFO BlockManagerMaster: Registered BlockManager BlockManagerId(driver, e66737cfc193, 35041, None)
[2025-09-01 02:27:04,665] {subprocess.py:92} INFO - 25/09/01 02:27:04 INFO BlockManager: Initialized BlockManager: BlockManagerId(driver, e66737cfc193, 35041, None)
[2025-09-01 02:27:04,944] {subprocess.py:92} INFO - Connexion à Kafka...
[2025-09-01 02:27:06,351] {subprocess.py:92} INFO - Connexion Kafka réussie (kafka:9092)
[2025-09-01 02:27:06,351] {subprocess.py:92} INFO - Transformation des données JSON...
[2025-09-01 02:27:06,559] {subprocess.py:92} INFO - Démarrage du streaming vers HDFS...
[2025-09-01 02:27:07,154] {subprocess.py:92} INFO - Streaming actif - Données météo sauvegardées dans HDFS:/data/weather
[2025-09-01 04:43:43,169] {base_job.py:229} ERROR - LocalTaskJob heartbeat got an exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 3141, in _wrap_pool_connect
    return fn()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 301, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 755, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 419, in checkout
    rec = pool._do_get()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/impl.py", line 259, in _do_get
    return self._create_connection()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 247, in _create_connection
    return _ConnectionRecord(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 362, in __init__
    self.__connect(first_connect_check=True)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 605, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 72, in __exit__
    with_traceback=exc_tb,
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 599, in __connect
    connection = pool._invoke_creator(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/create.py", line 578, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 583, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.7/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: could not translate host name "postgres" to address: Temporary failure in name resolution


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/jobs/base_job.py", line 225, in heartbeat
    self.heartbeat_callback(session=session)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 68, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/jobs/local_task_job.py", line 186, in heartbeat_callback
    self.task_instance.refresh_from_db()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 71, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 873, in refresh_from_db
    ti = qry.first()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 2734, in first
    return self.limit(1)._iter().first()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 2821, in _iter
    execution_options={"_sa_orm_load_options": self.load_options},
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 1669, in execute
    conn = self._connection_for_bind(bind, close_with_result=True)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 1520, in _connection_for_bind
    engine, execution_options
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 747, in _connection_for_bind
    conn = bind.connect()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 3095, in connect
    return self._connection_cls(self, close_with_result=close_with_result)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 91, in __init__
    else engine.raw_connection()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 3174, in raw_connection
    return self._wrap_pool_connect(self.pool.connect, _connection)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 3145, in _wrap_pool_connect
    e, dialect, self
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 2004, in _handle_dbapi_exception_noconnection
    sqlalchemy_exception, with_traceback=exc_info[2], from_=e
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 3141, in _wrap_pool_connect
    return fn()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 301, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 755, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 419, in checkout
    rec = pool._do_get()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/impl.py", line 259, in _do_get
    return self._create_connection()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 247, in _create_connection
    return _ConnectionRecord(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 362, in __init__
    self.__connect(first_connect_check=True)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 605, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 72, in __exit__
    with_traceback=exc_tb,
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 599, in __connect
    connection = pool._invoke_creator(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/create.py", line 578, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 583, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.7/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) could not translate host name "postgres" to address: Temporary failure in name resolution

(Background on this error at: http://sqlalche.me/e/14/e3q8)
[2025-09-01 04:44:18,001] {base_job.py:229} ERROR - LocalTaskJob heartbeat got an exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 3141, in _wrap_pool_connect
    return fn()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 301, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 755, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 419, in checkout
    rec = pool._do_get()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/impl.py", line 259, in _do_get
    return self._create_connection()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 247, in _create_connection
    return _ConnectionRecord(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 362, in __init__
    self.__connect(first_connect_check=True)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 605, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 72, in __exit__
    with_traceback=exc_tb,
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 599, in __connect
    connection = pool._invoke_creator(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/create.py", line 578, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 583, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.7/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: could not translate host name "postgres" to address: Temporary failure in name resolution


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/jobs/base_job.py", line 201, in heartbeat
    session.merge(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 2877, in merge
    _resolve_conflict_map=_resolve_conflict_map,
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 2950, in _merge
    merged = self.get(mapper.class_, key[1], identity_token=key[2])
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 2702, in get
    identity_token=identity_token,
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 2800, in _get_impl
    load_options=load_options,
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/loading.py", line 535, in load_on_pk_identity
    bind_arguments=bind_arguments,
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 1669, in execute
    conn = self._connection_for_bind(bind, close_with_result=True)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 1520, in _connection_for_bind
    engine, execution_options
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 747, in _connection_for_bind
    conn = bind.connect()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 3095, in connect
    return self._connection_cls(self, close_with_result=close_with_result)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 91, in __init__
    else engine.raw_connection()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 3174, in raw_connection
    return self._wrap_pool_connect(self.pool.connect, _connection)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 3145, in _wrap_pool_connect
    e, dialect, self
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 2004, in _handle_dbapi_exception_noconnection
    sqlalchemy_exception, with_traceback=exc_info[2], from_=e
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 3141, in _wrap_pool_connect
    return fn()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 301, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 755, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 419, in checkout
    rec = pool._do_get()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/impl.py", line 259, in _do_get
    return self._create_connection()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 247, in _create_connection
    return _ConnectionRecord(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 362, in __init__
    self.__connect(first_connect_check=True)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 605, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 72, in __exit__
    with_traceback=exc_tb,
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 599, in __connect
    connection = pool._invoke_creator(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/create.py", line 578, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 583, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.7/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) could not translate host name "postgres" to address: Temporary failure in name resolution

(Background on this error at: http://sqlalche.me/e/14/e3q8)
[2025-09-01 04:46:07,074] {base_job.py:229} ERROR - LocalTaskJob heartbeat got an exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 3141, in _wrap_pool_connect
    return fn()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 301, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 755, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 419, in checkout
    rec = pool._do_get()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/impl.py", line 259, in _do_get
    return self._create_connection()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 247, in _create_connection
    return _ConnectionRecord(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 362, in __init__
    self.__connect(first_connect_check=True)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 605, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 72, in __exit__
    with_traceback=exc_tb,
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 599, in __connect
    connection = pool._invoke_creator(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/create.py", line 578, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 583, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.7/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: could not translate host name "postgres" to address: Temporary failure in name resolution


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/jobs/base_job.py", line 225, in heartbeat
    self.heartbeat_callback(session=session)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 68, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/jobs/local_task_job.py", line 186, in heartbeat_callback
    self.task_instance.refresh_from_db()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 71, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 873, in refresh_from_db
    ti = qry.first()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 2734, in first
    return self.limit(1)._iter().first()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 2821, in _iter
    execution_options={"_sa_orm_load_options": self.load_options},
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 1669, in execute
    conn = self._connection_for_bind(bind, close_with_result=True)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 1520, in _connection_for_bind
    engine, execution_options
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 747, in _connection_for_bind
    conn = bind.connect()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 3095, in connect
    return self._connection_cls(self, close_with_result=close_with_result)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 91, in __init__
    else engine.raw_connection()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 3174, in raw_connection
    return self._wrap_pool_connect(self.pool.connect, _connection)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 3145, in _wrap_pool_connect
    e, dialect, self
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 2004, in _handle_dbapi_exception_noconnection
    sqlalchemy_exception, with_traceback=exc_info[2], from_=e
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 3141, in _wrap_pool_connect
    return fn()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 301, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 755, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 419, in checkout
    rec = pool._do_get()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/impl.py", line 259, in _do_get
    return self._create_connection()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 247, in _create_connection
    return _ConnectionRecord(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 362, in __init__
    self.__connect(first_connect_check=True)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 605, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 72, in __exit__
    with_traceback=exc_tb,
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 599, in __connect
    connection = pool._invoke_creator(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/create.py", line 578, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 583, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.7/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) could not translate host name "postgres" to address: Temporary failure in name resolution

(Background on this error at: http://sqlalche.me/e/14/e3q8)
[2025-09-01 04:48:34,362] {base_job.py:229} ERROR - LocalTaskJob heartbeat got an exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 3141, in _wrap_pool_connect
    return fn()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 301, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 755, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 419, in checkout
    rec = pool._do_get()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/impl.py", line 259, in _do_get
    return self._create_connection()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 247, in _create_connection
    return _ConnectionRecord(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 362, in __init__
    self.__connect(first_connect_check=True)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 605, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 72, in __exit__
    with_traceback=exc_tb,
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 599, in __connect
    connection = pool._invoke_creator(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/create.py", line 578, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 583, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.7/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: could not translate host name "postgres" to address: Temporary failure in name resolution


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/jobs/base_job.py", line 219, in heartbeat
    session.merge(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 2877, in merge
    _resolve_conflict_map=_resolve_conflict_map,
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 2950, in _merge
    merged = self.get(mapper.class_, key[1], identity_token=key[2])
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 2702, in get
    identity_token=identity_token,
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 2800, in _get_impl
    load_options=load_options,
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/loading.py", line 535, in load_on_pk_identity
    bind_arguments=bind_arguments,
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 1669, in execute
    conn = self._connection_for_bind(bind, close_with_result=True)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 1520, in _connection_for_bind
    engine, execution_options
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 747, in _connection_for_bind
    conn = bind.connect()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 3095, in connect
    return self._connection_cls(self, close_with_result=close_with_result)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 91, in __init__
    else engine.raw_connection()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 3174, in raw_connection
    return self._wrap_pool_connect(self.pool.connect, _connection)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 3145, in _wrap_pool_connect
    e, dialect, self
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 2004, in _handle_dbapi_exception_noconnection
    sqlalchemy_exception, with_traceback=exc_info[2], from_=e
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 3141, in _wrap_pool_connect
    return fn()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 301, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 755, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 419, in checkout
    rec = pool._do_get()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/impl.py", line 259, in _do_get
    return self._create_connection()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 247, in _create_connection
    return _ConnectionRecord(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 362, in __init__
    self.__connect(first_connect_check=True)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 605, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 72, in __exit__
    with_traceback=exc_tb,
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 599, in __connect
    connection = pool._invoke_creator(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/create.py", line 578, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 583, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.7/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) could not translate host name "postgres" to address: Temporary failure in name resolution

(Background on this error at: http://sqlalche.me/e/14/e3q8)
[2025-09-01 04:50:45,610] {subprocess.py:92} INFO - 25/09/01 04:50:45 WARN NettyRpcEnv: Ignored failure: java.util.concurrent.TimeoutException: Cannot receive any reply from e66737cfc193:36413 in 10000 milliseconds
[2025-09-01 04:50:45,981] {local_task_job.py:221} WARNING - State of this instance has been externally set to None. Terminating instance.
[2025-09-01 04:50:45,988] {process_utils.py:129} INFO - Sending Signals.SIGTERM to group 5197. PIDs of all processes in the group: [5198, 5249, 5197]
[2025-09-01 04:50:45,988] {process_utils.py:80} INFO - Sending the signal Signals.SIGTERM to group 5197
[2025-09-01 04:50:45,988] {taskinstance.py:1541} ERROR - Received SIGTERM. Terminating subprocesses.
[2025-09-01 04:50:45,989] {subprocess.py:103} INFO - Sending SIGTERM signal to process group
[2025-09-01 04:50:46,063] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 189, in execute
    cwd=self.cwd,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/hooks/subprocess.py", line 90, in run_command
    for raw_line in iter(self.sub_process.stdout.readline, b''):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1543, in signal_handler
    raise AirflowException("Task received SIGTERM signal")
airflow.exceptions.AirflowException: Task received SIGTERM signal
[2025-09-01 04:50:46,097] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=send_weather_to_kafka, task_id=stream_hdfs, execution_date=20250901T013900, start_date=20250901T022700, end_date=20250901T045046
[2025-09-01 04:50:46,158] {standard_task_runner.py:97} ERROR - Failed to execute job 435 for task stream_hdfs (Task received SIGTERM signal; 5197)
[2025-09-01 04:50:46,349] {process_utils.py:75} INFO - Process psutil.Process(pid=5249, status='terminated', started='02:27:02') (5249) terminated with exit code None
[2025-09-01 04:50:46,350] {process_utils.py:75} INFO - Process psutil.Process(pid=5197, status='terminated', exitcode=1, started='02:26:59') (5197) terminated with exit code 1
[2025-09-01 04:50:46,939] {process_utils.py:75} INFO - Process psutil.Process(pid=5198, status='terminated', started='02:26:59') (5198) terminated with exit code None
