[2025-09-01 03:42:35,677] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: send_weather_to_kafka.stream_hdfs scheduled__2025-09-01T03:09:00.786183+00:00 [queued]>
[2025-09-01 03:42:35,693] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: send_weather_to_kafka.stream_hdfs scheduled__2025-09-01T03:09:00.786183+00:00 [queued]>
[2025-09-01 03:42:35,693] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2025-09-01 03:42:35,693] {taskinstance.py:1357} INFO - Starting attempt 1 of 2
[2025-09-01 03:42:35,693] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2025-09-01 03:42:35,711] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): stream_hdfs> on 2025-09-01 03:09:00.786183+00:00
[2025-09-01 03:42:35,715] {standard_task_runner.py:52} INFO - Started process 6630 to run task
[2025-09-01 03:42:35,718] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'send_weather_to_kafka', 'stream_hdfs', 'scheduled__2025-09-01T03:09:00.786183+00:00', '--job-id', '447', '--raw', '--subdir', 'DAGS_FOLDER/dag_meteo.py', '--cfg-path', '/tmp/tmpcndt4n8x', '--error-file', '/tmp/tmpugnbceqw']
[2025-09-01 03:42:35,719] {standard_task_runner.py:80} INFO - Job 447: Subtask stream_hdfs
[2025-09-01 03:42:35,741] {logging_mixin.py:115} WARNING - /home/***/.local/lib/python3.7/site-packages/***/configuration.py:470 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-09-01 03:42:35,788] {task_command.py:369} INFO - Running <TaskInstance: send_weather_to_kafka.stream_hdfs scheduled__2025-09-01T03:09:00.786183+00:00 [running]> on host e66737cfc193
[2025-09-01 03:42:35,876] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=send_weather_to_kafka
AIRFLOW_CTX_TASK_ID=stream_hdfs
AIRFLOW_CTX_EXECUTION_DATE=2025-09-01T03:09:00.786183+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2025-09-01T03:09:00.786183+00:00
[2025-09-01 03:42:35,877] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2025-09-01 03:42:35,877] {subprocess.py:74} INFO - Running command: ['bash', '-c', '\n/home/***/.local/bin/spark-submit   --master local[*]   --conf spark.hadoop.fs.defaultFS=hdfs://namenode:9000   --conf spark.hadoop.dfs.client.use.datanode.hostname=true   --conf spark.sql.adaptive.enabled=false   --packages org.apache.spark:spark-sql-kafka-0-10_2.12:3.3.1   /opt/***/scripts/pyspark/streaming.py']
[2025-09-01 03:42:35,889] {subprocess.py:85} INFO - Output:
[2025-09-01 03:42:35,904] {subprocess.py:92} INFO - /opt/spark-3.3.1-bin-hadoop3/bin/load-spark-env.sh: line 68: ps: command not found
[2025-09-01 03:42:36,852] {subprocess.py:92} INFO - :: loading settings :: url = jar:file:/opt/spark-3.3.1-bin-hadoop3/jars/ivy-2.5.0.jar!/org/apache/ivy/core/settings/ivysettings.xml
[2025-09-01 03:42:36,926] {subprocess.py:92} INFO - Ivy Default Cache set to: /home/***/.ivy2/cache
[2025-09-01 03:42:36,926] {subprocess.py:92} INFO - The jars for the packages stored in: /home/***/.ivy2/jars
[2025-09-01 03:42:36,930] {subprocess.py:92} INFO - org.apache.spark#spark-sql-kafka-0-10_2.12 added as a dependency
[2025-09-01 03:42:36,931] {subprocess.py:92} INFO - :: resolving dependencies :: org.apache.spark#spark-submit-parent-e1a848d7-8d3b-4939-a05c-0785cf1e1229;1.0
[2025-09-01 03:42:36,931] {subprocess.py:92} INFO - 	confs: [default]
[2025-09-01 03:42:37,036] {subprocess.py:92} INFO - 	found org.apache.spark#spark-sql-kafka-0-10_2.12;3.3.1 in central
[2025-09-01 03:42:37,079] {subprocess.py:92} INFO - 	found org.apache.spark#spark-token-provider-kafka-0-10_2.12;3.3.1 in central
[2025-09-01 03:42:37,116] {subprocess.py:92} INFO - 	found org.apache.kafka#kafka-clients;2.8.1 in central
[2025-09-01 03:42:37,151] {subprocess.py:92} INFO - 	found org.lz4#lz4-java;1.8.0 in central
[2025-09-01 03:42:37,162] {subprocess.py:92} INFO - 	found org.xerial.snappy#snappy-java;1.1.8.4 in central
[2025-09-01 03:42:37,172] {subprocess.py:92} INFO - 	found org.slf4j#slf4j-api;1.7.32 in central
[2025-09-01 03:42:37,186] {subprocess.py:92} INFO - 	found org.apache.hadoop#hadoop-client-runtime;3.3.2 in central
[2025-09-01 03:42:37,194] {subprocess.py:92} INFO - 	found org.spark-project.spark#unused;1.0.0 in central
[2025-09-01 03:42:37,209] {subprocess.py:92} INFO - 	found org.apache.hadoop#hadoop-client-api;3.3.2 in central
[2025-09-01 03:42:37,221] {subprocess.py:92} INFO - 	found commons-logging#commons-logging;1.1.3 in central
[2025-09-01 03:42:37,230] {subprocess.py:92} INFO - 	found com.google.code.findbugs#jsr305;3.0.0 in central
[2025-09-01 03:42:37,237] {subprocess.py:92} INFO - 	found org.apache.commons#commons-pool2;2.11.1 in central
[2025-09-01 03:42:37,252] {subprocess.py:92} INFO - :: resolution report :: resolve 314ms :: artifacts dl 8ms
[2025-09-01 03:42:37,253] {subprocess.py:92} INFO - 	:: modules in use:
[2025-09-01 03:42:37,253] {subprocess.py:92} INFO - 	com.google.code.findbugs#jsr305;3.0.0 from central in [default]
[2025-09-01 03:42:37,253] {subprocess.py:92} INFO - 	commons-logging#commons-logging;1.1.3 from central in [default]
[2025-09-01 03:42:37,253] {subprocess.py:92} INFO - 	org.apache.commons#commons-pool2;2.11.1 from central in [default]
[2025-09-01 03:42:37,253] {subprocess.py:92} INFO - 	org.apache.hadoop#hadoop-client-api;3.3.2 from central in [default]
[2025-09-01 03:42:37,253] {subprocess.py:92} INFO - 	org.apache.hadoop#hadoop-client-runtime;3.3.2 from central in [default]
[2025-09-01 03:42:37,253] {subprocess.py:92} INFO - 	org.apache.kafka#kafka-clients;2.8.1 from central in [default]
[2025-09-01 03:42:37,253] {subprocess.py:92} INFO - 	org.apache.spark#spark-sql-kafka-0-10_2.12;3.3.1 from central in [default]
[2025-09-01 03:42:37,253] {subprocess.py:92} INFO - 	org.apache.spark#spark-token-provider-kafka-0-10_2.12;3.3.1 from central in [default]
[2025-09-01 03:42:37,253] {subprocess.py:92} INFO - 	org.lz4#lz4-java;1.8.0 from central in [default]
[2025-09-01 03:42:37,253] {subprocess.py:92} INFO - 	org.slf4j#slf4j-api;1.7.32 from central in [default]
[2025-09-01 03:42:37,253] {subprocess.py:92} INFO - 	org.spark-project.spark#unused;1.0.0 from central in [default]
[2025-09-01 03:42:37,253] {subprocess.py:92} INFO - 	org.xerial.snappy#snappy-java;1.1.8.4 from central in [default]
[2025-09-01 03:42:37,253] {subprocess.py:92} INFO - 	---------------------------------------------------------------------
[2025-09-01 03:42:37,253] {subprocess.py:92} INFO - 	|                  |            modules            ||   artifacts   |
[2025-09-01 03:42:37,253] {subprocess.py:92} INFO - 	|       conf       | number| search|dwnlded|evicted|| number|dwnlded|
[2025-09-01 03:42:37,253] {subprocess.py:92} INFO - 	---------------------------------------------------------------------
[2025-09-01 03:42:37,253] {subprocess.py:92} INFO - 	|      default     |   12  |   0   |   0   |   0   ||   12  |   0   |
[2025-09-01 03:42:37,253] {subprocess.py:92} INFO - 	---------------------------------------------------------------------
[2025-09-01 03:42:37,257] {subprocess.py:92} INFO - :: retrieving :: org.apache.spark#spark-submit-parent-e1a848d7-8d3b-4939-a05c-0785cf1e1229
[2025-09-01 03:42:37,258] {subprocess.py:92} INFO - 	confs: [default]
[2025-09-01 03:42:37,262] {subprocess.py:92} INFO - 	0 artifacts copied, 12 already retrieved (0kB/5ms)
[2025-09-01 03:42:37,410] {subprocess.py:92} INFO - 25/09/01 03:42:37 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
[2025-09-01 03:42:38,184] {subprocess.py:92} INFO - 25/09/01 03:42:38 INFO SparkContext: Running Spark version 3.3.1
[2025-09-01 03:42:38,197] {subprocess.py:92} INFO - 25/09/01 03:42:38 INFO ResourceUtils: ==============================================================
[2025-09-01 03:42:38,197] {subprocess.py:92} INFO - 25/09/01 03:42:38 INFO ResourceUtils: No custom resources configured for spark.driver.
[2025-09-01 03:42:38,197] {subprocess.py:92} INFO - 25/09/01 03:42:38 INFO ResourceUtils: ==============================================================
[2025-09-01 03:42:38,198] {subprocess.py:92} INFO - 25/09/01 03:42:38 INFO SparkContext: Submitted application: KafkaToHDFSWeather
[2025-09-01 03:42:38,211] {subprocess.py:92} INFO - 25/09/01 03:42:38 INFO ResourceProfile: Default ResourceProfile created, executor resources: Map(cores -> name: cores, amount: 1, script: , vendor: , memory -> name: memory, amount: 1024, script: , vendor: , offHeap -> name: offHeap, amount: 0, script: , vendor: ), task resources: Map(cpus -> name: cpus, amount: 1.0)
[2025-09-01 03:42:38,218] {subprocess.py:92} INFO - 25/09/01 03:42:38 INFO ResourceProfile: Limiting resource is cpu
[2025-09-01 03:42:38,218] {subprocess.py:92} INFO - 25/09/01 03:42:38 INFO ResourceProfileManager: Added ResourceProfile id: 0
[2025-09-01 03:42:38,251] {subprocess.py:92} INFO - 25/09/01 03:42:38 INFO SecurityManager: Changing view acls to: ***
[2025-09-01 03:42:38,251] {subprocess.py:92} INFO - 25/09/01 03:42:38 INFO SecurityManager: Changing modify acls to: ***
[2025-09-01 03:42:38,251] {subprocess.py:92} INFO - 25/09/01 03:42:38 INFO SecurityManager: Changing view acls groups to:
[2025-09-01 03:42:38,252] {subprocess.py:92} INFO - 25/09/01 03:42:38 INFO SecurityManager: Changing modify acls groups to:
[2025-09-01 03:42:38,252] {subprocess.py:92} INFO - 25/09/01 03:42:38 INFO SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users  with view permissions: Set(***); groups with view permissions: Set(); users  with modify permissions: Set(***); groups with modify permissions: Set()
[2025-09-01 03:42:38,423] {subprocess.py:92} INFO - 25/09/01 03:42:38 INFO Utils: Successfully started service 'sparkDriver' on port 43045.
[2025-09-01 03:42:38,440] {subprocess.py:92} INFO - 25/09/01 03:42:38 INFO SparkEnv: Registering MapOutputTracker
[2025-09-01 03:42:38,460] {subprocess.py:92} INFO - 25/09/01 03:42:38 INFO SparkEnv: Registering BlockManagerMaster
[2025-09-01 03:42:38,471] {subprocess.py:92} INFO - 25/09/01 03:42:38 INFO BlockManagerMasterEndpoint: Using org.apache.spark.storage.DefaultTopologyMapper for getting topology information
[2025-09-01 03:42:38,471] {subprocess.py:92} INFO - 25/09/01 03:42:38 INFO BlockManagerMasterEndpoint: BlockManagerMasterEndpoint up
[2025-09-01 03:42:38,475] {subprocess.py:92} INFO - 25/09/01 03:42:38 INFO SparkEnv: Registering BlockManagerMasterHeartbeat
[2025-09-01 03:42:38,497] {subprocess.py:92} INFO - 25/09/01 03:42:38 INFO DiskBlockManager: Created local directory at /tmp/blockmgr-61c6b7fa-c572-43bd-bc89-6b0c8c479ab1
[2025-09-01 03:42:38,513] {subprocess.py:92} INFO - 25/09/01 03:42:38 INFO MemoryStore: MemoryStore started with capacity 434.4 MiB
[2025-09-01 03:42:38,526] {subprocess.py:92} INFO - 25/09/01 03:42:38 INFO SparkEnv: Registering OutputCommitCoordinator
[2025-09-01 03:42:38,670] {subprocess.py:92} INFO - 25/09/01 03:42:38 WARN Utils: Service 'SparkUI' could not bind on port 4040. Attempting port 4041.
[2025-09-01 03:42:38,670] {subprocess.py:92} INFO - 25/09/01 03:42:38 WARN Utils: Service 'SparkUI' could not bind on port 4041. Attempting port 4042.
[2025-09-01 03:42:38,670] {subprocess.py:92} INFO - 25/09/01 03:42:38 WARN Utils: Service 'SparkUI' could not bind on port 4042. Attempting port 4043.
[2025-09-01 03:42:38,671] {subprocess.py:92} INFO - 25/09/01 03:42:38 WARN Utils: Service 'SparkUI' could not bind on port 4043. Attempting port 4044.
[2025-09-01 03:42:38,679] {subprocess.py:92} INFO - 25/09/01 03:42:38 INFO Utils: Successfully started service 'SparkUI' on port 4044.
[2025-09-01 03:42:38,715] {subprocess.py:92} INFO - 25/09/01 03:42:38 INFO SparkContext: Added JAR file:///home/***/.ivy2/jars/org.apache.spark_spark-sql-kafka-0-10_2.12-3.3.1.jar at spark://e66737cfc193:43045/jars/org.apache.spark_spark-sql-kafka-0-10_2.12-3.3.1.jar with timestamp 1756698158176
[2025-09-01 03:42:38,715] {subprocess.py:92} INFO - 25/09/01 03:42:38 INFO SparkContext: Added JAR file:///home/***/.ivy2/jars/org.apache.spark_spark-token-provider-kafka-0-10_2.12-3.3.1.jar at spark://e66737cfc193:43045/jars/org.apache.spark_spark-token-provider-kafka-0-10_2.12-3.3.1.jar with timestamp 1756698158176
[2025-09-01 03:42:38,715] {subprocess.py:92} INFO - 25/09/01 03:42:38 INFO SparkContext: Added JAR file:///home/***/.ivy2/jars/org.apache.kafka_kafka-clients-2.8.1.jar at spark://e66737cfc193:43045/jars/org.apache.kafka_kafka-clients-2.8.1.jar with timestamp 1756698158176
[2025-09-01 03:42:38,715] {subprocess.py:92} INFO - 25/09/01 03:42:38 INFO SparkContext: Added JAR file:///home/***/.ivy2/jars/com.google.code.findbugs_jsr305-3.0.0.jar at spark://e66737cfc193:43045/jars/com.google.code.findbugs_jsr305-3.0.0.jar with timestamp 1756698158176
[2025-09-01 03:42:38,715] {subprocess.py:92} INFO - 25/09/01 03:42:38 INFO SparkContext: Added JAR file:///home/***/.ivy2/jars/org.apache.commons_commons-pool2-2.11.1.jar at spark://e66737cfc193:43045/jars/org.apache.commons_commons-pool2-2.11.1.jar with timestamp 1756698158176
[2025-09-01 03:42:38,715] {subprocess.py:92} INFO - 25/09/01 03:42:38 INFO SparkContext: Added JAR file:///home/***/.ivy2/jars/org.spark-project.spark_unused-1.0.0.jar at spark://e66737cfc193:43045/jars/org.spark-project.spark_unused-1.0.0.jar with timestamp 1756698158176
[2025-09-01 03:42:38,716] {subprocess.py:92} INFO - 25/09/01 03:42:38 INFO SparkContext: Added JAR file:///home/***/.ivy2/jars/org.apache.hadoop_hadoop-client-runtime-3.3.2.jar at spark://e66737cfc193:43045/jars/org.apache.hadoop_hadoop-client-runtime-3.3.2.jar with timestamp 1756698158176
[2025-09-01 03:42:38,716] {subprocess.py:92} INFO - 25/09/01 03:42:38 INFO SparkContext: Added JAR file:///home/***/.ivy2/jars/org.lz4_lz4-java-1.8.0.jar at spark://e66737cfc193:43045/jars/org.lz4_lz4-java-1.8.0.jar with timestamp 1756698158176
[2025-09-01 03:42:38,716] {subprocess.py:92} INFO - 25/09/01 03:42:38 INFO SparkContext: Added JAR file:///home/***/.ivy2/jars/org.xerial.snappy_snappy-java-1.1.8.4.jar at spark://e66737cfc193:43045/jars/org.xerial.snappy_snappy-java-1.1.8.4.jar with timestamp 1756698158176
[2025-09-01 03:42:38,716] {subprocess.py:92} INFO - 25/09/01 03:42:38 INFO SparkContext: Added JAR file:///home/***/.ivy2/jars/org.slf4j_slf4j-api-1.7.32.jar at spark://e66737cfc193:43045/jars/org.slf4j_slf4j-api-1.7.32.jar with timestamp 1756698158176
[2025-09-01 03:42:38,716] {subprocess.py:92} INFO - 25/09/01 03:42:38 INFO SparkContext: Added JAR file:///home/***/.ivy2/jars/org.apache.hadoop_hadoop-client-api-3.3.2.jar at spark://e66737cfc193:43045/jars/org.apache.hadoop_hadoop-client-api-3.3.2.jar with timestamp 1756698158176
[2025-09-01 03:42:38,716] {subprocess.py:92} INFO - 25/09/01 03:42:38 INFO SparkContext: Added JAR file:///home/***/.ivy2/jars/commons-logging_commons-logging-1.1.3.jar at spark://e66737cfc193:43045/jars/commons-logging_commons-logging-1.1.3.jar with timestamp 1756698158176
[2025-09-01 03:42:38,719] {subprocess.py:92} INFO - 25/09/01 03:42:38 INFO SparkContext: Added file file:///home/***/.ivy2/jars/org.apache.spark_spark-sql-kafka-0-10_2.12-3.3.1.jar at file:///home/***/.ivy2/jars/org.apache.spark_spark-sql-kafka-0-10_2.12-3.3.1.jar with timestamp 1756698158176
[2025-09-01 03:42:38,720] {subprocess.py:92} INFO - 25/09/01 03:42:38 INFO Utils: Copying /home/***/.ivy2/jars/org.apache.spark_spark-sql-kafka-0-10_2.12-3.3.1.jar to /tmp/spark-a45daf75-2ff1-4924-895e-308278d69463/userFiles-dce3bb8d-f630-4cfb-996f-fe80458000b4/org.apache.spark_spark-sql-kafka-0-10_2.12-3.3.1.jar
[2025-09-01 03:42:38,730] {subprocess.py:92} INFO - 25/09/01 03:42:38 INFO SparkContext: Added file file:///home/***/.ivy2/jars/org.apache.spark_spark-token-provider-kafka-0-10_2.12-3.3.1.jar at file:///home/***/.ivy2/jars/org.apache.spark_spark-token-provider-kafka-0-10_2.12-3.3.1.jar with timestamp 1756698158176
[2025-09-01 03:42:38,731] {subprocess.py:92} INFO - 25/09/01 03:42:38 INFO Utils: Copying /home/***/.ivy2/jars/org.apache.spark_spark-token-provider-kafka-0-10_2.12-3.3.1.jar to /tmp/spark-a45daf75-2ff1-4924-895e-308278d69463/userFiles-dce3bb8d-f630-4cfb-996f-fe80458000b4/org.apache.spark_spark-token-provider-kafka-0-10_2.12-3.3.1.jar
[2025-09-01 03:42:38,735] {subprocess.py:92} INFO - 25/09/01 03:42:38 INFO SparkContext: Added file file:///home/***/.ivy2/jars/org.apache.kafka_kafka-clients-2.8.1.jar at file:///home/***/.ivy2/jars/org.apache.kafka_kafka-clients-2.8.1.jar with timestamp 1756698158176
[2025-09-01 03:42:38,735] {subprocess.py:92} INFO - 25/09/01 03:42:38 INFO Utils: Copying /home/***/.ivy2/jars/org.apache.kafka_kafka-clients-2.8.1.jar to /tmp/spark-a45daf75-2ff1-4924-895e-308278d69463/userFiles-dce3bb8d-f630-4cfb-996f-fe80458000b4/org.apache.kafka_kafka-clients-2.8.1.jar
[2025-09-01 03:42:38,740] {subprocess.py:92} INFO - 25/09/01 03:42:38 INFO SparkContext: Added file file:///home/***/.ivy2/jars/com.google.code.findbugs_jsr305-3.0.0.jar at file:///home/***/.ivy2/jars/com.google.code.findbugs_jsr305-3.0.0.jar with timestamp 1756698158176
[2025-09-01 03:42:38,740] {subprocess.py:92} INFO - 25/09/01 03:42:38 INFO Utils: Copying /home/***/.ivy2/jars/com.google.code.findbugs_jsr305-3.0.0.jar to /tmp/spark-a45daf75-2ff1-4924-895e-308278d69463/userFiles-dce3bb8d-f630-4cfb-996f-fe80458000b4/com.google.code.findbugs_jsr305-3.0.0.jar
[2025-09-01 03:42:38,744] {subprocess.py:92} INFO - 25/09/01 03:42:38 INFO SparkContext: Added file file:///home/***/.ivy2/jars/org.apache.commons_commons-pool2-2.11.1.jar at file:///home/***/.ivy2/jars/org.apache.commons_commons-pool2-2.11.1.jar with timestamp 1756698158176
[2025-09-01 03:42:38,744] {subprocess.py:92} INFO - 25/09/01 03:42:38 INFO Utils: Copying /home/***/.ivy2/jars/org.apache.commons_commons-pool2-2.11.1.jar to /tmp/spark-a45daf75-2ff1-4924-895e-308278d69463/userFiles-dce3bb8d-f630-4cfb-996f-fe80458000b4/org.apache.commons_commons-pool2-2.11.1.jar
[2025-09-01 03:42:38,747] {subprocess.py:92} INFO - 25/09/01 03:42:38 INFO SparkContext: Added file file:///home/***/.ivy2/jars/org.spark-project.spark_unused-1.0.0.jar at file:///home/***/.ivy2/jars/org.spark-project.spark_unused-1.0.0.jar with timestamp 1756698158176
[2025-09-01 03:42:38,747] {subprocess.py:92} INFO - 25/09/01 03:42:38 INFO Utils: Copying /home/***/.ivy2/jars/org.spark-project.spark_unused-1.0.0.jar to /tmp/spark-a45daf75-2ff1-4924-895e-308278d69463/userFiles-dce3bb8d-f630-4cfb-996f-fe80458000b4/org.spark-project.spark_unused-1.0.0.jar
[2025-09-01 03:42:38,751] {subprocess.py:92} INFO - 25/09/01 03:42:38 INFO SparkContext: Added file file:///home/***/.ivy2/jars/org.apache.hadoop_hadoop-client-runtime-3.3.2.jar at file:///home/***/.ivy2/jars/org.apache.hadoop_hadoop-client-runtime-3.3.2.jar with timestamp 1756698158176
[2025-09-01 03:42:38,751] {subprocess.py:92} INFO - 25/09/01 03:42:38 INFO Utils: Copying /home/***/.ivy2/jars/org.apache.hadoop_hadoop-client-runtime-3.3.2.jar to /tmp/spark-a45daf75-2ff1-4924-895e-308278d69463/userFiles-dce3bb8d-f630-4cfb-996f-fe80458000b4/org.apache.hadoop_hadoop-client-runtime-3.3.2.jar
[2025-09-01 03:42:38,768] {subprocess.py:92} INFO - 25/09/01 03:42:38 INFO SparkContext: Added file file:///home/***/.ivy2/jars/org.lz4_lz4-java-1.8.0.jar at file:///home/***/.ivy2/jars/org.lz4_lz4-java-1.8.0.jar with timestamp 1756698158176
[2025-09-01 03:42:38,768] {subprocess.py:92} INFO - 25/09/01 03:42:38 INFO Utils: Copying /home/***/.ivy2/jars/org.lz4_lz4-java-1.8.0.jar to /tmp/spark-a45daf75-2ff1-4924-895e-308278d69463/userFiles-dce3bb8d-f630-4cfb-996f-fe80458000b4/org.lz4_lz4-java-1.8.0.jar
[2025-09-01 03:42:38,773] {subprocess.py:92} INFO - 25/09/01 03:42:38 INFO SparkContext: Added file file:///home/***/.ivy2/jars/org.xerial.snappy_snappy-java-1.1.8.4.jar at file:///home/***/.ivy2/jars/org.xerial.snappy_snappy-java-1.1.8.4.jar with timestamp 1756698158176
[2025-09-01 03:42:38,773] {subprocess.py:92} INFO - 25/09/01 03:42:38 INFO Utils: Copying /home/***/.ivy2/jars/org.xerial.snappy_snappy-java-1.1.8.4.jar to /tmp/spark-a45daf75-2ff1-4924-895e-308278d69463/userFiles-dce3bb8d-f630-4cfb-996f-fe80458000b4/org.xerial.snappy_snappy-java-1.1.8.4.jar
[2025-09-01 03:42:38,779] {subprocess.py:92} INFO - 25/09/01 03:42:38 INFO SparkContext: Added file file:///home/***/.ivy2/jars/org.slf4j_slf4j-api-1.7.32.jar at file:///home/***/.ivy2/jars/org.slf4j_slf4j-api-1.7.32.jar with timestamp 1756698158176
[2025-09-01 03:42:38,779] {subprocess.py:92} INFO - 25/09/01 03:42:38 INFO Utils: Copying /home/***/.ivy2/jars/org.slf4j_slf4j-api-1.7.32.jar to /tmp/spark-a45daf75-2ff1-4924-895e-308278d69463/userFiles-dce3bb8d-f630-4cfb-996f-fe80458000b4/org.slf4j_slf4j-api-1.7.32.jar
[2025-09-01 03:42:38,782] {subprocess.py:92} INFO - 25/09/01 03:42:38 INFO SparkContext: Added file file:///home/***/.ivy2/jars/org.apache.hadoop_hadoop-client-api-3.3.2.jar at file:///home/***/.ivy2/jars/org.apache.hadoop_hadoop-client-api-3.3.2.jar with timestamp 1756698158176
[2025-09-01 03:42:38,783] {subprocess.py:92} INFO - 25/09/01 03:42:38 INFO Utils: Copying /home/***/.ivy2/jars/org.apache.hadoop_hadoop-client-api-3.3.2.jar to /tmp/spark-a45daf75-2ff1-4924-895e-308278d69463/userFiles-dce3bb8d-f630-4cfb-996f-fe80458000b4/org.apache.hadoop_hadoop-client-api-3.3.2.jar
[2025-09-01 03:42:38,799] {subprocess.py:92} INFO - 25/09/01 03:42:38 INFO SparkContext: Added file file:///home/***/.ivy2/jars/commons-logging_commons-logging-1.1.3.jar at file:///home/***/.ivy2/jars/commons-logging_commons-logging-1.1.3.jar with timestamp 1756698158176
[2025-09-01 03:42:38,799] {subprocess.py:92} INFO - 25/09/01 03:42:38 INFO Utils: Copying /home/***/.ivy2/jars/commons-logging_commons-logging-1.1.3.jar to /tmp/spark-a45daf75-2ff1-4924-895e-308278d69463/userFiles-dce3bb8d-f630-4cfb-996f-fe80458000b4/commons-logging_commons-logging-1.1.3.jar
[2025-09-01 03:42:38,871] {subprocess.py:92} INFO - 25/09/01 03:42:38 INFO Executor: Starting executor ID driver on host e66737cfc193
[2025-09-01 03:42:38,878] {subprocess.py:92} INFO - 25/09/01 03:42:38 INFO Executor: Starting executor with user classpath (userClassPathFirst = false): ''
[2025-09-01 03:42:38,888] {subprocess.py:92} INFO - 25/09/01 03:42:38 INFO Executor: Fetching file:///home/***/.ivy2/jars/commons-logging_commons-logging-1.1.3.jar with timestamp 1756698158176
[2025-09-01 03:42:38,899] {subprocess.py:92} INFO - 25/09/01 03:42:38 INFO Utils: /home/***/.ivy2/jars/commons-logging_commons-logging-1.1.3.jar has been previously copied to /tmp/spark-a45daf75-2ff1-4924-895e-308278d69463/userFiles-dce3bb8d-f630-4cfb-996f-fe80458000b4/commons-logging_commons-logging-1.1.3.jar
[2025-09-01 03:42:38,902] {subprocess.py:92} INFO - 25/09/01 03:42:38 INFO Executor: Fetching file:///home/***/.ivy2/jars/org.spark-project.spark_unused-1.0.0.jar with timestamp 1756698158176
[2025-09-01 03:42:38,903] {subprocess.py:92} INFO - 25/09/01 03:42:38 INFO Utils: /home/***/.ivy2/jars/org.spark-project.spark_unused-1.0.0.jar has been previously copied to /tmp/spark-a45daf75-2ff1-4924-895e-308278d69463/userFiles-dce3bb8d-f630-4cfb-996f-fe80458000b4/org.spark-project.spark_unused-1.0.0.jar
[2025-09-01 03:42:38,906] {subprocess.py:92} INFO - 25/09/01 03:42:38 INFO Executor: Fetching file:///home/***/.ivy2/jars/org.apache.spark_spark-sql-kafka-0-10_2.12-3.3.1.jar with timestamp 1756698158176
[2025-09-01 03:42:38,913] {subprocess.py:92} INFO - 25/09/01 03:42:38 INFO Utils: /home/***/.ivy2/jars/org.apache.spark_spark-sql-kafka-0-10_2.12-3.3.1.jar has been previously copied to /tmp/spark-a45daf75-2ff1-4924-895e-308278d69463/userFiles-dce3bb8d-f630-4cfb-996f-fe80458000b4/org.apache.spark_spark-sql-kafka-0-10_2.12-3.3.1.jar
[2025-09-01 03:42:38,916] {subprocess.py:92} INFO - 25/09/01 03:42:38 INFO Executor: Fetching file:///home/***/.ivy2/jars/org.apache.hadoop_hadoop-client-api-3.3.2.jar with timestamp 1756698158176
[2025-09-01 03:42:38,937] {subprocess.py:92} INFO - 25/09/01 03:42:38 INFO Utils: /home/***/.ivy2/jars/org.apache.hadoop_hadoop-client-api-3.3.2.jar has been previously copied to /tmp/spark-a45daf75-2ff1-4924-895e-308278d69463/userFiles-dce3bb8d-f630-4cfb-996f-fe80458000b4/org.apache.hadoop_hadoop-client-api-3.3.2.jar
[2025-09-01 03:42:38,940] {subprocess.py:92} INFO - 25/09/01 03:42:38 INFO Executor: Fetching file:///home/***/.ivy2/jars/org.apache.hadoop_hadoop-client-runtime-3.3.2.jar with timestamp 1756698158176
[2025-09-01 03:42:38,963] {subprocess.py:92} INFO - 25/09/01 03:42:38 INFO Utils: /home/***/.ivy2/jars/org.apache.hadoop_hadoop-client-runtime-3.3.2.jar has been previously copied to /tmp/spark-a45daf75-2ff1-4924-895e-308278d69463/userFiles-dce3bb8d-f630-4cfb-996f-fe80458000b4/org.apache.hadoop_hadoop-client-runtime-3.3.2.jar
[2025-09-01 03:42:38,966] {subprocess.py:92} INFO - 25/09/01 03:42:38 INFO Executor: Fetching file:///home/***/.ivy2/jars/org.slf4j_slf4j-api-1.7.32.jar with timestamp 1756698158176
[2025-09-01 03:42:38,966] {subprocess.py:92} INFO - 25/09/01 03:42:38 INFO Utils: /home/***/.ivy2/jars/org.slf4j_slf4j-api-1.7.32.jar has been previously copied to /tmp/spark-a45daf75-2ff1-4924-895e-308278d69463/userFiles-dce3bb8d-f630-4cfb-996f-fe80458000b4/org.slf4j_slf4j-api-1.7.32.jar
[2025-09-01 03:42:38,970] {subprocess.py:92} INFO - 25/09/01 03:42:38 INFO Executor: Fetching file:///home/***/.ivy2/jars/org.lz4_lz4-java-1.8.0.jar with timestamp 1756698158176
[2025-09-01 03:42:38,970] {subprocess.py:92} INFO - 25/09/01 03:42:38 INFO Utils: /home/***/.ivy2/jars/org.lz4_lz4-java-1.8.0.jar has been previously copied to /tmp/spark-a45daf75-2ff1-4924-895e-308278d69463/userFiles-dce3bb8d-f630-4cfb-996f-fe80458000b4/org.lz4_lz4-java-1.8.0.jar
[2025-09-01 03:42:38,974] {subprocess.py:92} INFO - 25/09/01 03:42:38 INFO Executor: Fetching file:///home/***/.ivy2/jars/org.apache.commons_commons-pool2-2.11.1.jar with timestamp 1756698158176
[2025-09-01 03:42:38,974] {subprocess.py:92} INFO - 25/09/01 03:42:38 INFO Utils: /home/***/.ivy2/jars/org.apache.commons_commons-pool2-2.11.1.jar has been previously copied to /tmp/spark-a45daf75-2ff1-4924-895e-308278d69463/userFiles-dce3bb8d-f630-4cfb-996f-fe80458000b4/org.apache.commons_commons-pool2-2.11.1.jar
[2025-09-01 03:42:38,977] {subprocess.py:92} INFO - 25/09/01 03:42:38 INFO Executor: Fetching file:///home/***/.ivy2/jars/com.google.code.findbugs_jsr305-3.0.0.jar with timestamp 1756698158176
[2025-09-01 03:42:38,977] {subprocess.py:92} INFO - 25/09/01 03:42:38 INFO Utils: /home/***/.ivy2/jars/com.google.code.findbugs_jsr305-3.0.0.jar has been previously copied to /tmp/spark-a45daf75-2ff1-4924-895e-308278d69463/userFiles-dce3bb8d-f630-4cfb-996f-fe80458000b4/com.google.code.findbugs_jsr305-3.0.0.jar
[2025-09-01 03:42:38,981] {subprocess.py:92} INFO - 25/09/01 03:42:38 INFO Executor: Fetching file:///home/***/.ivy2/jars/org.apache.spark_spark-token-provider-kafka-0-10_2.12-3.3.1.jar with timestamp 1756698158176
[2025-09-01 03:42:38,981] {subprocess.py:92} INFO - 25/09/01 03:42:38 INFO Utils: /home/***/.ivy2/jars/org.apache.spark_spark-token-provider-kafka-0-10_2.12-3.3.1.jar has been previously copied to /tmp/spark-a45daf75-2ff1-4924-895e-308278d69463/userFiles-dce3bb8d-f630-4cfb-996f-fe80458000b4/org.apache.spark_spark-token-provider-kafka-0-10_2.12-3.3.1.jar
[2025-09-01 03:42:38,984] {subprocess.py:92} INFO - 25/09/01 03:42:38 INFO Executor: Fetching file:///home/***/.ivy2/jars/org.apache.kafka_kafka-clients-2.8.1.jar with timestamp 1756698158176
[2025-09-01 03:42:38,988] {subprocess.py:92} INFO - 25/09/01 03:42:38 INFO Utils: /home/***/.ivy2/jars/org.apache.kafka_kafka-clients-2.8.1.jar has been previously copied to /tmp/spark-a45daf75-2ff1-4924-895e-308278d69463/userFiles-dce3bb8d-f630-4cfb-996f-fe80458000b4/org.apache.kafka_kafka-clients-2.8.1.jar
[2025-09-01 03:42:38,993] {subprocess.py:92} INFO - 25/09/01 03:42:38 INFO Executor: Fetching file:///home/***/.ivy2/jars/org.xerial.snappy_snappy-java-1.1.8.4.jar with timestamp 1756698158176
[2025-09-01 03:42:38,994] {subprocess.py:92} INFO - 25/09/01 03:42:38 INFO Utils: /home/***/.ivy2/jars/org.xerial.snappy_snappy-java-1.1.8.4.jar has been previously copied to /tmp/spark-a45daf75-2ff1-4924-895e-308278d69463/userFiles-dce3bb8d-f630-4cfb-996f-fe80458000b4/org.xerial.snappy_snappy-java-1.1.8.4.jar
[2025-09-01 03:42:39,001] {subprocess.py:92} INFO - 25/09/01 03:42:39 INFO Executor: Fetching spark://e66737cfc193:43045/jars/org.xerial.snappy_snappy-java-1.1.8.4.jar with timestamp 1756698158176
[2025-09-01 03:42:39,041] {subprocess.py:92} INFO - 25/09/01 03:42:39 INFO TransportClientFactory: Successfully created connection to e66737cfc193/172.20.0.18:43045 after 28 ms (0 ms spent in bootstraps)
[2025-09-01 03:42:39,044] {subprocess.py:92} INFO - 25/09/01 03:42:39 INFO Utils: Fetching spark://e66737cfc193:43045/jars/org.xerial.snappy_snappy-java-1.1.8.4.jar to /tmp/spark-a45daf75-2ff1-4924-895e-308278d69463/userFiles-dce3bb8d-f630-4cfb-996f-fe80458000b4/fetchFileTemp6889487645762909795.tmp
[2025-09-01 03:42:39,081] {subprocess.py:92} INFO - 25/09/01 03:42:39 INFO Utils: /tmp/spark-a45daf75-2ff1-4924-895e-308278d69463/userFiles-dce3bb8d-f630-4cfb-996f-fe80458000b4/fetchFileTemp6889487645762909795.tmp has been previously copied to /tmp/spark-a45daf75-2ff1-4924-895e-308278d69463/userFiles-dce3bb8d-f630-4cfb-996f-fe80458000b4/org.xerial.snappy_snappy-java-1.1.8.4.jar
[2025-09-01 03:42:39,086] {subprocess.py:92} INFO - 25/09/01 03:42:39 INFO Executor: Adding file:/tmp/spark-a45daf75-2ff1-4924-895e-308278d69463/userFiles-dce3bb8d-f630-4cfb-996f-fe80458000b4/org.xerial.snappy_snappy-java-1.1.8.4.jar to class loader
[2025-09-01 03:42:39,086] {subprocess.py:92} INFO - 25/09/01 03:42:39 INFO Executor: Fetching spark://e66737cfc193:43045/jars/org.slf4j_slf4j-api-1.7.32.jar with timestamp 1756698158176
[2025-09-01 03:42:39,087] {subprocess.py:92} INFO - 25/09/01 03:42:39 INFO Utils: Fetching spark://e66737cfc193:43045/jars/org.slf4j_slf4j-api-1.7.32.jar to /tmp/spark-a45daf75-2ff1-4924-895e-308278d69463/userFiles-dce3bb8d-f630-4cfb-996f-fe80458000b4/fetchFileTemp743900529967290023.tmp
[2025-09-01 03:42:39,089] {subprocess.py:92} INFO - 25/09/01 03:42:39 INFO Utils: /tmp/spark-a45daf75-2ff1-4924-895e-308278d69463/userFiles-dce3bb8d-f630-4cfb-996f-fe80458000b4/fetchFileTemp743900529967290023.tmp has been previously copied to /tmp/spark-a45daf75-2ff1-4924-895e-308278d69463/userFiles-dce3bb8d-f630-4cfb-996f-fe80458000b4/org.slf4j_slf4j-api-1.7.32.jar
[2025-09-01 03:42:39,093] {subprocess.py:92} INFO - 25/09/01 03:42:39 INFO Executor: Adding file:/tmp/spark-a45daf75-2ff1-4924-895e-308278d69463/userFiles-dce3bb8d-f630-4cfb-996f-fe80458000b4/org.slf4j_slf4j-api-1.7.32.jar to class loader
[2025-09-01 03:42:39,094] {subprocess.py:92} INFO - 25/09/01 03:42:39 INFO Executor: Fetching spark://e66737cfc193:43045/jars/commons-logging_commons-logging-1.1.3.jar with timestamp 1756698158176
[2025-09-01 03:42:39,094] {subprocess.py:92} INFO - 25/09/01 03:42:39 INFO Utils: Fetching spark://e66737cfc193:43045/jars/commons-logging_commons-logging-1.1.3.jar to /tmp/spark-a45daf75-2ff1-4924-895e-308278d69463/userFiles-dce3bb8d-f630-4cfb-996f-fe80458000b4/fetchFileTemp17128879122554514310.tmp
[2025-09-01 03:42:39,096] {subprocess.py:92} INFO - 25/09/01 03:42:39 INFO Utils: /tmp/spark-a45daf75-2ff1-4924-895e-308278d69463/userFiles-dce3bb8d-f630-4cfb-996f-fe80458000b4/fetchFileTemp17128879122554514310.tmp has been previously copied to /tmp/spark-a45daf75-2ff1-4924-895e-308278d69463/userFiles-dce3bb8d-f630-4cfb-996f-fe80458000b4/commons-logging_commons-logging-1.1.3.jar
[2025-09-01 03:42:39,101] {subprocess.py:92} INFO - 25/09/01 03:42:39 INFO Executor: Adding file:/tmp/spark-a45daf75-2ff1-4924-895e-308278d69463/userFiles-dce3bb8d-f630-4cfb-996f-fe80458000b4/commons-logging_commons-logging-1.1.3.jar to class loader
[2025-09-01 03:42:39,101] {subprocess.py:92} INFO - 25/09/01 03:42:39 INFO Executor: Fetching spark://e66737cfc193:43045/jars/org.apache.kafka_kafka-clients-2.8.1.jar with timestamp 1756698158176
[2025-09-01 03:42:39,102] {subprocess.py:92} INFO - 25/09/01 03:42:39 INFO Utils: Fetching spark://e66737cfc193:43045/jars/org.apache.kafka_kafka-clients-2.8.1.jar to /tmp/spark-a45daf75-2ff1-4924-895e-308278d69463/userFiles-dce3bb8d-f630-4cfb-996f-fe80458000b4/fetchFileTemp9264392335857174452.tmp
[2025-09-01 03:42:39,148] {subprocess.py:92} INFO - 25/09/01 03:42:39 INFO Utils: /tmp/spark-a45daf75-2ff1-4924-895e-308278d69463/userFiles-dce3bb8d-f630-4cfb-996f-fe80458000b4/fetchFileTemp9264392335857174452.tmp has been previously copied to /tmp/spark-a45daf75-2ff1-4924-895e-308278d69463/userFiles-dce3bb8d-f630-4cfb-996f-fe80458000b4/org.apache.kafka_kafka-clients-2.8.1.jar
[2025-09-01 03:42:39,151] {subprocess.py:92} INFO - 25/09/01 03:42:39 INFO Executor: Adding file:/tmp/spark-a45daf75-2ff1-4924-895e-308278d69463/userFiles-dce3bb8d-f630-4cfb-996f-fe80458000b4/org.apache.kafka_kafka-clients-2.8.1.jar to class loader
[2025-09-01 03:42:39,151] {subprocess.py:92} INFO - 25/09/01 03:42:39 INFO Executor: Fetching spark://e66737cfc193:43045/jars/org.apache.commons_commons-pool2-2.11.1.jar with timestamp 1756698158176
[2025-09-01 03:42:39,152] {subprocess.py:92} INFO - 25/09/01 03:42:39 INFO Utils: Fetching spark://e66737cfc193:43045/jars/org.apache.commons_commons-pool2-2.11.1.jar to /tmp/spark-a45daf75-2ff1-4924-895e-308278d69463/userFiles-dce3bb8d-f630-4cfb-996f-fe80458000b4/fetchFileTemp10728242494344200421.tmp
[2025-09-01 03:42:39,154] {subprocess.py:92} INFO - 25/09/01 03:42:39 INFO Utils: /tmp/spark-a45daf75-2ff1-4924-895e-308278d69463/userFiles-dce3bb8d-f630-4cfb-996f-fe80458000b4/fetchFileTemp10728242494344200421.tmp has been previously copied to /tmp/spark-a45daf75-2ff1-4924-895e-308278d69463/userFiles-dce3bb8d-f630-4cfb-996f-fe80458000b4/org.apache.commons_commons-pool2-2.11.1.jar
[2025-09-01 03:42:39,157] {subprocess.py:92} INFO - 25/09/01 03:42:39 INFO Executor: Adding file:/tmp/spark-a45daf75-2ff1-4924-895e-308278d69463/userFiles-dce3bb8d-f630-4cfb-996f-fe80458000b4/org.apache.commons_commons-pool2-2.11.1.jar to class loader
[2025-09-01 03:42:39,157] {subprocess.py:92} INFO - 25/09/01 03:42:39 INFO Executor: Fetching spark://e66737cfc193:43045/jars/org.lz4_lz4-java-1.8.0.jar with timestamp 1756698158176
[2025-09-01 03:42:39,158] {subprocess.py:92} INFO - 25/09/01 03:42:39 INFO Utils: Fetching spark://e66737cfc193:43045/jars/org.lz4_lz4-java-1.8.0.jar to /tmp/spark-a45daf75-2ff1-4924-895e-308278d69463/userFiles-dce3bb8d-f630-4cfb-996f-fe80458000b4/fetchFileTemp13796217853335866491.tmp
[2025-09-01 03:42:39,161] {subprocess.py:92} INFO - 25/09/01 03:42:39 INFO Utils: /tmp/spark-a45daf75-2ff1-4924-895e-308278d69463/userFiles-dce3bb8d-f630-4cfb-996f-fe80458000b4/fetchFileTemp13796217853335866491.tmp has been previously copied to /tmp/spark-a45daf75-2ff1-4924-895e-308278d69463/userFiles-dce3bb8d-f630-4cfb-996f-fe80458000b4/org.lz4_lz4-java-1.8.0.jar
[2025-09-01 03:42:39,165] {subprocess.py:92} INFO - 25/09/01 03:42:39 INFO Executor: Adding file:/tmp/spark-a45daf75-2ff1-4924-895e-308278d69463/userFiles-dce3bb8d-f630-4cfb-996f-fe80458000b4/org.lz4_lz4-java-1.8.0.jar to class loader
[2025-09-01 03:42:39,165] {subprocess.py:92} INFO - 25/09/01 03:42:39 INFO Executor: Fetching spark://e66737cfc193:43045/jars/org.apache.spark_spark-token-provider-kafka-0-10_2.12-3.3.1.jar with timestamp 1756698158176
[2025-09-01 03:42:39,165] {subprocess.py:92} INFO - 25/09/01 03:42:39 INFO Utils: Fetching spark://e66737cfc193:43045/jars/org.apache.spark_spark-token-provider-kafka-0-10_2.12-3.3.1.jar to /tmp/spark-a45daf75-2ff1-4924-895e-308278d69463/userFiles-dce3bb8d-f630-4cfb-996f-fe80458000b4/fetchFileTemp9159398462066854792.tmp
[2025-09-01 03:42:39,167] {subprocess.py:92} INFO - 25/09/01 03:42:39 INFO Utils: /tmp/spark-a45daf75-2ff1-4924-895e-308278d69463/userFiles-dce3bb8d-f630-4cfb-996f-fe80458000b4/fetchFileTemp9159398462066854792.tmp has been previously copied to /tmp/spark-a45daf75-2ff1-4924-895e-308278d69463/userFiles-dce3bb8d-f630-4cfb-996f-fe80458000b4/org.apache.spark_spark-token-provider-kafka-0-10_2.12-3.3.1.jar
[2025-09-01 03:42:39,170] {subprocess.py:92} INFO - 25/09/01 03:42:39 INFO Executor: Adding file:/tmp/spark-a45daf75-2ff1-4924-895e-308278d69463/userFiles-dce3bb8d-f630-4cfb-996f-fe80458000b4/org.apache.spark_spark-token-provider-kafka-0-10_2.12-3.3.1.jar to class loader
[2025-09-01 03:42:39,171] {subprocess.py:92} INFO - 25/09/01 03:42:39 INFO Executor: Fetching spark://e66737cfc193:43045/jars/org.apache.spark_spark-sql-kafka-0-10_2.12-3.3.1.jar with timestamp 1756698158176
[2025-09-01 03:42:39,171] {subprocess.py:92} INFO - 25/09/01 03:42:39 INFO Utils: Fetching spark://e66737cfc193:43045/jars/org.apache.spark_spark-sql-kafka-0-10_2.12-3.3.1.jar to /tmp/spark-a45daf75-2ff1-4924-895e-308278d69463/userFiles-dce3bb8d-f630-4cfb-996f-fe80458000b4/fetchFileTemp18161786320879687291.tmp
[2025-09-01 03:42:39,174] {subprocess.py:92} INFO - 25/09/01 03:42:39 INFO Utils: /tmp/spark-a45daf75-2ff1-4924-895e-308278d69463/userFiles-dce3bb8d-f630-4cfb-996f-fe80458000b4/fetchFileTemp18161786320879687291.tmp has been previously copied to /tmp/spark-a45daf75-2ff1-4924-895e-308278d69463/userFiles-dce3bb8d-f630-4cfb-996f-fe80458000b4/org.apache.spark_spark-sql-kafka-0-10_2.12-3.3.1.jar
[2025-09-01 03:42:39,177] {subprocess.py:92} INFO - 25/09/01 03:42:39 INFO Executor: Adding file:/tmp/spark-a45daf75-2ff1-4924-895e-308278d69463/userFiles-dce3bb8d-f630-4cfb-996f-fe80458000b4/org.apache.spark_spark-sql-kafka-0-10_2.12-3.3.1.jar to class loader
[2025-09-01 03:42:39,177] {subprocess.py:92} INFO - 25/09/01 03:42:39 INFO Executor: Fetching spark://e66737cfc193:43045/jars/org.spark-project.spark_unused-1.0.0.jar with timestamp 1756698158176
[2025-09-01 03:42:39,178] {subprocess.py:92} INFO - 25/09/01 03:42:39 INFO Utils: Fetching spark://e66737cfc193:43045/jars/org.spark-project.spark_unused-1.0.0.jar to /tmp/spark-a45daf75-2ff1-4924-895e-308278d69463/userFiles-dce3bb8d-f630-4cfb-996f-fe80458000b4/fetchFileTemp12539656300039856421.tmp
[2025-09-01 03:42:39,179] {subprocess.py:92} INFO - 25/09/01 03:42:39 INFO Utils: /tmp/spark-a45daf75-2ff1-4924-895e-308278d69463/userFiles-dce3bb8d-f630-4cfb-996f-fe80458000b4/fetchFileTemp12539656300039856421.tmp has been previously copied to /tmp/spark-a45daf75-2ff1-4924-895e-308278d69463/userFiles-dce3bb8d-f630-4cfb-996f-fe80458000b4/org.spark-project.spark_unused-1.0.0.jar
[2025-09-01 03:42:39,183] {subprocess.py:92} INFO - 25/09/01 03:42:39 INFO Executor: Adding file:/tmp/spark-a45daf75-2ff1-4924-895e-308278d69463/userFiles-dce3bb8d-f630-4cfb-996f-fe80458000b4/org.spark-project.spark_unused-1.0.0.jar to class loader
[2025-09-01 03:42:39,183] {subprocess.py:92} INFO - 25/09/01 03:42:39 INFO Executor: Fetching spark://e66737cfc193:43045/jars/com.google.code.findbugs_jsr305-3.0.0.jar with timestamp 1756698158176
[2025-09-01 03:42:39,184] {subprocess.py:92} INFO - 25/09/01 03:42:39 INFO Utils: Fetching spark://e66737cfc193:43045/jars/com.google.code.findbugs_jsr305-3.0.0.jar to /tmp/spark-a45daf75-2ff1-4924-895e-308278d69463/userFiles-dce3bb8d-f630-4cfb-996f-fe80458000b4/fetchFileTemp2387439238516086238.tmp
[2025-09-01 03:42:39,185] {subprocess.py:92} INFO - 25/09/01 03:42:39 INFO Utils: /tmp/spark-a45daf75-2ff1-4924-895e-308278d69463/userFiles-dce3bb8d-f630-4cfb-996f-fe80458000b4/fetchFileTemp2387439238516086238.tmp has been previously copied to /tmp/spark-a45daf75-2ff1-4924-895e-308278d69463/userFiles-dce3bb8d-f630-4cfb-996f-fe80458000b4/com.google.code.findbugs_jsr305-3.0.0.jar
[2025-09-01 03:42:39,190] {subprocess.py:92} INFO - 25/09/01 03:42:39 INFO Executor: Adding file:/tmp/spark-a45daf75-2ff1-4924-895e-308278d69463/userFiles-dce3bb8d-f630-4cfb-996f-fe80458000b4/com.google.code.findbugs_jsr305-3.0.0.jar to class loader
[2025-09-01 03:42:39,190] {subprocess.py:92} INFO - 25/09/01 03:42:39 INFO Executor: Fetching spark://e66737cfc193:43045/jars/org.apache.hadoop_hadoop-client-runtime-3.3.2.jar with timestamp 1756698158176
[2025-09-01 03:42:39,191] {subprocess.py:92} INFO - 25/09/01 03:42:39 INFO Utils: Fetching spark://e66737cfc193:43045/jars/org.apache.hadoop_hadoop-client-runtime-3.3.2.jar to /tmp/spark-a45daf75-2ff1-4924-895e-308278d69463/userFiles-dce3bb8d-f630-4cfb-996f-fe80458000b4/fetchFileTemp488609710101176655.tmp
[2025-09-01 03:42:39,270] {subprocess.py:92} INFO - 25/09/01 03:42:39 INFO Utils: /tmp/spark-a45daf75-2ff1-4924-895e-308278d69463/userFiles-dce3bb8d-f630-4cfb-996f-fe80458000b4/fetchFileTemp488609710101176655.tmp has been previously copied to /tmp/spark-a45daf75-2ff1-4924-895e-308278d69463/userFiles-dce3bb8d-f630-4cfb-996f-fe80458000b4/org.apache.hadoop_hadoop-client-runtime-3.3.2.jar
[2025-09-01 03:42:39,313] {subprocess.py:92} INFO - 25/09/01 03:42:39 INFO Executor: Adding file:/tmp/spark-a45daf75-2ff1-4924-895e-308278d69463/userFiles-dce3bb8d-f630-4cfb-996f-fe80458000b4/org.apache.hadoop_hadoop-client-runtime-3.3.2.jar to class loader
[2025-09-01 03:42:39,313] {subprocess.py:92} INFO - 25/09/01 03:42:39 INFO Executor: Fetching spark://e66737cfc193:43045/jars/org.apache.hadoop_hadoop-client-api-3.3.2.jar with timestamp 1756698158176
[2025-09-01 03:42:39,314] {subprocess.py:92} INFO - 25/09/01 03:42:39 INFO Utils: Fetching spark://e66737cfc193:43045/jars/org.apache.hadoop_hadoop-client-api-3.3.2.jar to /tmp/spark-a45daf75-2ff1-4924-895e-308278d69463/userFiles-dce3bb8d-f630-4cfb-996f-fe80458000b4/fetchFileTemp12990414891741562347.tmp
[2025-09-01 03:42:39,392] {subprocess.py:92} INFO - 25/09/01 03:42:39 INFO Utils: /tmp/spark-a45daf75-2ff1-4924-895e-308278d69463/userFiles-dce3bb8d-f630-4cfb-996f-fe80458000b4/fetchFileTemp12990414891741562347.tmp has been previously copied to /tmp/spark-a45daf75-2ff1-4924-895e-308278d69463/userFiles-dce3bb8d-f630-4cfb-996f-fe80458000b4/org.apache.hadoop_hadoop-client-api-3.3.2.jar
[2025-09-01 03:42:39,398] {subprocess.py:92} INFO - 25/09/01 03:42:39 INFO Executor: Adding file:/tmp/spark-a45daf75-2ff1-4924-895e-308278d69463/userFiles-dce3bb8d-f630-4cfb-996f-fe80458000b4/org.apache.hadoop_hadoop-client-api-3.3.2.jar to class loader
[2025-09-01 03:42:39,404] {subprocess.py:92} INFO - 25/09/01 03:42:39 INFO Utils: Successfully started service 'org.apache.spark.network.netty.NettyBlockTransferService' on port 32925.
[2025-09-01 03:42:39,404] {subprocess.py:92} INFO - 25/09/01 03:42:39 INFO NettyBlockTransferService: Server created on e66737cfc193:32925
[2025-09-01 03:42:39,406] {subprocess.py:92} INFO - 25/09/01 03:42:39 INFO BlockManager: Using org.apache.spark.storage.RandomBlockReplicationPolicy for block replication policy
[2025-09-01 03:42:39,410] {subprocess.py:92} INFO - 25/09/01 03:42:39 INFO BlockManagerMaster: Registering BlockManager BlockManagerId(driver, e66737cfc193, 32925, None)
[2025-09-01 03:42:39,414] {subprocess.py:92} INFO - 25/09/01 03:42:39 INFO BlockManagerMasterEndpoint: Registering block manager e66737cfc193:32925 with 434.4 MiB RAM, BlockManagerId(driver, e66737cfc193, 32925, None)
[2025-09-01 03:42:39,417] {subprocess.py:92} INFO - 25/09/01 03:42:39 INFO BlockManagerMaster: Registered BlockManager BlockManagerId(driver, e66737cfc193, 32925, None)
[2025-09-01 03:42:39,418] {subprocess.py:92} INFO - 25/09/01 03:42:39 INFO BlockManager: Initialized BlockManager: BlockManagerId(driver, e66737cfc193, 32925, None)
[2025-09-01 03:42:39,673] {subprocess.py:92} INFO - Connexion à Kafka...
[2025-09-01 03:42:40,986] {subprocess.py:92} INFO - Connexion Kafka réussie (kafka:9092)
[2025-09-01 03:42:40,987] {subprocess.py:92} INFO - Transformation des données JSON...
[2025-09-01 03:42:41,199] {subprocess.py:92} INFO - Démarrage du streaming vers HDFS...
[2025-09-01 03:42:41,698] {subprocess.py:92} INFO - Streaming actif - Données météo sauvegardées dans HDFS:/data/weather
[2025-09-01 04:45:36,572] {base_job.py:229} ERROR - LocalTaskJob heartbeat got an exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 3141, in _wrap_pool_connect
    return fn()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 301, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 755, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 419, in checkout
    rec = pool._do_get()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/impl.py", line 259, in _do_get
    return self._create_connection()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 247, in _create_connection
    return _ConnectionRecord(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 362, in __init__
    self.__connect(first_connect_check=True)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 605, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 72, in __exit__
    with_traceback=exc_tb,
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 599, in __connect
    connection = pool._invoke_creator(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/create.py", line 578, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 583, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.7/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: could not translate host name "postgres" to address: Temporary failure in name resolution


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/jobs/base_job.py", line 219, in heartbeat
    session.merge(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 2877, in merge
    _resolve_conflict_map=_resolve_conflict_map,
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 2950, in _merge
    merged = self.get(mapper.class_, key[1], identity_token=key[2])
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 2702, in get
    identity_token=identity_token,
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 2800, in _get_impl
    load_options=load_options,
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/loading.py", line 535, in load_on_pk_identity
    bind_arguments=bind_arguments,
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 1669, in execute
    conn = self._connection_for_bind(bind, close_with_result=True)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 1520, in _connection_for_bind
    engine, execution_options
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 747, in _connection_for_bind
    conn = bind.connect()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 3095, in connect
    return self._connection_cls(self, close_with_result=close_with_result)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 91, in __init__
    else engine.raw_connection()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 3174, in raw_connection
    return self._wrap_pool_connect(self.pool.connect, _connection)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 3145, in _wrap_pool_connect
    e, dialect, self
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 2004, in _handle_dbapi_exception_noconnection
    sqlalchemy_exception, with_traceback=exc_info[2], from_=e
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 3141, in _wrap_pool_connect
    return fn()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 301, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 755, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 419, in checkout
    rec = pool._do_get()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/impl.py", line 259, in _do_get
    return self._create_connection()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 247, in _create_connection
    return _ConnectionRecord(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 362, in __init__
    self.__connect(first_connect_check=True)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 605, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 72, in __exit__
    with_traceback=exc_tb,
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 599, in __connect
    connection = pool._invoke_creator(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/create.py", line 578, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 583, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.7/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) could not translate host name "postgres" to address: Temporary failure in name resolution

(Background on this error at: http://sqlalche.me/e/14/e3q8)
[2025-09-01 04:46:07,264] {base_job.py:229} ERROR - LocalTaskJob heartbeat got an exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 3141, in _wrap_pool_connect
    return fn()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 301, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 755, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 419, in checkout
    rec = pool._do_get()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/impl.py", line 259, in _do_get
    return self._create_connection()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 247, in _create_connection
    return _ConnectionRecord(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 362, in __init__
    self.__connect(first_connect_check=True)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 605, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 72, in __exit__
    with_traceback=exc_tb,
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 599, in __connect
    connection = pool._invoke_creator(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/create.py", line 578, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 583, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.7/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: could not translate host name "postgres" to address: Temporary failure in name resolution


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/jobs/base_job.py", line 201, in heartbeat
    session.merge(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 2877, in merge
    _resolve_conflict_map=_resolve_conflict_map,
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 2950, in _merge
    merged = self.get(mapper.class_, key[1], identity_token=key[2])
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 2702, in get
    identity_token=identity_token,
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 2800, in _get_impl
    load_options=load_options,
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/loading.py", line 535, in load_on_pk_identity
    bind_arguments=bind_arguments,
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 1669, in execute
    conn = self._connection_for_bind(bind, close_with_result=True)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 1520, in _connection_for_bind
    engine, execution_options
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 747, in _connection_for_bind
    conn = bind.connect()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 3095, in connect
    return self._connection_cls(self, close_with_result=close_with_result)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 91, in __init__
    else engine.raw_connection()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 3174, in raw_connection
    return self._wrap_pool_connect(self.pool.connect, _connection)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 3145, in _wrap_pool_connect
    e, dialect, self
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 2004, in _handle_dbapi_exception_noconnection
    sqlalchemy_exception, with_traceback=exc_info[2], from_=e
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 3141, in _wrap_pool_connect
    return fn()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 301, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 755, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 419, in checkout
    rec = pool._do_get()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/impl.py", line 259, in _do_get
    return self._create_connection()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 247, in _create_connection
    return _ConnectionRecord(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 362, in __init__
    self.__connect(first_connect_check=True)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 605, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 72, in __exit__
    with_traceback=exc_tb,
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 599, in __connect
    connection = pool._invoke_creator(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/create.py", line 578, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 583, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.7/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) could not translate host name "postgres" to address: Temporary failure in name resolution

(Background on this error at: http://sqlalche.me/e/14/e3q8)
[2025-09-01 04:46:34,243] {subprocess.py:92} INFO - 25/09/01 04:46:10 WARN NetworkClient: [Consumer clientId=consumer-spark-kafka-source-e28a3e09-d3a9-475d-aecc-a44e90fb2e5c-629405726-driver-0-1, groupId=spark-kafka-source-e28a3e09-d3a9-475d-aecc-a44e90fb2e5c-629405726-driver-0] Error connecting to node kafka:9092 (id: 2147483646 rack: null)
[2025-09-01 04:46:35,160] {subprocess.py:92} INFO - java.net.UnknownHostException: kafka: Temporary failure in name resolution
[2025-09-01 04:46:35,166] {subprocess.py:92} INFO - 	at java.base/java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method)
[2025-09-01 04:46:35,166] {subprocess.py:92} INFO - 	at java.base/java.net.InetAddress$PlatformNameService.lookupAllHostAddr(InetAddress.java:930)
[2025-09-01 04:46:35,166] {subprocess.py:92} INFO - 	at java.base/java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1543)
[2025-09-01 04:46:35,166] {subprocess.py:92} INFO - 	at java.base/java.net.InetAddress$NameServiceAddresses.get(InetAddress.java:848)
[2025-09-01 04:46:35,166] {subprocess.py:92} INFO - 	at java.base/java.net.InetAddress.getAllByName0(InetAddress.java:1533)
[2025-09-01 04:46:35,167] {subprocess.py:92} INFO - 	at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1386)
[2025-09-01 04:46:35,167] {subprocess.py:92} INFO - 	at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1307)
[2025-09-01 04:46:35,167] {subprocess.py:92} INFO - 	at org.apache.kafka.clients.DefaultHostResolver.resolve(DefaultHostResolver.java:27)
[2025-09-01 04:46:35,167] {subprocess.py:92} INFO - 	at org.apache.kafka.clients.ClientUtils.resolve(ClientUtils.java:111)
[2025-09-01 04:46:35,167] {subprocess.py:92} INFO - 	at org.apache.kafka.clients.ClusterConnectionStates$NodeConnectionState.currentAddress(ClusterConnectionStates.java:513)
[2025-09-01 04:46:35,167] {subprocess.py:92} INFO - 	at org.apache.kafka.clients.ClusterConnectionStates$NodeConnectionState.access$200(ClusterConnectionStates.java:467)
[2025-09-01 04:46:35,167] {subprocess.py:92} INFO - 	at org.apache.kafka.clients.ClusterConnectionStates.currentAddress(ClusterConnectionStates.java:172)
[2025-09-01 04:46:35,167] {subprocess.py:92} INFO - 	at org.apache.kafka.clients.NetworkClient.initiateConnect(NetworkClient.java:985)
[2025-09-01 04:46:35,167] {subprocess.py:92} INFO - 	at org.apache.kafka.clients.NetworkClient.ready(NetworkClient.java:311)
[2025-09-01 04:46:35,167] {subprocess.py:92} INFO - 	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.tryConnect(ConsumerNetworkClient.java:575)
[2025-09-01 04:46:35,167] {subprocess.py:92} INFO - 	at org.apache.kafka.clients.consumer.internals.AbstractCoordinator$FindCoordinatorResponseHandler.onSuccess(AbstractCoordinator.java:851)
[2025-09-01 04:46:35,167] {subprocess.py:92} INFO - 	at org.apache.kafka.clients.consumer.internals.AbstractCoordinator$FindCoordinatorResponseHandler.onSuccess(AbstractCoordinator.java:832)
[2025-09-01 04:46:35,167] {subprocess.py:92} INFO - 	at org.apache.kafka.clients.consumer.internals.RequestFuture$1.onSuccess(RequestFuture.java:206)
[2025-09-01 04:46:35,167] {subprocess.py:92} INFO - 	at org.apache.kafka.clients.consumer.internals.RequestFuture.fireSuccess(RequestFuture.java:169)
[2025-09-01 04:46:35,167] {subprocess.py:92} INFO - 	at org.apache.kafka.clients.consumer.internals.RequestFuture.complete(RequestFuture.java:129)
[2025-09-01 04:46:35,167] {subprocess.py:92} INFO - 	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient$RequestFutureCompletionHandler.fireCompletion(ConsumerNetworkClient.java:602)
[2025-09-01 04:46:35,786] {subprocess.py:92} INFO - 	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.firePendingCompletedRequests(ConsumerNetworkClient.java:412)
[2025-09-01 04:46:36,451] {subprocess.py:92} INFO - 	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:297)
[2025-09-01 04:46:36,628] {subprocess.py:92} INFO - 	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.pollNoWakeup(ConsumerNetworkClient.java:306)
[2025-09-01 04:46:37,999] {subprocess.py:92} INFO - 	at org.apache.kafka.clients.consumer.internals.AbstractCoordinator$HeartbeatThread.run(AbstractCoordinator.java:1372)
[2025-09-01 04:48:56,569] {base_job.py:229} ERROR - LocalTaskJob heartbeat got an exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 3141, in _wrap_pool_connect
    return fn()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 301, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 755, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 419, in checkout
    rec = pool._do_get()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/impl.py", line 259, in _do_get
    return self._create_connection()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 247, in _create_connection
    return _ConnectionRecord(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 362, in __init__
    self.__connect(first_connect_check=True)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 605, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 72, in __exit__
    with_traceback=exc_tb,
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 599, in __connect
    connection = pool._invoke_creator(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/create.py", line 578, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 583, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.7/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: could not translate host name "postgres" to address: Temporary failure in name resolution


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/jobs/base_job.py", line 219, in heartbeat
    session.merge(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 2877, in merge
    _resolve_conflict_map=_resolve_conflict_map,
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 2950, in _merge
    merged = self.get(mapper.class_, key[1], identity_token=key[2])
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 2702, in get
    identity_token=identity_token,
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 2800, in _get_impl
    load_options=load_options,
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/loading.py", line 535, in load_on_pk_identity
    bind_arguments=bind_arguments,
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 1669, in execute
    conn = self._connection_for_bind(bind, close_with_result=True)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 1520, in _connection_for_bind
    engine, execution_options
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 747, in _connection_for_bind
    conn = bind.connect()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 3095, in connect
    return self._connection_cls(self, close_with_result=close_with_result)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 91, in __init__
    else engine.raw_connection()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 3174, in raw_connection
    return self._wrap_pool_connect(self.pool.connect, _connection)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 3145, in _wrap_pool_connect
    e, dialect, self
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 2004, in _handle_dbapi_exception_noconnection
    sqlalchemy_exception, with_traceback=exc_info[2], from_=e
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 3141, in _wrap_pool_connect
    return fn()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 301, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 755, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 419, in checkout
    rec = pool._do_get()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/impl.py", line 259, in _do_get
    return self._create_connection()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 247, in _create_connection
    return _ConnectionRecord(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 362, in __init__
    self.__connect(first_connect_check=True)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 605, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 72, in __exit__
    with_traceback=exc_tb,
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 599, in __connect
    connection = pool._invoke_creator(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/create.py", line 578, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 583, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.7/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) could not translate host name "postgres" to address: Temporary failure in name resolution

(Background on this error at: http://sqlalche.me/e/14/e3q8)
[2025-09-01 04:49:01,290] {local_task_job.py:144} ERROR - Heartbeat time limit exceeded!
[2025-09-01 04:50:08,875] {process_utils.py:129} INFO - Sending Signals.SIGTERM to group 6630. PIDs of all processes in the group: [6631, 6681, 6630]
[2025-09-01 04:50:21,901] {process_utils.py:80} INFO - Sending the signal Signals.SIGTERM to group 6630
[2025-09-01 04:50:45,450] {taskinstance.py:1541} ERROR - Received SIGTERM. Terminating subprocesses.
[2025-09-01 04:50:45,460] {subprocess.py:103} INFO - Sending SIGTERM signal to process group
[2025-09-01 04:50:45,483] {process_utils.py:75} INFO - Process psutil.Process(pid=6681, status='terminated', started='03:42:36') (6681) terminated with exit code None
[2025-09-01 04:50:45,959] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 189, in execute
    cwd=self.cwd,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/hooks/subprocess.py", line 90, in run_command
    for raw_line in iter(self.sub_process.stdout.readline, b''):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1543, in signal_handler
    raise AirflowException("Task received SIGTERM signal")
airflow.exceptions.AirflowException: Task received SIGTERM signal
[2025-09-01 04:50:46,035] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=send_weather_to_kafka, task_id=stream_hdfs, execution_date=20250901T030900, start_date=20250901T034235, end_date=20250901T045046
[2025-09-01 04:50:46,083] {standard_task_runner.py:97} ERROR - Failed to execute job 447 for task stream_hdfs (Task received SIGTERM signal; 6630)
[2025-09-01 04:50:46,220] {process_utils.py:75} INFO - Process psutil.Process(pid=6630, status='terminated', exitcode=1, started='03:42:34') (6630) terminated with exit code 1
[2025-09-01 04:50:46,745] {process_utils.py:75} INFO - Process psutil.Process(pid=6631, status='terminated', started='03:42:34') (6631) terminated with exit code None
