[2025-09-01 02:42:34,858] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: send_weather_to_kafka.stream_hdfs scheduled__2025-09-01T02:09:00.786183+00:00 [queued]>
[2025-09-01 02:42:34,863] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: send_weather_to_kafka.stream_hdfs scheduled__2025-09-01T02:09:00.786183+00:00 [queued]>
[2025-09-01 02:42:34,863] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2025-09-01 02:42:34,864] {taskinstance.py:1357} INFO - Starting attempt 1 of 2
[2025-09-01 02:42:34,864] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2025-09-01 02:42:34,873] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): stream_hdfs> on 2025-09-01 02:09:00.786183+00:00
[2025-09-01 02:42:34,876] {standard_task_runner.py:52} INFO - Started process 5578 to run task
[2025-09-01 02:42:34,879] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'send_weather_to_kafka', 'stream_hdfs', 'scheduled__2025-09-01T02:09:00.786183+00:00', '--job-id', '439', '--raw', '--subdir', 'DAGS_FOLDER/dag_meteo.py', '--cfg-path', '/tmp/tmpza9nypga', '--error-file', '/tmp/tmpxoftm5lf']
[2025-09-01 02:42:34,880] {standard_task_runner.py:80} INFO - Job 439: Subtask stream_hdfs
[2025-09-01 02:42:34,896] {logging_mixin.py:115} WARNING - /home/***/.local/lib/python3.7/site-packages/***/configuration.py:470 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-09-01 02:42:34,930] {task_command.py:369} INFO - Running <TaskInstance: send_weather_to_kafka.stream_hdfs scheduled__2025-09-01T02:09:00.786183+00:00 [running]> on host e66737cfc193
[2025-09-01 02:42:35,016] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=send_weather_to_kafka
AIRFLOW_CTX_TASK_ID=stream_hdfs
AIRFLOW_CTX_EXECUTION_DATE=2025-09-01T02:09:00.786183+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2025-09-01T02:09:00.786183+00:00
[2025-09-01 02:42:35,017] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2025-09-01 02:42:35,017] {subprocess.py:74} INFO - Running command: ['bash', '-c', '\n/home/***/.local/bin/spark-submit   --master local[*]   --conf spark.hadoop.fs.defaultFS=hdfs://namenode:9000   --conf spark.hadoop.dfs.client.use.datanode.hostname=true   --conf spark.sql.adaptive.enabled=false   --packages org.apache.spark:spark-sql-kafka-0-10_2.12:3.3.1   /opt/***/scripts/pyspark/streaming.py']
[2025-09-01 02:42:35,030] {subprocess.py:85} INFO - Output:
[2025-09-01 02:42:35,042] {subprocess.py:92} INFO - /opt/spark-3.3.1-bin-hadoop3/bin/load-spark-env.sh: line 68: ps: command not found
[2025-09-01 02:42:35,956] {subprocess.py:92} INFO - :: loading settings :: url = jar:file:/opt/spark-3.3.1-bin-hadoop3/jars/ivy-2.5.0.jar!/org/apache/ivy/core/settings/ivysettings.xml
[2025-09-01 02:42:36,030] {subprocess.py:92} INFO - Ivy Default Cache set to: /home/***/.ivy2/cache
[2025-09-01 02:42:36,030] {subprocess.py:92} INFO - The jars for the packages stored in: /home/***/.ivy2/jars
[2025-09-01 02:42:36,036] {subprocess.py:92} INFO - org.apache.spark#spark-sql-kafka-0-10_2.12 added as a dependency
[2025-09-01 02:42:36,037] {subprocess.py:92} INFO - :: resolving dependencies :: org.apache.spark#spark-submit-parent-d1cbbb33-83a0-448c-8ab2-961f0ac10d5e;1.0
[2025-09-01 02:42:36,037] {subprocess.py:92} INFO - 	confs: [default]
[2025-09-01 02:42:36,144] {subprocess.py:92} INFO - 	found org.apache.spark#spark-sql-kafka-0-10_2.12;3.3.1 in central
[2025-09-01 02:42:36,213] {subprocess.py:92} INFO - 	found org.apache.spark#spark-token-provider-kafka-0-10_2.12;3.3.1 in central
[2025-09-01 02:42:36,247] {subprocess.py:92} INFO - 	found org.apache.kafka#kafka-clients;2.8.1 in central
[2025-09-01 02:42:36,278] {subprocess.py:92} INFO - 	found org.lz4#lz4-java;1.8.0 in central
[2025-09-01 02:42:36,300] {subprocess.py:92} INFO - 	found org.xerial.snappy#snappy-java;1.1.8.4 in central
[2025-09-01 02:42:36,318] {subprocess.py:92} INFO - 	found org.slf4j#slf4j-api;1.7.32 in central
[2025-09-01 02:42:36,343] {subprocess.py:92} INFO - 	found org.apache.hadoop#hadoop-client-runtime;3.3.2 in central
[2025-09-01 02:42:36,357] {subprocess.py:92} INFO - 	found org.spark-project.spark#unused;1.0.0 in central
[2025-09-01 02:42:36,383] {subprocess.py:92} INFO - 	found org.apache.hadoop#hadoop-client-api;3.3.2 in central
[2025-09-01 02:42:36,405] {subprocess.py:92} INFO - 	found commons-logging#commons-logging;1.1.3 in central
[2025-09-01 02:42:36,420] {subprocess.py:92} INFO - 	found com.google.code.findbugs#jsr305;3.0.0 in central
[2025-09-01 02:42:36,434] {subprocess.py:92} INFO - 	found org.apache.commons#commons-pool2;2.11.1 in central
[2025-09-01 02:42:36,462] {subprocess.py:92} INFO - :: resolution report :: resolve 412ms :: artifacts dl 14ms
[2025-09-01 02:42:36,462] {subprocess.py:92} INFO - 	:: modules in use:
[2025-09-01 02:42:36,462] {subprocess.py:92} INFO - 	com.google.code.findbugs#jsr305;3.0.0 from central in [default]
[2025-09-01 02:42:36,462] {subprocess.py:92} INFO - 	commons-logging#commons-logging;1.1.3 from central in [default]
[2025-09-01 02:42:36,462] {subprocess.py:92} INFO - 	org.apache.commons#commons-pool2;2.11.1 from central in [default]
[2025-09-01 02:42:36,462] {subprocess.py:92} INFO - 	org.apache.hadoop#hadoop-client-api;3.3.2 from central in [default]
[2025-09-01 02:42:36,462] {subprocess.py:92} INFO - 	org.apache.hadoop#hadoop-client-runtime;3.3.2 from central in [default]
[2025-09-01 02:42:36,463] {subprocess.py:92} INFO - 	org.apache.kafka#kafka-clients;2.8.1 from central in [default]
[2025-09-01 02:42:36,463] {subprocess.py:92} INFO - 	org.apache.spark#spark-sql-kafka-0-10_2.12;3.3.1 from central in [default]
[2025-09-01 02:42:36,463] {subprocess.py:92} INFO - 	org.apache.spark#spark-token-provider-kafka-0-10_2.12;3.3.1 from central in [default]
[2025-09-01 02:42:36,463] {subprocess.py:92} INFO - 	org.lz4#lz4-java;1.8.0 from central in [default]
[2025-09-01 02:42:36,463] {subprocess.py:92} INFO - 	org.slf4j#slf4j-api;1.7.32 from central in [default]
[2025-09-01 02:42:36,463] {subprocess.py:92} INFO - 	org.spark-project.spark#unused;1.0.0 from central in [default]
[2025-09-01 02:42:36,463] {subprocess.py:92} INFO - 	org.xerial.snappy#snappy-java;1.1.8.4 from central in [default]
[2025-09-01 02:42:36,463] {subprocess.py:92} INFO - 	---------------------------------------------------------------------
[2025-09-01 02:42:36,463] {subprocess.py:92} INFO - 	|                  |            modules            ||   artifacts   |
[2025-09-01 02:42:36,463] {subprocess.py:92} INFO - 	|       conf       | number| search|dwnlded|evicted|| number|dwnlded|
[2025-09-01 02:42:36,463] {subprocess.py:92} INFO - 	---------------------------------------------------------------------
[2025-09-01 02:42:36,463] {subprocess.py:92} INFO - 	|      default     |   12  |   0   |   0   |   0   ||   12  |   0   |
[2025-09-01 02:42:36,463] {subprocess.py:92} INFO - 	---------------------------------------------------------------------
[2025-09-01 02:42:36,471] {subprocess.py:92} INFO - :: retrieving :: org.apache.spark#spark-submit-parent-d1cbbb33-83a0-448c-8ab2-961f0ac10d5e
[2025-09-01 02:42:36,471] {subprocess.py:92} INFO - 	confs: [default]
[2025-09-01 02:42:36,480] {subprocess.py:92} INFO - 	0 artifacts copied, 12 already retrieved (0kB/10ms)
[2025-09-01 02:42:36,677] {subprocess.py:92} INFO - 25/09/01 02:42:36 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
[2025-09-01 02:42:37,405] {subprocess.py:92} INFO - 25/09/01 02:42:37 INFO SparkContext: Running Spark version 3.3.1
[2025-09-01 02:42:37,417] {subprocess.py:92} INFO - 25/09/01 02:42:37 INFO ResourceUtils: ==============================================================
[2025-09-01 02:42:37,417] {subprocess.py:92} INFO - 25/09/01 02:42:37 INFO ResourceUtils: No custom resources configured for spark.driver.
[2025-09-01 02:42:37,417] {subprocess.py:92} INFO - 25/09/01 02:42:37 INFO ResourceUtils: ==============================================================
[2025-09-01 02:42:37,417] {subprocess.py:92} INFO - 25/09/01 02:42:37 INFO SparkContext: Submitted application: KafkaToHDFSWeather
[2025-09-01 02:42:37,430] {subprocess.py:92} INFO - 25/09/01 02:42:37 INFO ResourceProfile: Default ResourceProfile created, executor resources: Map(cores -> name: cores, amount: 1, script: , vendor: , memory -> name: memory, amount: 1024, script: , vendor: , offHeap -> name: offHeap, amount: 0, script: , vendor: ), task resources: Map(cpus -> name: cpus, amount: 1.0)
[2025-09-01 02:42:37,437] {subprocess.py:92} INFO - 25/09/01 02:42:37 INFO ResourceProfile: Limiting resource is cpu
[2025-09-01 02:42:37,437] {subprocess.py:92} INFO - 25/09/01 02:42:37 INFO ResourceProfileManager: Added ResourceProfile id: 0
[2025-09-01 02:42:37,471] {subprocess.py:92} INFO - 25/09/01 02:42:37 INFO SecurityManager: Changing view acls to: ***
[2025-09-01 02:42:37,472] {subprocess.py:92} INFO - 25/09/01 02:42:37 INFO SecurityManager: Changing modify acls to: ***
[2025-09-01 02:42:37,472] {subprocess.py:92} INFO - 25/09/01 02:42:37 INFO SecurityManager: Changing view acls groups to:
[2025-09-01 02:42:37,473] {subprocess.py:92} INFO - 25/09/01 02:42:37 INFO SecurityManager: Changing modify acls groups to:
[2025-09-01 02:42:37,473] {subprocess.py:92} INFO - 25/09/01 02:42:37 INFO SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users  with view permissions: Set(***); groups with view permissions: Set(); users  with modify permissions: Set(***); groups with modify permissions: Set()
[2025-09-01 02:42:37,638] {subprocess.py:92} INFO - 25/09/01 02:42:37 INFO Utils: Successfully started service 'sparkDriver' on port 36835.
[2025-09-01 02:42:37,655] {subprocess.py:92} INFO - 25/09/01 02:42:37 INFO SparkEnv: Registering MapOutputTracker
[2025-09-01 02:42:37,674] {subprocess.py:92} INFO - 25/09/01 02:42:37 INFO SparkEnv: Registering BlockManagerMaster
[2025-09-01 02:42:37,684] {subprocess.py:92} INFO - 25/09/01 02:42:37 INFO BlockManagerMasterEndpoint: Using org.apache.spark.storage.DefaultTopologyMapper for getting topology information
[2025-09-01 02:42:37,684] {subprocess.py:92} INFO - 25/09/01 02:42:37 INFO BlockManagerMasterEndpoint: BlockManagerMasterEndpoint up
[2025-09-01 02:42:37,687] {subprocess.py:92} INFO - 25/09/01 02:42:37 INFO SparkEnv: Registering BlockManagerMasterHeartbeat
[2025-09-01 02:42:37,699] {subprocess.py:92} INFO - 25/09/01 02:42:37 INFO DiskBlockManager: Created local directory at /tmp/blockmgr-e77436c8-154b-4e8e-a844-bdc2676ddb56
[2025-09-01 02:42:37,709] {subprocess.py:92} INFO - 25/09/01 02:42:37 INFO MemoryStore: MemoryStore started with capacity 434.4 MiB
[2025-09-01 02:42:37,718] {subprocess.py:92} INFO - 25/09/01 02:42:37 INFO SparkEnv: Registering OutputCommitCoordinator
[2025-09-01 02:42:37,827] {subprocess.py:92} INFO - 25/09/01 02:42:37 WARN Utils: Service 'SparkUI' could not bind on port 4040. Attempting port 4041.
[2025-09-01 02:42:37,835] {subprocess.py:92} INFO - 25/09/01 02:42:37 INFO Utils: Successfully started service 'SparkUI' on port 4041.
[2025-09-01 02:42:37,857] {subprocess.py:92} INFO - 25/09/01 02:42:37 INFO SparkContext: Added JAR file:///home/***/.ivy2/jars/org.apache.spark_spark-sql-kafka-0-10_2.12-3.3.1.jar at spark://e66737cfc193:36835/jars/org.apache.spark_spark-sql-kafka-0-10_2.12-3.3.1.jar with timestamp 1756694557400
[2025-09-01 02:42:37,857] {subprocess.py:92} INFO - 25/09/01 02:42:37 INFO SparkContext: Added JAR file:///home/***/.ivy2/jars/org.apache.spark_spark-token-provider-kafka-0-10_2.12-3.3.1.jar at spark://e66737cfc193:36835/jars/org.apache.spark_spark-token-provider-kafka-0-10_2.12-3.3.1.jar with timestamp 1756694557400
[2025-09-01 02:42:37,857] {subprocess.py:92} INFO - 25/09/01 02:42:37 INFO SparkContext: Added JAR file:///home/***/.ivy2/jars/org.apache.kafka_kafka-clients-2.8.1.jar at spark://e66737cfc193:36835/jars/org.apache.kafka_kafka-clients-2.8.1.jar with timestamp 1756694557400
[2025-09-01 02:42:37,857] {subprocess.py:92} INFO - 25/09/01 02:42:37 INFO SparkContext: Added JAR file:///home/***/.ivy2/jars/com.google.code.findbugs_jsr305-3.0.0.jar at spark://e66737cfc193:36835/jars/com.google.code.findbugs_jsr305-3.0.0.jar with timestamp 1756694557400
[2025-09-01 02:42:37,857] {subprocess.py:92} INFO - 25/09/01 02:42:37 INFO SparkContext: Added JAR file:///home/***/.ivy2/jars/org.apache.commons_commons-pool2-2.11.1.jar at spark://e66737cfc193:36835/jars/org.apache.commons_commons-pool2-2.11.1.jar with timestamp 1756694557400
[2025-09-01 02:42:37,857] {subprocess.py:92} INFO - 25/09/01 02:42:37 INFO SparkContext: Added JAR file:///home/***/.ivy2/jars/org.spark-project.spark_unused-1.0.0.jar at spark://e66737cfc193:36835/jars/org.spark-project.spark_unused-1.0.0.jar with timestamp 1756694557400
[2025-09-01 02:42:37,857] {subprocess.py:92} INFO - 25/09/01 02:42:37 INFO SparkContext: Added JAR file:///home/***/.ivy2/jars/org.apache.hadoop_hadoop-client-runtime-3.3.2.jar at spark://e66737cfc193:36835/jars/org.apache.hadoop_hadoop-client-runtime-3.3.2.jar with timestamp 1756694557400
[2025-09-01 02:42:37,857] {subprocess.py:92} INFO - 25/09/01 02:42:37 INFO SparkContext: Added JAR file:///home/***/.ivy2/jars/org.lz4_lz4-java-1.8.0.jar at spark://e66737cfc193:36835/jars/org.lz4_lz4-java-1.8.0.jar with timestamp 1756694557400
[2025-09-01 02:42:37,858] {subprocess.py:92} INFO - 25/09/01 02:42:37 INFO SparkContext: Added JAR file:///home/***/.ivy2/jars/org.xerial.snappy_snappy-java-1.1.8.4.jar at spark://e66737cfc193:36835/jars/org.xerial.snappy_snappy-java-1.1.8.4.jar with timestamp 1756694557400
[2025-09-01 02:42:37,858] {subprocess.py:92} INFO - 25/09/01 02:42:37 INFO SparkContext: Added JAR file:///home/***/.ivy2/jars/org.slf4j_slf4j-api-1.7.32.jar at spark://e66737cfc193:36835/jars/org.slf4j_slf4j-api-1.7.32.jar with timestamp 1756694557400
[2025-09-01 02:42:37,858] {subprocess.py:92} INFO - 25/09/01 02:42:37 INFO SparkContext: Added JAR file:///home/***/.ivy2/jars/org.apache.hadoop_hadoop-client-api-3.3.2.jar at spark://e66737cfc193:36835/jars/org.apache.hadoop_hadoop-client-api-3.3.2.jar with timestamp 1756694557400
[2025-09-01 02:42:37,858] {subprocess.py:92} INFO - 25/09/01 02:42:37 INFO SparkContext: Added JAR file:///home/***/.ivy2/jars/commons-logging_commons-logging-1.1.3.jar at spark://e66737cfc193:36835/jars/commons-logging_commons-logging-1.1.3.jar with timestamp 1756694557400
[2025-09-01 02:42:37,859] {subprocess.py:92} INFO - 25/09/01 02:42:37 INFO SparkContext: Added file file:///home/***/.ivy2/jars/org.apache.spark_spark-sql-kafka-0-10_2.12-3.3.1.jar at file:///home/***/.ivy2/jars/org.apache.spark_spark-sql-kafka-0-10_2.12-3.3.1.jar with timestamp 1756694557400
[2025-09-01 02:42:37,860] {subprocess.py:92} INFO - 25/09/01 02:42:37 INFO Utils: Copying /home/***/.ivy2/jars/org.apache.spark_spark-sql-kafka-0-10_2.12-3.3.1.jar to /tmp/spark-e9fcb46c-6f35-42bd-86d3-bf8c55550d38/userFiles-cc9c2dc1-b3e3-438e-8187-a0deca4da0e6/org.apache.spark_spark-sql-kafka-0-10_2.12-3.3.1.jar
[2025-09-01 02:42:37,867] {subprocess.py:92} INFO - 25/09/01 02:42:37 INFO SparkContext: Added file file:///home/***/.ivy2/jars/org.apache.spark_spark-token-provider-kafka-0-10_2.12-3.3.1.jar at file:///home/***/.ivy2/jars/org.apache.spark_spark-token-provider-kafka-0-10_2.12-3.3.1.jar with timestamp 1756694557400
[2025-09-01 02:42:37,867] {subprocess.py:92} INFO - 25/09/01 02:42:37 INFO Utils: Copying /home/***/.ivy2/jars/org.apache.spark_spark-token-provider-kafka-0-10_2.12-3.3.1.jar to /tmp/spark-e9fcb46c-6f35-42bd-86d3-bf8c55550d38/userFiles-cc9c2dc1-b3e3-438e-8187-a0deca4da0e6/org.apache.spark_spark-token-provider-kafka-0-10_2.12-3.3.1.jar
[2025-09-01 02:42:37,871] {subprocess.py:92} INFO - 25/09/01 02:42:37 INFO SparkContext: Added file file:///home/***/.ivy2/jars/org.apache.kafka_kafka-clients-2.8.1.jar at file:///home/***/.ivy2/jars/org.apache.kafka_kafka-clients-2.8.1.jar with timestamp 1756694557400
[2025-09-01 02:42:37,872] {subprocess.py:92} INFO - 25/09/01 02:42:37 INFO Utils: Copying /home/***/.ivy2/jars/org.apache.kafka_kafka-clients-2.8.1.jar to /tmp/spark-e9fcb46c-6f35-42bd-86d3-bf8c55550d38/userFiles-cc9c2dc1-b3e3-438e-8187-a0deca4da0e6/org.apache.kafka_kafka-clients-2.8.1.jar
[2025-09-01 02:42:37,879] {subprocess.py:92} INFO - 25/09/01 02:42:37 INFO SparkContext: Added file file:///home/***/.ivy2/jars/com.google.code.findbugs_jsr305-3.0.0.jar at file:///home/***/.ivy2/jars/com.google.code.findbugs_jsr305-3.0.0.jar with timestamp 1756694557400
[2025-09-01 02:42:37,880] {subprocess.py:92} INFO - 25/09/01 02:42:37 INFO Utils: Copying /home/***/.ivy2/jars/com.google.code.findbugs_jsr305-3.0.0.jar to /tmp/spark-e9fcb46c-6f35-42bd-86d3-bf8c55550d38/userFiles-cc9c2dc1-b3e3-438e-8187-a0deca4da0e6/com.google.code.findbugs_jsr305-3.0.0.jar
[2025-09-01 02:42:37,884] {subprocess.py:92} INFO - 25/09/01 02:42:37 INFO SparkContext: Added file file:///home/***/.ivy2/jars/org.apache.commons_commons-pool2-2.11.1.jar at file:///home/***/.ivy2/jars/org.apache.commons_commons-pool2-2.11.1.jar with timestamp 1756694557400
[2025-09-01 02:42:37,884] {subprocess.py:92} INFO - 25/09/01 02:42:37 INFO Utils: Copying /home/***/.ivy2/jars/org.apache.commons_commons-pool2-2.11.1.jar to /tmp/spark-e9fcb46c-6f35-42bd-86d3-bf8c55550d38/userFiles-cc9c2dc1-b3e3-438e-8187-a0deca4da0e6/org.apache.commons_commons-pool2-2.11.1.jar
[2025-09-01 02:42:37,888] {subprocess.py:92} INFO - 25/09/01 02:42:37 INFO SparkContext: Added file file:///home/***/.ivy2/jars/org.spark-project.spark_unused-1.0.0.jar at file:///home/***/.ivy2/jars/org.spark-project.spark_unused-1.0.0.jar with timestamp 1756694557400
[2025-09-01 02:42:37,888] {subprocess.py:92} INFO - 25/09/01 02:42:37 INFO Utils: Copying /home/***/.ivy2/jars/org.spark-project.spark_unused-1.0.0.jar to /tmp/spark-e9fcb46c-6f35-42bd-86d3-bf8c55550d38/userFiles-cc9c2dc1-b3e3-438e-8187-a0deca4da0e6/org.spark-project.spark_unused-1.0.0.jar
[2025-09-01 02:42:37,892] {subprocess.py:92} INFO - 25/09/01 02:42:37 INFO SparkContext: Added file file:///home/***/.ivy2/jars/org.apache.hadoop_hadoop-client-runtime-3.3.2.jar at file:///home/***/.ivy2/jars/org.apache.hadoop_hadoop-client-runtime-3.3.2.jar with timestamp 1756694557400
[2025-09-01 02:42:37,893] {subprocess.py:92} INFO - 25/09/01 02:42:37 INFO Utils: Copying /home/***/.ivy2/jars/org.apache.hadoop_hadoop-client-runtime-3.3.2.jar to /tmp/spark-e9fcb46c-6f35-42bd-86d3-bf8c55550d38/userFiles-cc9c2dc1-b3e3-438e-8187-a0deca4da0e6/org.apache.hadoop_hadoop-client-runtime-3.3.2.jar
[2025-09-01 02:42:37,914] {subprocess.py:92} INFO - 25/09/01 02:42:37 INFO SparkContext: Added file file:///home/***/.ivy2/jars/org.lz4_lz4-java-1.8.0.jar at file:///home/***/.ivy2/jars/org.lz4_lz4-java-1.8.0.jar with timestamp 1756694557400
[2025-09-01 02:42:37,914] {subprocess.py:92} INFO - 25/09/01 02:42:37 INFO Utils: Copying /home/***/.ivy2/jars/org.lz4_lz4-java-1.8.0.jar to /tmp/spark-e9fcb46c-6f35-42bd-86d3-bf8c55550d38/userFiles-cc9c2dc1-b3e3-438e-8187-a0deca4da0e6/org.lz4_lz4-java-1.8.0.jar
[2025-09-01 02:42:37,918] {subprocess.py:92} INFO - 25/09/01 02:42:37 INFO SparkContext: Added file file:///home/***/.ivy2/jars/org.xerial.snappy_snappy-java-1.1.8.4.jar at file:///home/***/.ivy2/jars/org.xerial.snappy_snappy-java-1.1.8.4.jar with timestamp 1756694557400
[2025-09-01 02:42:37,918] {subprocess.py:92} INFO - 25/09/01 02:42:37 INFO Utils: Copying /home/***/.ivy2/jars/org.xerial.snappy_snappy-java-1.1.8.4.jar to /tmp/spark-e9fcb46c-6f35-42bd-86d3-bf8c55550d38/userFiles-cc9c2dc1-b3e3-438e-8187-a0deca4da0e6/org.xerial.snappy_snappy-java-1.1.8.4.jar
[2025-09-01 02:42:37,923] {subprocess.py:92} INFO - 25/09/01 02:42:37 INFO SparkContext: Added file file:///home/***/.ivy2/jars/org.slf4j_slf4j-api-1.7.32.jar at file:///home/***/.ivy2/jars/org.slf4j_slf4j-api-1.7.32.jar with timestamp 1756694557400
[2025-09-01 02:42:37,924] {subprocess.py:92} INFO - 25/09/01 02:42:37 INFO Utils: Copying /home/***/.ivy2/jars/org.slf4j_slf4j-api-1.7.32.jar to /tmp/spark-e9fcb46c-6f35-42bd-86d3-bf8c55550d38/userFiles-cc9c2dc1-b3e3-438e-8187-a0deca4da0e6/org.slf4j_slf4j-api-1.7.32.jar
[2025-09-01 02:42:37,927] {subprocess.py:92} INFO - 25/09/01 02:42:37 INFO SparkContext: Added file file:///home/***/.ivy2/jars/org.apache.hadoop_hadoop-client-api-3.3.2.jar at file:///home/***/.ivy2/jars/org.apache.hadoop_hadoop-client-api-3.3.2.jar with timestamp 1756694557400
[2025-09-01 02:42:37,927] {subprocess.py:92} INFO - 25/09/01 02:42:37 INFO Utils: Copying /home/***/.ivy2/jars/org.apache.hadoop_hadoop-client-api-3.3.2.jar to /tmp/spark-e9fcb46c-6f35-42bd-86d3-bf8c55550d38/userFiles-cc9c2dc1-b3e3-438e-8187-a0deca4da0e6/org.apache.hadoop_hadoop-client-api-3.3.2.jar
[2025-09-01 02:42:37,940] {subprocess.py:92} INFO - 25/09/01 02:42:37 INFO SparkContext: Added file file:///home/***/.ivy2/jars/commons-logging_commons-logging-1.1.3.jar at file:///home/***/.ivy2/jars/commons-logging_commons-logging-1.1.3.jar with timestamp 1756694557400
[2025-09-01 02:42:37,940] {subprocess.py:92} INFO - 25/09/01 02:42:37 INFO Utils: Copying /home/***/.ivy2/jars/commons-logging_commons-logging-1.1.3.jar to /tmp/spark-e9fcb46c-6f35-42bd-86d3-bf8c55550d38/userFiles-cc9c2dc1-b3e3-438e-8187-a0deca4da0e6/commons-logging_commons-logging-1.1.3.jar
[2025-09-01 02:42:37,980] {subprocess.py:92} INFO - 25/09/01 02:42:37 INFO Executor: Starting executor ID driver on host e66737cfc193
[2025-09-01 02:42:37,983] {subprocess.py:92} INFO - 25/09/01 02:42:37 INFO Executor: Starting executor with user classpath (userClassPathFirst = false): ''
[2025-09-01 02:42:37,990] {subprocess.py:92} INFO - 25/09/01 02:42:37 INFO Executor: Fetching file:///home/***/.ivy2/jars/commons-logging_commons-logging-1.1.3.jar with timestamp 1756694557400
[2025-09-01 02:42:38,001] {subprocess.py:92} INFO - 25/09/01 02:42:38 INFO Utils: /home/***/.ivy2/jars/commons-logging_commons-logging-1.1.3.jar has been previously copied to /tmp/spark-e9fcb46c-6f35-42bd-86d3-bf8c55550d38/userFiles-cc9c2dc1-b3e3-438e-8187-a0deca4da0e6/commons-logging_commons-logging-1.1.3.jar
[2025-09-01 02:42:38,004] {subprocess.py:92} INFO - 25/09/01 02:42:38 INFO Executor: Fetching file:///home/***/.ivy2/jars/org.spark-project.spark_unused-1.0.0.jar with timestamp 1756694557400
[2025-09-01 02:42:38,004] {subprocess.py:92} INFO - 25/09/01 02:42:38 INFO Utils: /home/***/.ivy2/jars/org.spark-project.spark_unused-1.0.0.jar has been previously copied to /tmp/spark-e9fcb46c-6f35-42bd-86d3-bf8c55550d38/userFiles-cc9c2dc1-b3e3-438e-8187-a0deca4da0e6/org.spark-project.spark_unused-1.0.0.jar
[2025-09-01 02:42:38,007] {subprocess.py:92} INFO - 25/09/01 02:42:38 INFO Executor: Fetching file:///home/***/.ivy2/jars/org.apache.spark_spark-sql-kafka-0-10_2.12-3.3.1.jar with timestamp 1756694557400
[2025-09-01 02:42:38,010] {subprocess.py:92} INFO - 25/09/01 02:42:38 INFO Utils: /home/***/.ivy2/jars/org.apache.spark_spark-sql-kafka-0-10_2.12-3.3.1.jar has been previously copied to /tmp/spark-e9fcb46c-6f35-42bd-86d3-bf8c55550d38/userFiles-cc9c2dc1-b3e3-438e-8187-a0deca4da0e6/org.apache.spark_spark-sql-kafka-0-10_2.12-3.3.1.jar
[2025-09-01 02:42:38,013] {subprocess.py:92} INFO - 25/09/01 02:42:38 INFO Executor: Fetching file:///home/***/.ivy2/jars/org.apache.hadoop_hadoop-client-api-3.3.2.jar with timestamp 1756694557400
[2025-09-01 02:42:38,022] {subprocess.py:92} INFO - 25/09/01 02:42:38 INFO Utils: /home/***/.ivy2/jars/org.apache.hadoop_hadoop-client-api-3.3.2.jar has been previously copied to /tmp/spark-e9fcb46c-6f35-42bd-86d3-bf8c55550d38/userFiles-cc9c2dc1-b3e3-438e-8187-a0deca4da0e6/org.apache.hadoop_hadoop-client-api-3.3.2.jar
[2025-09-01 02:42:38,025] {subprocess.py:92} INFO - 25/09/01 02:42:38 INFO Executor: Fetching file:///home/***/.ivy2/jars/org.apache.hadoop_hadoop-client-runtime-3.3.2.jar with timestamp 1756694557400
[2025-09-01 02:42:38,039] {subprocess.py:92} INFO - 25/09/01 02:42:38 INFO Utils: /home/***/.ivy2/jars/org.apache.hadoop_hadoop-client-runtime-3.3.2.jar has been previously copied to /tmp/spark-e9fcb46c-6f35-42bd-86d3-bf8c55550d38/userFiles-cc9c2dc1-b3e3-438e-8187-a0deca4da0e6/org.apache.hadoop_hadoop-client-runtime-3.3.2.jar
[2025-09-01 02:42:38,042] {subprocess.py:92} INFO - 25/09/01 02:42:38 INFO Executor: Fetching file:///home/***/.ivy2/jars/org.slf4j_slf4j-api-1.7.32.jar with timestamp 1756694557400
[2025-09-01 02:42:38,042] {subprocess.py:92} INFO - 25/09/01 02:42:38 INFO Utils: /home/***/.ivy2/jars/org.slf4j_slf4j-api-1.7.32.jar has been previously copied to /tmp/spark-e9fcb46c-6f35-42bd-86d3-bf8c55550d38/userFiles-cc9c2dc1-b3e3-438e-8187-a0deca4da0e6/org.slf4j_slf4j-api-1.7.32.jar
[2025-09-01 02:42:38,046] {subprocess.py:92} INFO - 25/09/01 02:42:38 INFO Executor: Fetching file:///home/***/.ivy2/jars/org.lz4_lz4-java-1.8.0.jar with timestamp 1756694557400
[2025-09-01 02:42:38,046] {subprocess.py:92} INFO - 25/09/01 02:42:38 INFO Utils: /home/***/.ivy2/jars/org.lz4_lz4-java-1.8.0.jar has been previously copied to /tmp/spark-e9fcb46c-6f35-42bd-86d3-bf8c55550d38/userFiles-cc9c2dc1-b3e3-438e-8187-a0deca4da0e6/org.lz4_lz4-java-1.8.0.jar
[2025-09-01 02:42:38,050] {subprocess.py:92} INFO - 25/09/01 02:42:38 INFO Executor: Fetching file:///home/***/.ivy2/jars/org.apache.commons_commons-pool2-2.11.1.jar with timestamp 1756694557400
[2025-09-01 02:42:38,050] {subprocess.py:92} INFO - 25/09/01 02:42:38 INFO Utils: /home/***/.ivy2/jars/org.apache.commons_commons-pool2-2.11.1.jar has been previously copied to /tmp/spark-e9fcb46c-6f35-42bd-86d3-bf8c55550d38/userFiles-cc9c2dc1-b3e3-438e-8187-a0deca4da0e6/org.apache.commons_commons-pool2-2.11.1.jar
[2025-09-01 02:42:38,053] {subprocess.py:92} INFO - 25/09/01 02:42:38 INFO Executor: Fetching file:///home/***/.ivy2/jars/com.google.code.findbugs_jsr305-3.0.0.jar with timestamp 1756694557400
[2025-09-01 02:42:38,053] {subprocess.py:92} INFO - 25/09/01 02:42:38 INFO Utils: /home/***/.ivy2/jars/com.google.code.findbugs_jsr305-3.0.0.jar has been previously copied to /tmp/spark-e9fcb46c-6f35-42bd-86d3-bf8c55550d38/userFiles-cc9c2dc1-b3e3-438e-8187-a0deca4da0e6/com.google.code.findbugs_jsr305-3.0.0.jar
[2025-09-01 02:42:38,057] {subprocess.py:92} INFO - 25/09/01 02:42:38 INFO Executor: Fetching file:///home/***/.ivy2/jars/org.apache.spark_spark-token-provider-kafka-0-10_2.12-3.3.1.jar with timestamp 1756694557400
[2025-09-01 02:42:38,057] {subprocess.py:92} INFO - 25/09/01 02:42:38 INFO Utils: /home/***/.ivy2/jars/org.apache.spark_spark-token-provider-kafka-0-10_2.12-3.3.1.jar has been previously copied to /tmp/spark-e9fcb46c-6f35-42bd-86d3-bf8c55550d38/userFiles-cc9c2dc1-b3e3-438e-8187-a0deca4da0e6/org.apache.spark_spark-token-provider-kafka-0-10_2.12-3.3.1.jar
[2025-09-01 02:42:38,061] {subprocess.py:92} INFO - 25/09/01 02:42:38 INFO Executor: Fetching file:///home/***/.ivy2/jars/org.apache.kafka_kafka-clients-2.8.1.jar with timestamp 1756694557400
[2025-09-01 02:42:38,065] {subprocess.py:92} INFO - 25/09/01 02:42:38 INFO Utils: /home/***/.ivy2/jars/org.apache.kafka_kafka-clients-2.8.1.jar has been previously copied to /tmp/spark-e9fcb46c-6f35-42bd-86d3-bf8c55550d38/userFiles-cc9c2dc1-b3e3-438e-8187-a0deca4da0e6/org.apache.kafka_kafka-clients-2.8.1.jar
[2025-09-01 02:42:38,069] {subprocess.py:92} INFO - 25/09/01 02:42:38 INFO Executor: Fetching file:///home/***/.ivy2/jars/org.xerial.snappy_snappy-java-1.1.8.4.jar with timestamp 1756694557400
[2025-09-01 02:42:38,071] {subprocess.py:92} INFO - 25/09/01 02:42:38 INFO Utils: /home/***/.ivy2/jars/org.xerial.snappy_snappy-java-1.1.8.4.jar has been previously copied to /tmp/spark-e9fcb46c-6f35-42bd-86d3-bf8c55550d38/userFiles-cc9c2dc1-b3e3-438e-8187-a0deca4da0e6/org.xerial.snappy_snappy-java-1.1.8.4.jar
[2025-09-01 02:42:38,076] {subprocess.py:92} INFO - 25/09/01 02:42:38 INFO Executor: Fetching spark://e66737cfc193:36835/jars/com.google.code.findbugs_jsr305-3.0.0.jar with timestamp 1756694557400
[2025-09-01 02:42:38,113] {subprocess.py:92} INFO - 25/09/01 02:42:38 INFO TransportClientFactory: Successfully created connection to e66737cfc193/172.20.0.18:36835 after 25 ms (0 ms spent in bootstraps)
[2025-09-01 02:42:38,118] {subprocess.py:92} INFO - 25/09/01 02:42:38 INFO Utils: Fetching spark://e66737cfc193:36835/jars/com.google.code.findbugs_jsr305-3.0.0.jar to /tmp/spark-e9fcb46c-6f35-42bd-86d3-bf8c55550d38/userFiles-cc9c2dc1-b3e3-438e-8187-a0deca4da0e6/fetchFileTemp7534905938817320459.tmp
[2025-09-01 02:42:38,154] {subprocess.py:92} INFO - 25/09/01 02:42:38 INFO Utils: /tmp/spark-e9fcb46c-6f35-42bd-86d3-bf8c55550d38/userFiles-cc9c2dc1-b3e3-438e-8187-a0deca4da0e6/fetchFileTemp7534905938817320459.tmp has been previously copied to /tmp/spark-e9fcb46c-6f35-42bd-86d3-bf8c55550d38/userFiles-cc9c2dc1-b3e3-438e-8187-a0deca4da0e6/com.google.code.findbugs_jsr305-3.0.0.jar
[2025-09-01 02:42:38,159] {subprocess.py:92} INFO - 25/09/01 02:42:38 INFO Executor: Adding file:/tmp/spark-e9fcb46c-6f35-42bd-86d3-bf8c55550d38/userFiles-cc9c2dc1-b3e3-438e-8187-a0deca4da0e6/com.google.code.findbugs_jsr305-3.0.0.jar to class loader
[2025-09-01 02:42:38,159] {subprocess.py:92} INFO - 25/09/01 02:42:38 INFO Executor: Fetching spark://e66737cfc193:36835/jars/org.apache.spark_spark-sql-kafka-0-10_2.12-3.3.1.jar with timestamp 1756694557400
[2025-09-01 02:42:38,160] {subprocess.py:92} INFO - 25/09/01 02:42:38 INFO Utils: Fetching spark://e66737cfc193:36835/jars/org.apache.spark_spark-sql-kafka-0-10_2.12-3.3.1.jar to /tmp/spark-e9fcb46c-6f35-42bd-86d3-bf8c55550d38/userFiles-cc9c2dc1-b3e3-438e-8187-a0deca4da0e6/fetchFileTemp12586798844126012197.tmp
[2025-09-01 02:42:38,163] {subprocess.py:92} INFO - 25/09/01 02:42:38 INFO Utils: /tmp/spark-e9fcb46c-6f35-42bd-86d3-bf8c55550d38/userFiles-cc9c2dc1-b3e3-438e-8187-a0deca4da0e6/fetchFileTemp12586798844126012197.tmp has been previously copied to /tmp/spark-e9fcb46c-6f35-42bd-86d3-bf8c55550d38/userFiles-cc9c2dc1-b3e3-438e-8187-a0deca4da0e6/org.apache.spark_spark-sql-kafka-0-10_2.12-3.3.1.jar
[2025-09-01 02:42:38,168] {subprocess.py:92} INFO - 25/09/01 02:42:38 INFO Executor: Adding file:/tmp/spark-e9fcb46c-6f35-42bd-86d3-bf8c55550d38/userFiles-cc9c2dc1-b3e3-438e-8187-a0deca4da0e6/org.apache.spark_spark-sql-kafka-0-10_2.12-3.3.1.jar to class loader
[2025-09-01 02:42:38,169] {subprocess.py:92} INFO - 25/09/01 02:42:38 INFO Executor: Fetching spark://e66737cfc193:36835/jars/org.slf4j_slf4j-api-1.7.32.jar with timestamp 1756694557400
[2025-09-01 02:42:38,169] {subprocess.py:92} INFO - 25/09/01 02:42:38 INFO Utils: Fetching spark://e66737cfc193:36835/jars/org.slf4j_slf4j-api-1.7.32.jar to /tmp/spark-e9fcb46c-6f35-42bd-86d3-bf8c55550d38/userFiles-cc9c2dc1-b3e3-438e-8187-a0deca4da0e6/fetchFileTemp12057202052119326055.tmp
[2025-09-01 02:42:38,171] {subprocess.py:92} INFO - 25/09/01 02:42:38 INFO Utils: /tmp/spark-e9fcb46c-6f35-42bd-86d3-bf8c55550d38/userFiles-cc9c2dc1-b3e3-438e-8187-a0deca4da0e6/fetchFileTemp12057202052119326055.tmp has been previously copied to /tmp/spark-e9fcb46c-6f35-42bd-86d3-bf8c55550d38/userFiles-cc9c2dc1-b3e3-438e-8187-a0deca4da0e6/org.slf4j_slf4j-api-1.7.32.jar
[2025-09-01 02:42:38,176] {subprocess.py:92} INFO - 25/09/01 02:42:38 INFO Executor: Adding file:/tmp/spark-e9fcb46c-6f35-42bd-86d3-bf8c55550d38/userFiles-cc9c2dc1-b3e3-438e-8187-a0deca4da0e6/org.slf4j_slf4j-api-1.7.32.jar to class loader
[2025-09-01 02:42:38,176] {subprocess.py:92} INFO - 25/09/01 02:42:38 INFO Executor: Fetching spark://e66737cfc193:36835/jars/org.xerial.snappy_snappy-java-1.1.8.4.jar with timestamp 1756694557400
[2025-09-01 02:42:38,176] {subprocess.py:92} INFO - 25/09/01 02:42:38 INFO Utils: Fetching spark://e66737cfc193:36835/jars/org.xerial.snappy_snappy-java-1.1.8.4.jar to /tmp/spark-e9fcb46c-6f35-42bd-86d3-bf8c55550d38/userFiles-cc9c2dc1-b3e3-438e-8187-a0deca4da0e6/fetchFileTemp4229105297912310241.tmp
[2025-09-01 02:42:38,184] {subprocess.py:92} INFO - 25/09/01 02:42:38 INFO Utils: /tmp/spark-e9fcb46c-6f35-42bd-86d3-bf8c55550d38/userFiles-cc9c2dc1-b3e3-438e-8187-a0deca4da0e6/fetchFileTemp4229105297912310241.tmp has been previously copied to /tmp/spark-e9fcb46c-6f35-42bd-86d3-bf8c55550d38/userFiles-cc9c2dc1-b3e3-438e-8187-a0deca4da0e6/org.xerial.snappy_snappy-java-1.1.8.4.jar
[2025-09-01 02:42:38,188] {subprocess.py:92} INFO - 25/09/01 02:42:38 INFO Executor: Adding file:/tmp/spark-e9fcb46c-6f35-42bd-86d3-bf8c55550d38/userFiles-cc9c2dc1-b3e3-438e-8187-a0deca4da0e6/org.xerial.snappy_snappy-java-1.1.8.4.jar to class loader
[2025-09-01 02:42:38,189] {subprocess.py:92} INFO - 25/09/01 02:42:38 INFO Executor: Fetching spark://e66737cfc193:36835/jars/org.lz4_lz4-java-1.8.0.jar with timestamp 1756694557400
[2025-09-01 02:42:38,189] {subprocess.py:92} INFO - 25/09/01 02:42:38 INFO Utils: Fetching spark://e66737cfc193:36835/jars/org.lz4_lz4-java-1.8.0.jar to /tmp/spark-e9fcb46c-6f35-42bd-86d3-bf8c55550d38/userFiles-cc9c2dc1-b3e3-438e-8187-a0deca4da0e6/fetchFileTemp1121373752298357001.tmp
[2025-09-01 02:42:38,192] {subprocess.py:92} INFO - 25/09/01 02:42:38 INFO Utils: /tmp/spark-e9fcb46c-6f35-42bd-86d3-bf8c55550d38/userFiles-cc9c2dc1-b3e3-438e-8187-a0deca4da0e6/fetchFileTemp1121373752298357001.tmp has been previously copied to /tmp/spark-e9fcb46c-6f35-42bd-86d3-bf8c55550d38/userFiles-cc9c2dc1-b3e3-438e-8187-a0deca4da0e6/org.lz4_lz4-java-1.8.0.jar
[2025-09-01 02:42:38,197] {subprocess.py:92} INFO - 25/09/01 02:42:38 INFO Executor: Adding file:/tmp/spark-e9fcb46c-6f35-42bd-86d3-bf8c55550d38/userFiles-cc9c2dc1-b3e3-438e-8187-a0deca4da0e6/org.lz4_lz4-java-1.8.0.jar to class loader
[2025-09-01 02:42:38,197] {subprocess.py:92} INFO - 25/09/01 02:42:38 INFO Executor: Fetching spark://e66737cfc193:36835/jars/org.apache.hadoop_hadoop-client-api-3.3.2.jar with timestamp 1756694557400
[2025-09-01 02:42:38,197] {subprocess.py:92} INFO - 25/09/01 02:42:38 INFO Utils: Fetching spark://e66737cfc193:36835/jars/org.apache.hadoop_hadoop-client-api-3.3.2.jar to /tmp/spark-e9fcb46c-6f35-42bd-86d3-bf8c55550d38/userFiles-cc9c2dc1-b3e3-438e-8187-a0deca4da0e6/fetchFileTemp13385660410789116160.tmp
[2025-09-01 02:42:38,233] {subprocess.py:92} INFO - 25/09/01 02:42:38 INFO Utils: /tmp/spark-e9fcb46c-6f35-42bd-86d3-bf8c55550d38/userFiles-cc9c2dc1-b3e3-438e-8187-a0deca4da0e6/fetchFileTemp13385660410789116160.tmp has been previously copied to /tmp/spark-e9fcb46c-6f35-42bd-86d3-bf8c55550d38/userFiles-cc9c2dc1-b3e3-438e-8187-a0deca4da0e6/org.apache.hadoop_hadoop-client-api-3.3.2.jar
[2025-09-01 02:42:38,238] {subprocess.py:92} INFO - 25/09/01 02:42:38 INFO Executor: Adding file:/tmp/spark-e9fcb46c-6f35-42bd-86d3-bf8c55550d38/userFiles-cc9c2dc1-b3e3-438e-8187-a0deca4da0e6/org.apache.hadoop_hadoop-client-api-3.3.2.jar to class loader
[2025-09-01 02:42:38,238] {subprocess.py:92} INFO - 25/09/01 02:42:38 INFO Executor: Fetching spark://e66737cfc193:36835/jars/org.spark-project.spark_unused-1.0.0.jar with timestamp 1756694557400
[2025-09-01 02:42:38,238] {subprocess.py:92} INFO - 25/09/01 02:42:38 INFO Utils: Fetching spark://e66737cfc193:36835/jars/org.spark-project.spark_unused-1.0.0.jar to /tmp/spark-e9fcb46c-6f35-42bd-86d3-bf8c55550d38/userFiles-cc9c2dc1-b3e3-438e-8187-a0deca4da0e6/fetchFileTemp2571177791911525715.tmp
[2025-09-01 02:42:38,240] {subprocess.py:92} INFO - 25/09/01 02:42:38 INFO Utils: /tmp/spark-e9fcb46c-6f35-42bd-86d3-bf8c55550d38/userFiles-cc9c2dc1-b3e3-438e-8187-a0deca4da0e6/fetchFileTemp2571177791911525715.tmp has been previously copied to /tmp/spark-e9fcb46c-6f35-42bd-86d3-bf8c55550d38/userFiles-cc9c2dc1-b3e3-438e-8187-a0deca4da0e6/org.spark-project.spark_unused-1.0.0.jar
[2025-09-01 02:42:38,243] {subprocess.py:92} INFO - 25/09/01 02:42:38 INFO Executor: Adding file:/tmp/spark-e9fcb46c-6f35-42bd-86d3-bf8c55550d38/userFiles-cc9c2dc1-b3e3-438e-8187-a0deca4da0e6/org.spark-project.spark_unused-1.0.0.jar to class loader
[2025-09-01 02:42:38,243] {subprocess.py:92} INFO - 25/09/01 02:42:38 INFO Executor: Fetching spark://e66737cfc193:36835/jars/commons-logging_commons-logging-1.1.3.jar with timestamp 1756694557400
[2025-09-01 02:42:38,244] {subprocess.py:92} INFO - 25/09/01 02:42:38 INFO Utils: Fetching spark://e66737cfc193:36835/jars/commons-logging_commons-logging-1.1.3.jar to /tmp/spark-e9fcb46c-6f35-42bd-86d3-bf8c55550d38/userFiles-cc9c2dc1-b3e3-438e-8187-a0deca4da0e6/fetchFileTemp4708710885251645183.tmp
[2025-09-01 02:42:38,245] {subprocess.py:92} INFO - 25/09/01 02:42:38 INFO Utils: /tmp/spark-e9fcb46c-6f35-42bd-86d3-bf8c55550d38/userFiles-cc9c2dc1-b3e3-438e-8187-a0deca4da0e6/fetchFileTemp4708710885251645183.tmp has been previously copied to /tmp/spark-e9fcb46c-6f35-42bd-86d3-bf8c55550d38/userFiles-cc9c2dc1-b3e3-438e-8187-a0deca4da0e6/commons-logging_commons-logging-1.1.3.jar
[2025-09-01 02:42:38,248] {subprocess.py:92} INFO - 25/09/01 02:42:38 INFO Executor: Adding file:/tmp/spark-e9fcb46c-6f35-42bd-86d3-bf8c55550d38/userFiles-cc9c2dc1-b3e3-438e-8187-a0deca4da0e6/commons-logging_commons-logging-1.1.3.jar to class loader
[2025-09-01 02:42:38,248] {subprocess.py:92} INFO - 25/09/01 02:42:38 INFO Executor: Fetching spark://e66737cfc193:36835/jars/org.apache.spark_spark-token-provider-kafka-0-10_2.12-3.3.1.jar with timestamp 1756694557400
[2025-09-01 02:42:38,249] {subprocess.py:92} INFO - 25/09/01 02:42:38 INFO Utils: Fetching spark://e66737cfc193:36835/jars/org.apache.spark_spark-token-provider-kafka-0-10_2.12-3.3.1.jar to /tmp/spark-e9fcb46c-6f35-42bd-86d3-bf8c55550d38/userFiles-cc9c2dc1-b3e3-438e-8187-a0deca4da0e6/fetchFileTemp4442787523123675433.tmp
[2025-09-01 02:42:38,251] {subprocess.py:92} INFO - 25/09/01 02:42:38 INFO Utils: /tmp/spark-e9fcb46c-6f35-42bd-86d3-bf8c55550d38/userFiles-cc9c2dc1-b3e3-438e-8187-a0deca4da0e6/fetchFileTemp4442787523123675433.tmp has been previously copied to /tmp/spark-e9fcb46c-6f35-42bd-86d3-bf8c55550d38/userFiles-cc9c2dc1-b3e3-438e-8187-a0deca4da0e6/org.apache.spark_spark-token-provider-kafka-0-10_2.12-3.3.1.jar
[2025-09-01 02:42:38,254] {subprocess.py:92} INFO - 25/09/01 02:42:38 INFO Executor: Adding file:/tmp/spark-e9fcb46c-6f35-42bd-86d3-bf8c55550d38/userFiles-cc9c2dc1-b3e3-438e-8187-a0deca4da0e6/org.apache.spark_spark-token-provider-kafka-0-10_2.12-3.3.1.jar to class loader
[2025-09-01 02:42:38,254] {subprocess.py:92} INFO - 25/09/01 02:42:38 INFO Executor: Fetching spark://e66737cfc193:36835/jars/org.apache.commons_commons-pool2-2.11.1.jar with timestamp 1756694557400
[2025-09-01 02:42:38,254] {subprocess.py:92} INFO - 25/09/01 02:42:38 INFO Utils: Fetching spark://e66737cfc193:36835/jars/org.apache.commons_commons-pool2-2.11.1.jar to /tmp/spark-e9fcb46c-6f35-42bd-86d3-bf8c55550d38/userFiles-cc9c2dc1-b3e3-438e-8187-a0deca4da0e6/fetchFileTemp6847466787313329548.tmp
[2025-09-01 02:42:38,256] {subprocess.py:92} INFO - 25/09/01 02:42:38 INFO Utils: /tmp/spark-e9fcb46c-6f35-42bd-86d3-bf8c55550d38/userFiles-cc9c2dc1-b3e3-438e-8187-a0deca4da0e6/fetchFileTemp6847466787313329548.tmp has been previously copied to /tmp/spark-e9fcb46c-6f35-42bd-86d3-bf8c55550d38/userFiles-cc9c2dc1-b3e3-438e-8187-a0deca4da0e6/org.apache.commons_commons-pool2-2.11.1.jar
[2025-09-01 02:42:38,261] {subprocess.py:92} INFO - 25/09/01 02:42:38 INFO Executor: Adding file:/tmp/spark-e9fcb46c-6f35-42bd-86d3-bf8c55550d38/userFiles-cc9c2dc1-b3e3-438e-8187-a0deca4da0e6/org.apache.commons_commons-pool2-2.11.1.jar to class loader
[2025-09-01 02:42:38,261] {subprocess.py:92} INFO - 25/09/01 02:42:38 INFO Executor: Fetching spark://e66737cfc193:36835/jars/org.apache.kafka_kafka-clients-2.8.1.jar with timestamp 1756694557400
[2025-09-01 02:42:38,261] {subprocess.py:92} INFO - 25/09/01 02:42:38 INFO Utils: Fetching spark://e66737cfc193:36835/jars/org.apache.kafka_kafka-clients-2.8.1.jar to /tmp/spark-e9fcb46c-6f35-42bd-86d3-bf8c55550d38/userFiles-cc9c2dc1-b3e3-438e-8187-a0deca4da0e6/fetchFileTemp8387976497395535994.tmp
[2025-09-01 02:42:38,279] {subprocess.py:92} INFO - 25/09/01 02:42:38 INFO Utils: /tmp/spark-e9fcb46c-6f35-42bd-86d3-bf8c55550d38/userFiles-cc9c2dc1-b3e3-438e-8187-a0deca4da0e6/fetchFileTemp8387976497395535994.tmp has been previously copied to /tmp/spark-e9fcb46c-6f35-42bd-86d3-bf8c55550d38/userFiles-cc9c2dc1-b3e3-438e-8187-a0deca4da0e6/org.apache.kafka_kafka-clients-2.8.1.jar
[2025-09-01 02:42:38,283] {subprocess.py:92} INFO - 25/09/01 02:42:38 INFO Executor: Adding file:/tmp/spark-e9fcb46c-6f35-42bd-86d3-bf8c55550d38/userFiles-cc9c2dc1-b3e3-438e-8187-a0deca4da0e6/org.apache.kafka_kafka-clients-2.8.1.jar to class loader
[2025-09-01 02:42:38,283] {subprocess.py:92} INFO - 25/09/01 02:42:38 INFO Executor: Fetching spark://e66737cfc193:36835/jars/org.apache.hadoop_hadoop-client-runtime-3.3.2.jar with timestamp 1756694557400
[2025-09-01 02:42:38,283] {subprocess.py:92} INFO - 25/09/01 02:42:38 INFO Utils: Fetching spark://e66737cfc193:36835/jars/org.apache.hadoop_hadoop-client-runtime-3.3.2.jar to /tmp/spark-e9fcb46c-6f35-42bd-86d3-bf8c55550d38/userFiles-cc9c2dc1-b3e3-438e-8187-a0deca4da0e6/fetchFileTemp16663831015615624596.tmp
[2025-09-01 02:42:38,355] {subprocess.py:92} INFO - 25/09/01 02:42:38 INFO Utils: /tmp/spark-e9fcb46c-6f35-42bd-86d3-bf8c55550d38/userFiles-cc9c2dc1-b3e3-438e-8187-a0deca4da0e6/fetchFileTemp16663831015615624596.tmp has been previously copied to /tmp/spark-e9fcb46c-6f35-42bd-86d3-bf8c55550d38/userFiles-cc9c2dc1-b3e3-438e-8187-a0deca4da0e6/org.apache.hadoop_hadoop-client-runtime-3.3.2.jar
[2025-09-01 02:42:38,361] {subprocess.py:92} INFO - 25/09/01 02:42:38 INFO Executor: Adding file:/tmp/spark-e9fcb46c-6f35-42bd-86d3-bf8c55550d38/userFiles-cc9c2dc1-b3e3-438e-8187-a0deca4da0e6/org.apache.hadoop_hadoop-client-runtime-3.3.2.jar to class loader
[2025-09-01 02:42:38,365] {subprocess.py:92} INFO - 25/09/01 02:42:38 INFO Utils: Successfully started service 'org.apache.spark.network.netty.NettyBlockTransferService' on port 41505.
[2025-09-01 02:42:38,366] {subprocess.py:92} INFO - 25/09/01 02:42:38 INFO NettyBlockTransferService: Server created on e66737cfc193:41505
[2025-09-01 02:42:38,366] {subprocess.py:92} INFO - 25/09/01 02:42:38 INFO BlockManager: Using org.apache.spark.storage.RandomBlockReplicationPolicy for block replication policy
[2025-09-01 02:42:38,370] {subprocess.py:92} INFO - 25/09/01 02:42:38 INFO BlockManagerMaster: Registering BlockManager BlockManagerId(driver, e66737cfc193, 41505, None)
[2025-09-01 02:42:38,373] {subprocess.py:92} INFO - 25/09/01 02:42:38 INFO BlockManagerMasterEndpoint: Registering block manager e66737cfc193:41505 with 434.4 MiB RAM, BlockManagerId(driver, e66737cfc193, 41505, None)
[2025-09-01 02:42:38,376] {subprocess.py:92} INFO - 25/09/01 02:42:38 INFO BlockManagerMaster: Registered BlockManager BlockManagerId(driver, e66737cfc193, 41505, None)
[2025-09-01 02:42:38,377] {subprocess.py:92} INFO - 25/09/01 02:42:38 INFO BlockManager: Initialized BlockManager: BlockManagerId(driver, e66737cfc193, 41505, None)
[2025-09-01 02:42:38,610] {subprocess.py:92} INFO - Connexion à Kafka...
[2025-09-01 02:42:39,899] {subprocess.py:92} INFO - Connexion Kafka réussie (kafka:9092)
[2025-09-01 02:42:39,899] {subprocess.py:92} INFO - Transformation des données JSON...
[2025-09-01 02:42:40,144] {subprocess.py:92} INFO - Démarrage du streaming vers HDFS...
[2025-09-01 02:42:40,647] {subprocess.py:92} INFO - Streaming actif - Données météo sauvegardées dans HDFS:/data/weather
[2025-09-01 04:43:42,710] {base_job.py:229} ERROR - LocalTaskJob heartbeat got an exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 3141, in _wrap_pool_connect
    return fn()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 301, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 755, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 419, in checkout
    rec = pool._do_get()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/impl.py", line 259, in _do_get
    return self._create_connection()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 247, in _create_connection
    return _ConnectionRecord(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 362, in __init__
    self.__connect(first_connect_check=True)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 605, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 72, in __exit__
    with_traceback=exc_tb,
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 599, in __connect
    connection = pool._invoke_creator(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/create.py", line 578, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 583, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.7/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: could not translate host name "postgres" to address: Temporary failure in name resolution


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/jobs/base_job.py", line 225, in heartbeat
    self.heartbeat_callback(session=session)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 68, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/jobs/local_task_job.py", line 186, in heartbeat_callback
    self.task_instance.refresh_from_db()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 71, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 873, in refresh_from_db
    ti = qry.first()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 2734, in first
    return self.limit(1)._iter().first()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 2821, in _iter
    execution_options={"_sa_orm_load_options": self.load_options},
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 1669, in execute
    conn = self._connection_for_bind(bind, close_with_result=True)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 1520, in _connection_for_bind
    engine, execution_options
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 747, in _connection_for_bind
    conn = bind.connect()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 3095, in connect
    return self._connection_cls(self, close_with_result=close_with_result)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 91, in __init__
    else engine.raw_connection()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 3174, in raw_connection
    return self._wrap_pool_connect(self.pool.connect, _connection)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 3145, in _wrap_pool_connect
    e, dialect, self
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 2004, in _handle_dbapi_exception_noconnection
    sqlalchemy_exception, with_traceback=exc_info[2], from_=e
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 3141, in _wrap_pool_connect
    return fn()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 301, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 755, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 419, in checkout
    rec = pool._do_get()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/impl.py", line 259, in _do_get
    return self._create_connection()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 247, in _create_connection
    return _ConnectionRecord(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 362, in __init__
    self.__connect(first_connect_check=True)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 605, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 72, in __exit__
    with_traceback=exc_tb,
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 599, in __connect
    connection = pool._invoke_creator(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/create.py", line 578, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 583, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.7/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) could not translate host name "postgres" to address: Temporary failure in name resolution

(Background on this error at: http://sqlalche.me/e/14/e3q8)
[2025-09-01 04:44:17,985] {base_job.py:229} ERROR - LocalTaskJob heartbeat got an exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 3141, in _wrap_pool_connect
    return fn()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 301, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 755, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 419, in checkout
    rec = pool._do_get()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/impl.py", line 259, in _do_get
    return self._create_connection()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 247, in _create_connection
    return _ConnectionRecord(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 362, in __init__
    self.__connect(first_connect_check=True)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 605, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 72, in __exit__
    with_traceback=exc_tb,
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 599, in __connect
    connection = pool._invoke_creator(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/create.py", line 578, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 583, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.7/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: could not translate host name "postgres" to address: Temporary failure in name resolution


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/jobs/base_job.py", line 201, in heartbeat
    session.merge(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 2877, in merge
    _resolve_conflict_map=_resolve_conflict_map,
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 2950, in _merge
    merged = self.get(mapper.class_, key[1], identity_token=key[2])
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 2702, in get
    identity_token=identity_token,
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 2800, in _get_impl
    load_options=load_options,
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/loading.py", line 535, in load_on_pk_identity
    bind_arguments=bind_arguments,
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 1669, in execute
    conn = self._connection_for_bind(bind, close_with_result=True)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 1520, in _connection_for_bind
    engine, execution_options
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 747, in _connection_for_bind
    conn = bind.connect()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 3095, in connect
    return self._connection_cls(self, close_with_result=close_with_result)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 91, in __init__
    else engine.raw_connection()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 3174, in raw_connection
    return self._wrap_pool_connect(self.pool.connect, _connection)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 3145, in _wrap_pool_connect
    e, dialect, self
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 2004, in _handle_dbapi_exception_noconnection
    sqlalchemy_exception, with_traceback=exc_info[2], from_=e
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 3141, in _wrap_pool_connect
    return fn()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 301, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 755, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 419, in checkout
    rec = pool._do_get()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/impl.py", line 259, in _do_get
    return self._create_connection()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 247, in _create_connection
    return _ConnectionRecord(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 362, in __init__
    self.__connect(first_connect_check=True)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 605, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 72, in __exit__
    with_traceback=exc_tb,
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 599, in __connect
    connection = pool._invoke_creator(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/create.py", line 578, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 583, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.7/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) could not translate host name "postgres" to address: Temporary failure in name resolution

(Background on this error at: http://sqlalche.me/e/14/e3q8)
[2025-09-01 04:45:36,613] {base_job.py:229} ERROR - LocalTaskJob heartbeat got an exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 3141, in _wrap_pool_connect
    return fn()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 301, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 755, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 419, in checkout
    rec = pool._do_get()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/impl.py", line 259, in _do_get
    return self._create_connection()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 247, in _create_connection
    return _ConnectionRecord(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 362, in __init__
    self.__connect(first_connect_check=True)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 605, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 72, in __exit__
    with_traceback=exc_tb,
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 599, in __connect
    connection = pool._invoke_creator(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/create.py", line 578, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 583, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.7/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: could not translate host name "postgres" to address: Temporary failure in name resolution


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/jobs/base_job.py", line 219, in heartbeat
    session.merge(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 2877, in merge
    _resolve_conflict_map=_resolve_conflict_map,
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 2950, in _merge
    merged = self.get(mapper.class_, key[1], identity_token=key[2])
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 2702, in get
    identity_token=identity_token,
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 2800, in _get_impl
    load_options=load_options,
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/loading.py", line 535, in load_on_pk_identity
    bind_arguments=bind_arguments,
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 1669, in execute
    conn = self._connection_for_bind(bind, close_with_result=True)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 1520, in _connection_for_bind
    engine, execution_options
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 747, in _connection_for_bind
    conn = bind.connect()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 3095, in connect
    return self._connection_cls(self, close_with_result=close_with_result)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 91, in __init__
    else engine.raw_connection()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 3174, in raw_connection
    return self._wrap_pool_connect(self.pool.connect, _connection)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 3145, in _wrap_pool_connect
    e, dialect, self
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 2004, in _handle_dbapi_exception_noconnection
    sqlalchemy_exception, with_traceback=exc_info[2], from_=e
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 3141, in _wrap_pool_connect
    return fn()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 301, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 755, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 419, in checkout
    rec = pool._do_get()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/impl.py", line 259, in _do_get
    return self._create_connection()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 247, in _create_connection
    return _ConnectionRecord(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 362, in __init__
    self.__connect(first_connect_check=True)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 605, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 72, in __exit__
    with_traceback=exc_tb,
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 599, in __connect
    connection = pool._invoke_creator(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/create.py", line 578, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 583, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.7/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) could not translate host name "postgres" to address: Temporary failure in name resolution

(Background on this error at: http://sqlalche.me/e/14/e3q8)
[2025-09-01 04:50:45,516] {subprocess.py:92} INFO - 25/09/01 04:50:45 WARN HeartbeatReceiver: Removing executor driver with no recent heartbeats: 150717 ms exceeds timeout 120000 ms
[2025-09-01 04:50:45,587] {base_job.py:229} ERROR - LocalTaskJob heartbeat got an exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 3141, in _wrap_pool_connect
    return fn()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 301, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 755, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 419, in checkout
    rec = pool._do_get()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/impl.py", line 259, in _do_get
    return self._create_connection()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 247, in _create_connection
    return _ConnectionRecord(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 362, in __init__
    self.__connect(first_connect_check=True)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 605, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 72, in __exit__
    with_traceback=exc_tb,
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 599, in __connect
    connection = pool._invoke_creator(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/create.py", line 578, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 583, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.7/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "postgres" (172.20.0.2), port 5432 failed: server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request.


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/jobs/base_job.py", line 219, in heartbeat
    session.merge(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 2877, in merge
    _resolve_conflict_map=_resolve_conflict_map,
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 2950, in _merge
    merged = self.get(mapper.class_, key[1], identity_token=key[2])
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 2702, in get
    identity_token=identity_token,
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 2800, in _get_impl
    load_options=load_options,
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/loading.py", line 535, in load_on_pk_identity
    bind_arguments=bind_arguments,
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 1669, in execute
    conn = self._connection_for_bind(bind, close_with_result=True)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 1520, in _connection_for_bind
    engine, execution_options
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 747, in _connection_for_bind
    conn = bind.connect()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 3095, in connect
    return self._connection_cls(self, close_with_result=close_with_result)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 91, in __init__
    else engine.raw_connection()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 3174, in raw_connection
    return self._wrap_pool_connect(self.pool.connect, _connection)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 3145, in _wrap_pool_connect
    e, dialect, self
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 2004, in _handle_dbapi_exception_noconnection
    sqlalchemy_exception, with_traceback=exc_info[2], from_=e
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 3141, in _wrap_pool_connect
    return fn()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 301, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 755, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 419, in checkout
    rec = pool._do_get()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/impl.py", line 259, in _do_get
    return self._create_connection()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 247, in _create_connection
    return _ConnectionRecord(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 362, in __init__
    self.__connect(first_connect_check=True)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 605, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 72, in __exit__
    with_traceback=exc_tb,
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 599, in __connect
    connection = pool._invoke_creator(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/create.py", line 578, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 583, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.7/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) connection to server at "postgres" (172.20.0.2), port 5432 failed: server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request.

(Background on this error at: http://sqlalche.me/e/14/e3q8)
[2025-09-01 04:50:45,606] {local_task_job.py:144} ERROR - Heartbeat time limit exceeded!
[2025-09-01 04:50:45,591] {subprocess.py:92} INFO - 25/09/01 04:50:45 WARN SparkContext: Killing executors is not supported by current scheduler.
[2025-09-01 04:50:45,726] {process_utils.py:129} INFO - Sending Signals.SIGTERM to group 5578. PIDs of all processes in the group: [5579, 5629, 5578]
[2025-09-01 04:50:45,728] {process_utils.py:80} INFO - Sending the signal Signals.SIGTERM to group 5578
[2025-09-01 04:50:45,728] {taskinstance.py:1541} ERROR - Received SIGTERM. Terminating subprocesses.
[2025-09-01 04:50:45,728] {subprocess.py:103} INFO - Sending SIGTERM signal to process group
[2025-09-01 04:50:45,950] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 189, in execute
    cwd=self.cwd,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/hooks/subprocess.py", line 90, in run_command
    for raw_line in iter(self.sub_process.stdout.readline, b''):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1543, in signal_handler
    raise AirflowException("Task received SIGTERM signal")
airflow.exceptions.AirflowException: Task received SIGTERM signal
[2025-09-01 04:50:46,016] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=send_weather_to_kafka, task_id=stream_hdfs, execution_date=20250901T020900, start_date=20250901T024234, end_date=20250901T045046
[2025-09-01 04:50:46,139] {standard_task_runner.py:97} ERROR - Failed to execute job 439 for task stream_hdfs (Task received SIGTERM signal; 5578)
[2025-09-01 04:50:46,179] {process_utils.py:75} INFO - Process psutil.Process(pid=5578, status='terminated', exitcode=1, started='02:42:33') (5578) terminated with exit code 1
[2025-09-01 04:50:46,180] {process_utils.py:75} INFO - Process psutil.Process(pid=5629, status='terminated', started='02:42:35') (5629) terminated with exit code None
[2025-09-01 04:50:46,972] {process_utils.py:75} INFO - Process psutil.Process(pid=5579, status='terminated', started='02:42:34') (5579) terminated with exit code None
