[2025-09-01 04:12:35,205] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: send_weather_to_kafka.stream_hdfs scheduled__2025-09-01T03:39:00.786183+00:00 [queued]>
[2025-09-01 04:12:35,211] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: send_weather_to_kafka.stream_hdfs scheduled__2025-09-01T03:39:00.786183+00:00 [queued]>
[2025-09-01 04:12:35,211] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2025-09-01 04:12:35,211] {taskinstance.py:1357} INFO - Starting attempt 1 of 2
[2025-09-01 04:12:35,211] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2025-09-01 04:12:35,219] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): stream_hdfs> on 2025-09-01 03:39:00.786183+00:00
[2025-09-01 04:12:35,222] {standard_task_runner.py:52} INFO - Started process 7153 to run task
[2025-09-01 04:12:35,224] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'send_weather_to_kafka', 'stream_hdfs', 'scheduled__2025-09-01T03:39:00.786183+00:00', '--job-id', '451', '--raw', '--subdir', 'DAGS_FOLDER/dag_meteo.py', '--cfg-path', '/tmp/tmpdbstqgzb', '--error-file', '/tmp/tmpzzph0kx2']
[2025-09-01 04:12:35,225] {standard_task_runner.py:80} INFO - Job 451: Subtask stream_hdfs
[2025-09-01 04:12:35,237] {logging_mixin.py:115} WARNING - /home/***/.local/lib/python3.7/site-packages/***/configuration.py:470 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-09-01 04:12:35,283] {task_command.py:369} INFO - Running <TaskInstance: send_weather_to_kafka.stream_hdfs scheduled__2025-09-01T03:39:00.786183+00:00 [running]> on host e66737cfc193
[2025-09-01 04:12:35,381] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=send_weather_to_kafka
AIRFLOW_CTX_TASK_ID=stream_hdfs
AIRFLOW_CTX_EXECUTION_DATE=2025-09-01T03:39:00.786183+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2025-09-01T03:39:00.786183+00:00
[2025-09-01 04:12:35,382] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2025-09-01 04:12:35,382] {subprocess.py:74} INFO - Running command: ['bash', '-c', '\n/home/***/.local/bin/spark-submit   --master local[*]   --conf spark.hadoop.fs.defaultFS=hdfs://namenode:9000   --conf spark.hadoop.dfs.client.use.datanode.hostname=true   --conf spark.sql.adaptive.enabled=false   --packages org.apache.spark:spark-sql-kafka-0-10_2.12:3.3.1   /opt/***/scripts/pyspark/streaming.py']
[2025-09-01 04:12:35,391] {subprocess.py:85} INFO - Output:
[2025-09-01 04:12:35,402] {subprocess.py:92} INFO - /opt/spark-3.3.1-bin-hadoop3/bin/load-spark-env.sh: line 68: ps: command not found
[2025-09-01 04:12:36,876] {subprocess.py:92} INFO - :: loading settings :: url = jar:file:/opt/spark-3.3.1-bin-hadoop3/jars/ivy-2.5.0.jar!/org/apache/ivy/core/settings/ivysettings.xml
[2025-09-01 04:12:36,948] {subprocess.py:92} INFO - Ivy Default Cache set to: /home/***/.ivy2/cache
[2025-09-01 04:12:36,948] {subprocess.py:92} INFO - The jars for the packages stored in: /home/***/.ivy2/jars
[2025-09-01 04:12:36,951] {subprocess.py:92} INFO - org.apache.spark#spark-sql-kafka-0-10_2.12 added as a dependency
[2025-09-01 04:12:36,952] {subprocess.py:92} INFO - :: resolving dependencies :: org.apache.spark#spark-submit-parent-de99d211-433b-4a40-8295-631907b0913c;1.0
[2025-09-01 04:12:36,952] {subprocess.py:92} INFO - 	confs: [default]
[2025-09-01 04:12:37,058] {subprocess.py:92} INFO - 	found org.apache.spark#spark-sql-kafka-0-10_2.12;3.3.1 in central
[2025-09-01 04:12:37,094] {subprocess.py:92} INFO - 	found org.apache.spark#spark-token-provider-kafka-0-10_2.12;3.3.1 in central
[2025-09-01 04:12:37,112] {subprocess.py:92} INFO - 	found org.apache.kafka#kafka-clients;2.8.1 in central
[2025-09-01 04:12:37,135] {subprocess.py:92} INFO - 	found org.lz4#lz4-java;1.8.0 in central
[2025-09-01 04:12:37,148] {subprocess.py:92} INFO - 	found org.xerial.snappy#snappy-java;1.1.8.4 in central
[2025-09-01 04:12:37,158] {subprocess.py:92} INFO - 	found org.slf4j#slf4j-api;1.7.32 in central
[2025-09-01 04:12:37,179] {subprocess.py:92} INFO - 	found org.apache.hadoop#hadoop-client-runtime;3.3.2 in central
[2025-09-01 04:12:37,188] {subprocess.py:92} INFO - 	found org.spark-project.spark#unused;1.0.0 in central
[2025-09-01 04:12:37,202] {subprocess.py:92} INFO - 	found org.apache.hadoop#hadoop-client-api;3.3.2 in central
[2025-09-01 04:12:37,215] {subprocess.py:92} INFO - 	found commons-logging#commons-logging;1.1.3 in central
[2025-09-01 04:12:37,222] {subprocess.py:92} INFO - 	found com.google.code.findbugs#jsr305;3.0.0 in central
[2025-09-01 04:12:37,229] {subprocess.py:92} INFO - 	found org.apache.commons#commons-pool2;2.11.1 in central
[2025-09-01 04:12:37,242] {subprocess.py:92} INFO - :: resolution report :: resolve 284ms :: artifacts dl 6ms
[2025-09-01 04:12:37,242] {subprocess.py:92} INFO - 	:: modules in use:
[2025-09-01 04:12:37,242] {subprocess.py:92} INFO - 	com.google.code.findbugs#jsr305;3.0.0 from central in [default]
[2025-09-01 04:12:37,242] {subprocess.py:92} INFO - 	commons-logging#commons-logging;1.1.3 from central in [default]
[2025-09-01 04:12:37,242] {subprocess.py:92} INFO - 	org.apache.commons#commons-pool2;2.11.1 from central in [default]
[2025-09-01 04:12:37,242] {subprocess.py:92} INFO - 	org.apache.hadoop#hadoop-client-api;3.3.2 from central in [default]
[2025-09-01 04:12:37,242] {subprocess.py:92} INFO - 	org.apache.hadoop#hadoop-client-runtime;3.3.2 from central in [default]
[2025-09-01 04:12:37,242] {subprocess.py:92} INFO - 	org.apache.kafka#kafka-clients;2.8.1 from central in [default]
[2025-09-01 04:12:37,242] {subprocess.py:92} INFO - 	org.apache.spark#spark-sql-kafka-0-10_2.12;3.3.1 from central in [default]
[2025-09-01 04:12:37,242] {subprocess.py:92} INFO - 	org.apache.spark#spark-token-provider-kafka-0-10_2.12;3.3.1 from central in [default]
[2025-09-01 04:12:37,242] {subprocess.py:92} INFO - 	org.lz4#lz4-java;1.8.0 from central in [default]
[2025-09-01 04:12:37,242] {subprocess.py:92} INFO - 	org.slf4j#slf4j-api;1.7.32 from central in [default]
[2025-09-01 04:12:37,242] {subprocess.py:92} INFO - 	org.spark-project.spark#unused;1.0.0 from central in [default]
[2025-09-01 04:12:37,242] {subprocess.py:92} INFO - 	org.xerial.snappy#snappy-java;1.1.8.4 from central in [default]
[2025-09-01 04:12:37,242] {subprocess.py:92} INFO - 	---------------------------------------------------------------------
[2025-09-01 04:12:37,242] {subprocess.py:92} INFO - 	|                  |            modules            ||   artifacts   |
[2025-09-01 04:12:37,242] {subprocess.py:92} INFO - 	|       conf       | number| search|dwnlded|evicted|| number|dwnlded|
[2025-09-01 04:12:37,242] {subprocess.py:92} INFO - 	---------------------------------------------------------------------
[2025-09-01 04:12:37,242] {subprocess.py:92} INFO - 	|      default     |   12  |   0   |   0   |   0   ||   12  |   0   |
[2025-09-01 04:12:37,242] {subprocess.py:92} INFO - 	---------------------------------------------------------------------
[2025-09-01 04:12:37,246] {subprocess.py:92} INFO - :: retrieving :: org.apache.spark#spark-submit-parent-de99d211-433b-4a40-8295-631907b0913c
[2025-09-01 04:12:37,246] {subprocess.py:92} INFO - 	confs: [default]
[2025-09-01 04:12:37,250] {subprocess.py:92} INFO - 	0 artifacts copied, 12 already retrieved (0kB/4ms)
[2025-09-01 04:12:37,389] {subprocess.py:92} INFO - 25/09/01 04:12:37 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
[2025-09-01 04:12:38,178] {subprocess.py:92} INFO - 25/09/01 04:12:38 INFO SparkContext: Running Spark version 3.3.1
[2025-09-01 04:12:38,197] {subprocess.py:92} INFO - 25/09/01 04:12:38 INFO ResourceUtils: ==============================================================
[2025-09-01 04:12:38,197] {subprocess.py:92} INFO - 25/09/01 04:12:38 INFO ResourceUtils: No custom resources configured for spark.driver.
[2025-09-01 04:12:38,197] {subprocess.py:92} INFO - 25/09/01 04:12:38 INFO ResourceUtils: ==============================================================
[2025-09-01 04:12:38,198] {subprocess.py:92} INFO - 25/09/01 04:12:38 INFO SparkContext: Submitted application: KafkaToHDFSWeather
[2025-09-01 04:12:38,212] {subprocess.py:92} INFO - 25/09/01 04:12:38 INFO ResourceProfile: Default ResourceProfile created, executor resources: Map(cores -> name: cores, amount: 1, script: , vendor: , memory -> name: memory, amount: 1024, script: , vendor: , offHeap -> name: offHeap, amount: 0, script: , vendor: ), task resources: Map(cpus -> name: cpus, amount: 1.0)
[2025-09-01 04:12:38,219] {subprocess.py:92} INFO - 25/09/01 04:12:38 INFO ResourceProfile: Limiting resource is cpu
[2025-09-01 04:12:38,220] {subprocess.py:92} INFO - 25/09/01 04:12:38 INFO ResourceProfileManager: Added ResourceProfile id: 0
[2025-09-01 04:12:38,260] {subprocess.py:92} INFO - 25/09/01 04:12:38 INFO SecurityManager: Changing view acls to: ***
[2025-09-01 04:12:38,261] {subprocess.py:92} INFO - 25/09/01 04:12:38 INFO SecurityManager: Changing modify acls to: ***
[2025-09-01 04:12:38,261] {subprocess.py:92} INFO - 25/09/01 04:12:38 INFO SecurityManager: Changing view acls groups to:
[2025-09-01 04:12:38,261] {subprocess.py:92} INFO - 25/09/01 04:12:38 INFO SecurityManager: Changing modify acls groups to:
[2025-09-01 04:12:38,262] {subprocess.py:92} INFO - 25/09/01 04:12:38 INFO SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users  with view permissions: Set(***); groups with view permissions: Set(); users  with modify permissions: Set(***); groups with modify permissions: Set()
[2025-09-01 04:12:38,506] {subprocess.py:92} INFO - 25/09/01 04:12:38 INFO Utils: Successfully started service 'sparkDriver' on port 44779.
[2025-09-01 04:12:38,537] {subprocess.py:92} INFO - 25/09/01 04:12:38 INFO SparkEnv: Registering MapOutputTracker
[2025-09-01 04:12:38,572] {subprocess.py:92} INFO - 25/09/01 04:12:38 INFO SparkEnv: Registering BlockManagerMaster
[2025-09-01 04:12:38,585] {subprocess.py:92} INFO - 25/09/01 04:12:38 INFO BlockManagerMasterEndpoint: Using org.apache.spark.storage.DefaultTopologyMapper for getting topology information
[2025-09-01 04:12:38,585] {subprocess.py:92} INFO - 25/09/01 04:12:38 INFO BlockManagerMasterEndpoint: BlockManagerMasterEndpoint up
[2025-09-01 04:12:38,588] {subprocess.py:92} INFO - 25/09/01 04:12:38 INFO SparkEnv: Registering BlockManagerMasterHeartbeat
[2025-09-01 04:12:38,610] {subprocess.py:92} INFO - 25/09/01 04:12:38 INFO DiskBlockManager: Created local directory at /tmp/blockmgr-e7031305-1687-4e59-a39d-23fca0e17bd9
[2025-09-01 04:12:38,626] {subprocess.py:92} INFO - 25/09/01 04:12:38 INFO MemoryStore: MemoryStore started with capacity 434.4 MiB
[2025-09-01 04:12:38,642] {subprocess.py:92} INFO - 25/09/01 04:12:38 INFO SparkEnv: Registering OutputCommitCoordinator
[2025-09-01 04:12:38,803] {subprocess.py:92} INFO - 25/09/01 04:12:38 WARN Utils: Service 'SparkUI' could not bind on port 4040. Attempting port 4041.
[2025-09-01 04:12:38,803] {subprocess.py:92} INFO - 25/09/01 04:12:38 WARN Utils: Service 'SparkUI' could not bind on port 4041. Attempting port 4042.
[2025-09-01 04:12:38,804] {subprocess.py:92} INFO - 25/09/01 04:12:38 WARN Utils: Service 'SparkUI' could not bind on port 4042. Attempting port 4043.
[2025-09-01 04:12:38,804] {subprocess.py:92} INFO - 25/09/01 04:12:38 WARN Utils: Service 'SparkUI' could not bind on port 4043. Attempting port 4044.
[2025-09-01 04:12:38,804] {subprocess.py:92} INFO - 25/09/01 04:12:38 WARN Utils: Service 'SparkUI' could not bind on port 4044. Attempting port 4045.
[2025-09-01 04:12:38,811] {subprocess.py:92} INFO - 25/09/01 04:12:38 INFO Utils: Successfully started service 'SparkUI' on port 4045.
[2025-09-01 04:12:38,835] {subprocess.py:92} INFO - 25/09/01 04:12:38 INFO SparkContext: Added JAR file:///home/***/.ivy2/jars/org.apache.spark_spark-sql-kafka-0-10_2.12-3.3.1.jar at spark://e66737cfc193:44779/jars/org.apache.spark_spark-sql-kafka-0-10_2.12-3.3.1.jar with timestamp 1756699958171
[2025-09-01 04:12:38,835] {subprocess.py:92} INFO - 25/09/01 04:12:38 INFO SparkContext: Added JAR file:///home/***/.ivy2/jars/org.apache.spark_spark-token-provider-kafka-0-10_2.12-3.3.1.jar at spark://e66737cfc193:44779/jars/org.apache.spark_spark-token-provider-kafka-0-10_2.12-3.3.1.jar with timestamp 1756699958171
[2025-09-01 04:12:38,835] {subprocess.py:92} INFO - 25/09/01 04:12:38 INFO SparkContext: Added JAR file:///home/***/.ivy2/jars/org.apache.kafka_kafka-clients-2.8.1.jar at spark://e66737cfc193:44779/jars/org.apache.kafka_kafka-clients-2.8.1.jar with timestamp 1756699958171
[2025-09-01 04:12:38,836] {subprocess.py:92} INFO - 25/09/01 04:12:38 INFO SparkContext: Added JAR file:///home/***/.ivy2/jars/com.google.code.findbugs_jsr305-3.0.0.jar at spark://e66737cfc193:44779/jars/com.google.code.findbugs_jsr305-3.0.0.jar with timestamp 1756699958171
[2025-09-01 04:12:38,836] {subprocess.py:92} INFO - 25/09/01 04:12:38 INFO SparkContext: Added JAR file:///home/***/.ivy2/jars/org.apache.commons_commons-pool2-2.11.1.jar at spark://e66737cfc193:44779/jars/org.apache.commons_commons-pool2-2.11.1.jar with timestamp 1756699958171
[2025-09-01 04:12:38,836] {subprocess.py:92} INFO - 25/09/01 04:12:38 INFO SparkContext: Added JAR file:///home/***/.ivy2/jars/org.spark-project.spark_unused-1.0.0.jar at spark://e66737cfc193:44779/jars/org.spark-project.spark_unused-1.0.0.jar with timestamp 1756699958171
[2025-09-01 04:12:38,836] {subprocess.py:92} INFO - 25/09/01 04:12:38 INFO SparkContext: Added JAR file:///home/***/.ivy2/jars/org.apache.hadoop_hadoop-client-runtime-3.3.2.jar at spark://e66737cfc193:44779/jars/org.apache.hadoop_hadoop-client-runtime-3.3.2.jar with timestamp 1756699958171
[2025-09-01 04:12:38,836] {subprocess.py:92} INFO - 25/09/01 04:12:38 INFO SparkContext: Added JAR file:///home/***/.ivy2/jars/org.lz4_lz4-java-1.8.0.jar at spark://e66737cfc193:44779/jars/org.lz4_lz4-java-1.8.0.jar with timestamp 1756699958171
[2025-09-01 04:12:38,836] {subprocess.py:92} INFO - 25/09/01 04:12:38 INFO SparkContext: Added JAR file:///home/***/.ivy2/jars/org.xerial.snappy_snappy-java-1.1.8.4.jar at spark://e66737cfc193:44779/jars/org.xerial.snappy_snappy-java-1.1.8.4.jar with timestamp 1756699958171
[2025-09-01 04:12:38,836] {subprocess.py:92} INFO - 25/09/01 04:12:38 INFO SparkContext: Added JAR file:///home/***/.ivy2/jars/org.slf4j_slf4j-api-1.7.32.jar at spark://e66737cfc193:44779/jars/org.slf4j_slf4j-api-1.7.32.jar with timestamp 1756699958171
[2025-09-01 04:12:38,836] {subprocess.py:92} INFO - 25/09/01 04:12:38 INFO SparkContext: Added JAR file:///home/***/.ivy2/jars/org.apache.hadoop_hadoop-client-api-3.3.2.jar at spark://e66737cfc193:44779/jars/org.apache.hadoop_hadoop-client-api-3.3.2.jar with timestamp 1756699958171
[2025-09-01 04:12:38,836] {subprocess.py:92} INFO - 25/09/01 04:12:38 INFO SparkContext: Added JAR file:///home/***/.ivy2/jars/commons-logging_commons-logging-1.1.3.jar at spark://e66737cfc193:44779/jars/commons-logging_commons-logging-1.1.3.jar with timestamp 1756699958171
[2025-09-01 04:12:38,838] {subprocess.py:92} INFO - 25/09/01 04:12:38 INFO SparkContext: Added file file:///home/***/.ivy2/jars/org.apache.spark_spark-sql-kafka-0-10_2.12-3.3.1.jar at file:///home/***/.ivy2/jars/org.apache.spark_spark-sql-kafka-0-10_2.12-3.3.1.jar with timestamp 1756699958171
[2025-09-01 04:12:38,839] {subprocess.py:92} INFO - 25/09/01 04:12:38 INFO Utils: Copying /home/***/.ivy2/jars/org.apache.spark_spark-sql-kafka-0-10_2.12-3.3.1.jar to /tmp/spark-06c00f26-c0b0-4adb-91ab-09fc2656b85a/userFiles-4c60f393-d5cb-4c12-9ced-58d178a9c8cf/org.apache.spark_spark-sql-kafka-0-10_2.12-3.3.1.jar
[2025-09-01 04:12:38,850] {subprocess.py:92} INFO - 25/09/01 04:12:38 INFO SparkContext: Added file file:///home/***/.ivy2/jars/org.apache.spark_spark-token-provider-kafka-0-10_2.12-3.3.1.jar at file:///home/***/.ivy2/jars/org.apache.spark_spark-token-provider-kafka-0-10_2.12-3.3.1.jar with timestamp 1756699958171
[2025-09-01 04:12:38,850] {subprocess.py:92} INFO - 25/09/01 04:12:38 INFO Utils: Copying /home/***/.ivy2/jars/org.apache.spark_spark-token-provider-kafka-0-10_2.12-3.3.1.jar to /tmp/spark-06c00f26-c0b0-4adb-91ab-09fc2656b85a/userFiles-4c60f393-d5cb-4c12-9ced-58d178a9c8cf/org.apache.spark_spark-token-provider-kafka-0-10_2.12-3.3.1.jar
[2025-09-01 04:12:38,855] {subprocess.py:92} INFO - 25/09/01 04:12:38 INFO SparkContext: Added file file:///home/***/.ivy2/jars/org.apache.kafka_kafka-clients-2.8.1.jar at file:///home/***/.ivy2/jars/org.apache.kafka_kafka-clients-2.8.1.jar with timestamp 1756699958171
[2025-09-01 04:12:38,855] {subprocess.py:92} INFO - 25/09/01 04:12:38 INFO Utils: Copying /home/***/.ivy2/jars/org.apache.kafka_kafka-clients-2.8.1.jar to /tmp/spark-06c00f26-c0b0-4adb-91ab-09fc2656b85a/userFiles-4c60f393-d5cb-4c12-9ced-58d178a9c8cf/org.apache.kafka_kafka-clients-2.8.1.jar
[2025-09-01 04:12:38,866] {subprocess.py:92} INFO - 25/09/01 04:12:38 INFO SparkContext: Added file file:///home/***/.ivy2/jars/com.google.code.findbugs_jsr305-3.0.0.jar at file:///home/***/.ivy2/jars/com.google.code.findbugs_jsr305-3.0.0.jar with timestamp 1756699958171
[2025-09-01 04:12:38,866] {subprocess.py:92} INFO - 25/09/01 04:12:38 INFO Utils: Copying /home/***/.ivy2/jars/com.google.code.findbugs_jsr305-3.0.0.jar to /tmp/spark-06c00f26-c0b0-4adb-91ab-09fc2656b85a/userFiles-4c60f393-d5cb-4c12-9ced-58d178a9c8cf/com.google.code.findbugs_jsr305-3.0.0.jar
[2025-09-01 04:12:38,870] {subprocess.py:92} INFO - 25/09/01 04:12:38 INFO SparkContext: Added file file:///home/***/.ivy2/jars/org.apache.commons_commons-pool2-2.11.1.jar at file:///home/***/.ivy2/jars/org.apache.commons_commons-pool2-2.11.1.jar with timestamp 1756699958171
[2025-09-01 04:12:38,870] {subprocess.py:92} INFO - 25/09/01 04:12:38 INFO Utils: Copying /home/***/.ivy2/jars/org.apache.commons_commons-pool2-2.11.1.jar to /tmp/spark-06c00f26-c0b0-4adb-91ab-09fc2656b85a/userFiles-4c60f393-d5cb-4c12-9ced-58d178a9c8cf/org.apache.commons_commons-pool2-2.11.1.jar
[2025-09-01 04:12:38,874] {subprocess.py:92} INFO - 25/09/01 04:12:38 INFO SparkContext: Added file file:///home/***/.ivy2/jars/org.spark-project.spark_unused-1.0.0.jar at file:///home/***/.ivy2/jars/org.spark-project.spark_unused-1.0.0.jar with timestamp 1756699958171
[2025-09-01 04:12:38,874] {subprocess.py:92} INFO - 25/09/01 04:12:38 INFO Utils: Copying /home/***/.ivy2/jars/org.spark-project.spark_unused-1.0.0.jar to /tmp/spark-06c00f26-c0b0-4adb-91ab-09fc2656b85a/userFiles-4c60f393-d5cb-4c12-9ced-58d178a9c8cf/org.spark-project.spark_unused-1.0.0.jar
[2025-09-01 04:12:38,878] {subprocess.py:92} INFO - 25/09/01 04:12:38 INFO SparkContext: Added file file:///home/***/.ivy2/jars/org.apache.hadoop_hadoop-client-runtime-3.3.2.jar at file:///home/***/.ivy2/jars/org.apache.hadoop_hadoop-client-runtime-3.3.2.jar with timestamp 1756699958171
[2025-09-01 04:12:38,878] {subprocess.py:92} INFO - 25/09/01 04:12:38 INFO Utils: Copying /home/***/.ivy2/jars/org.apache.hadoop_hadoop-client-runtime-3.3.2.jar to /tmp/spark-06c00f26-c0b0-4adb-91ab-09fc2656b85a/userFiles-4c60f393-d5cb-4c12-9ced-58d178a9c8cf/org.apache.hadoop_hadoop-client-runtime-3.3.2.jar
[2025-09-01 04:12:38,911] {subprocess.py:92} INFO - 25/09/01 04:12:38 INFO SparkContext: Added file file:///home/***/.ivy2/jars/org.lz4_lz4-java-1.8.0.jar at file:///home/***/.ivy2/jars/org.lz4_lz4-java-1.8.0.jar with timestamp 1756699958171
[2025-09-01 04:12:38,912] {subprocess.py:92} INFO - 25/09/01 04:12:38 INFO Utils: Copying /home/***/.ivy2/jars/org.lz4_lz4-java-1.8.0.jar to /tmp/spark-06c00f26-c0b0-4adb-91ab-09fc2656b85a/userFiles-4c60f393-d5cb-4c12-9ced-58d178a9c8cf/org.lz4_lz4-java-1.8.0.jar
[2025-09-01 04:12:38,916] {subprocess.py:92} INFO - 25/09/01 04:12:38 INFO SparkContext: Added file file:///home/***/.ivy2/jars/org.xerial.snappy_snappy-java-1.1.8.4.jar at file:///home/***/.ivy2/jars/org.xerial.snappy_snappy-java-1.1.8.4.jar with timestamp 1756699958171
[2025-09-01 04:12:38,917] {subprocess.py:92} INFO - 25/09/01 04:12:38 INFO Utils: Copying /home/***/.ivy2/jars/org.xerial.snappy_snappy-java-1.1.8.4.jar to /tmp/spark-06c00f26-c0b0-4adb-91ab-09fc2656b85a/userFiles-4c60f393-d5cb-4c12-9ced-58d178a9c8cf/org.xerial.snappy_snappy-java-1.1.8.4.jar
[2025-09-01 04:12:38,922] {subprocess.py:92} INFO - 25/09/01 04:12:38 INFO SparkContext: Added file file:///home/***/.ivy2/jars/org.slf4j_slf4j-api-1.7.32.jar at file:///home/***/.ivy2/jars/org.slf4j_slf4j-api-1.7.32.jar with timestamp 1756699958171
[2025-09-01 04:12:38,922] {subprocess.py:92} INFO - 25/09/01 04:12:38 INFO Utils: Copying /home/***/.ivy2/jars/org.slf4j_slf4j-api-1.7.32.jar to /tmp/spark-06c00f26-c0b0-4adb-91ab-09fc2656b85a/userFiles-4c60f393-d5cb-4c12-9ced-58d178a9c8cf/org.slf4j_slf4j-api-1.7.32.jar
[2025-09-01 04:12:38,926] {subprocess.py:92} INFO - 25/09/01 04:12:38 INFO SparkContext: Added file file:///home/***/.ivy2/jars/org.apache.hadoop_hadoop-client-api-3.3.2.jar at file:///home/***/.ivy2/jars/org.apache.hadoop_hadoop-client-api-3.3.2.jar with timestamp 1756699958171
[2025-09-01 04:12:38,926] {subprocess.py:92} INFO - 25/09/01 04:12:38 INFO Utils: Copying /home/***/.ivy2/jars/org.apache.hadoop_hadoop-client-api-3.3.2.jar to /tmp/spark-06c00f26-c0b0-4adb-91ab-09fc2656b85a/userFiles-4c60f393-d5cb-4c12-9ced-58d178a9c8cf/org.apache.hadoop_hadoop-client-api-3.3.2.jar
[2025-09-01 04:12:38,953] {subprocess.py:92} INFO - 25/09/01 04:12:38 INFO SparkContext: Added file file:///home/***/.ivy2/jars/commons-logging_commons-logging-1.1.3.jar at file:///home/***/.ivy2/jars/commons-logging_commons-logging-1.1.3.jar with timestamp 1756699958171
[2025-09-01 04:12:38,954] {subprocess.py:92} INFO - 25/09/01 04:12:38 INFO Utils: Copying /home/***/.ivy2/jars/commons-logging_commons-logging-1.1.3.jar to /tmp/spark-06c00f26-c0b0-4adb-91ab-09fc2656b85a/userFiles-4c60f393-d5cb-4c12-9ced-58d178a9c8cf/commons-logging_commons-logging-1.1.3.jar
[2025-09-01 04:12:39,002] {subprocess.py:92} INFO - 25/09/01 04:12:39 INFO Executor: Starting executor ID driver on host e66737cfc193
[2025-09-01 04:12:39,006] {subprocess.py:92} INFO - 25/09/01 04:12:39 INFO Executor: Starting executor with user classpath (userClassPathFirst = false): ''
[2025-09-01 04:12:39,014] {subprocess.py:92} INFO - 25/09/01 04:12:39 INFO Executor: Fetching file:///home/***/.ivy2/jars/commons-logging_commons-logging-1.1.3.jar with timestamp 1756699958171
[2025-09-01 04:12:39,026] {subprocess.py:92} INFO - 25/09/01 04:12:39 INFO Utils: /home/***/.ivy2/jars/commons-logging_commons-logging-1.1.3.jar has been previously copied to /tmp/spark-06c00f26-c0b0-4adb-91ab-09fc2656b85a/userFiles-4c60f393-d5cb-4c12-9ced-58d178a9c8cf/commons-logging_commons-logging-1.1.3.jar
[2025-09-01 04:12:39,029] {subprocess.py:92} INFO - 25/09/01 04:12:39 INFO Executor: Fetching file:///home/***/.ivy2/jars/org.spark-project.spark_unused-1.0.0.jar with timestamp 1756699958171
[2025-09-01 04:12:39,029] {subprocess.py:92} INFO - 25/09/01 04:12:39 INFO Utils: /home/***/.ivy2/jars/org.spark-project.spark_unused-1.0.0.jar has been previously copied to /tmp/spark-06c00f26-c0b0-4adb-91ab-09fc2656b85a/userFiles-4c60f393-d5cb-4c12-9ced-58d178a9c8cf/org.spark-project.spark_unused-1.0.0.jar
[2025-09-01 04:12:39,032] {subprocess.py:92} INFO - 25/09/01 04:12:39 INFO Executor: Fetching file:///home/***/.ivy2/jars/org.apache.spark_spark-sql-kafka-0-10_2.12-3.3.1.jar with timestamp 1756699958171
[2025-09-01 04:12:39,036] {subprocess.py:92} INFO - 25/09/01 04:12:39 INFO Utils: /home/***/.ivy2/jars/org.apache.spark_spark-sql-kafka-0-10_2.12-3.3.1.jar has been previously copied to /tmp/spark-06c00f26-c0b0-4adb-91ab-09fc2656b85a/userFiles-4c60f393-d5cb-4c12-9ced-58d178a9c8cf/org.apache.spark_spark-sql-kafka-0-10_2.12-3.3.1.jar
[2025-09-01 04:12:39,039] {subprocess.py:92} INFO - 25/09/01 04:12:39 INFO Executor: Fetching file:///home/***/.ivy2/jars/org.apache.hadoop_hadoop-client-api-3.3.2.jar with timestamp 1756699958171
[2025-09-01 04:12:39,048] {subprocess.py:92} INFO - 25/09/01 04:12:39 INFO Utils: /home/***/.ivy2/jars/org.apache.hadoop_hadoop-client-api-3.3.2.jar has been previously copied to /tmp/spark-06c00f26-c0b0-4adb-91ab-09fc2656b85a/userFiles-4c60f393-d5cb-4c12-9ced-58d178a9c8cf/org.apache.hadoop_hadoop-client-api-3.3.2.jar
[2025-09-01 04:12:39,052] {subprocess.py:92} INFO - 25/09/01 04:12:39 INFO Executor: Fetching file:///home/***/.ivy2/jars/org.apache.hadoop_hadoop-client-runtime-3.3.2.jar with timestamp 1756699958171
[2025-09-01 04:12:39,073] {subprocess.py:92} INFO - 25/09/01 04:12:39 INFO Utils: /home/***/.ivy2/jars/org.apache.hadoop_hadoop-client-runtime-3.3.2.jar has been previously copied to /tmp/spark-06c00f26-c0b0-4adb-91ab-09fc2656b85a/userFiles-4c60f393-d5cb-4c12-9ced-58d178a9c8cf/org.apache.hadoop_hadoop-client-runtime-3.3.2.jar
[2025-09-01 04:12:39,076] {subprocess.py:92} INFO - 25/09/01 04:12:39 INFO Executor: Fetching file:///home/***/.ivy2/jars/org.slf4j_slf4j-api-1.7.32.jar with timestamp 1756699958171
[2025-09-01 04:12:39,077] {subprocess.py:92} INFO - 25/09/01 04:12:39 INFO Utils: /home/***/.ivy2/jars/org.slf4j_slf4j-api-1.7.32.jar has been previously copied to /tmp/spark-06c00f26-c0b0-4adb-91ab-09fc2656b85a/userFiles-4c60f393-d5cb-4c12-9ced-58d178a9c8cf/org.slf4j_slf4j-api-1.7.32.jar
[2025-09-01 04:12:39,080] {subprocess.py:92} INFO - 25/09/01 04:12:39 INFO Executor: Fetching file:///home/***/.ivy2/jars/org.lz4_lz4-java-1.8.0.jar with timestamp 1756699958171
[2025-09-01 04:12:39,080] {subprocess.py:92} INFO - 25/09/01 04:12:39 INFO Utils: /home/***/.ivy2/jars/org.lz4_lz4-java-1.8.0.jar has been previously copied to /tmp/spark-06c00f26-c0b0-4adb-91ab-09fc2656b85a/userFiles-4c60f393-d5cb-4c12-9ced-58d178a9c8cf/org.lz4_lz4-java-1.8.0.jar
[2025-09-01 04:12:39,084] {subprocess.py:92} INFO - 25/09/01 04:12:39 INFO Executor: Fetching file:///home/***/.ivy2/jars/org.apache.commons_commons-pool2-2.11.1.jar with timestamp 1756699958171
[2025-09-01 04:12:39,085] {subprocess.py:92} INFO - 25/09/01 04:12:39 INFO Utils: /home/***/.ivy2/jars/org.apache.commons_commons-pool2-2.11.1.jar has been previously copied to /tmp/spark-06c00f26-c0b0-4adb-91ab-09fc2656b85a/userFiles-4c60f393-d5cb-4c12-9ced-58d178a9c8cf/org.apache.commons_commons-pool2-2.11.1.jar
[2025-09-01 04:12:39,088] {subprocess.py:92} INFO - 25/09/01 04:12:39 INFO Executor: Fetching file:///home/***/.ivy2/jars/com.google.code.findbugs_jsr305-3.0.0.jar with timestamp 1756699958171
[2025-09-01 04:12:39,088] {subprocess.py:92} INFO - 25/09/01 04:12:39 INFO Utils: /home/***/.ivy2/jars/com.google.code.findbugs_jsr305-3.0.0.jar has been previously copied to /tmp/spark-06c00f26-c0b0-4adb-91ab-09fc2656b85a/userFiles-4c60f393-d5cb-4c12-9ced-58d178a9c8cf/com.google.code.findbugs_jsr305-3.0.0.jar
[2025-09-01 04:12:39,092] {subprocess.py:92} INFO - 25/09/01 04:12:39 INFO Executor: Fetching file:///home/***/.ivy2/jars/org.apache.spark_spark-token-provider-kafka-0-10_2.12-3.3.1.jar with timestamp 1756699958171
[2025-09-01 04:12:39,093] {subprocess.py:92} INFO - 25/09/01 04:12:39 INFO Utils: /home/***/.ivy2/jars/org.apache.spark_spark-token-provider-kafka-0-10_2.12-3.3.1.jar has been previously copied to /tmp/spark-06c00f26-c0b0-4adb-91ab-09fc2656b85a/userFiles-4c60f393-d5cb-4c12-9ced-58d178a9c8cf/org.apache.spark_spark-token-provider-kafka-0-10_2.12-3.3.1.jar
[2025-09-01 04:12:39,097] {subprocess.py:92} INFO - 25/09/01 04:12:39 INFO Executor: Fetching file:///home/***/.ivy2/jars/org.apache.kafka_kafka-clients-2.8.1.jar with timestamp 1756699958171
[2025-09-01 04:12:39,105] {subprocess.py:92} INFO - 25/09/01 04:12:39 INFO Utils: /home/***/.ivy2/jars/org.apache.kafka_kafka-clients-2.8.1.jar has been previously copied to /tmp/spark-06c00f26-c0b0-4adb-91ab-09fc2656b85a/userFiles-4c60f393-d5cb-4c12-9ced-58d178a9c8cf/org.apache.kafka_kafka-clients-2.8.1.jar
[2025-09-01 04:12:39,110] {subprocess.py:92} INFO - 25/09/01 04:12:39 INFO Executor: Fetching file:///home/***/.ivy2/jars/org.xerial.snappy_snappy-java-1.1.8.4.jar with timestamp 1756699958171
[2025-09-01 04:12:39,112] {subprocess.py:92} INFO - 25/09/01 04:12:39 INFO Utils: /home/***/.ivy2/jars/org.xerial.snappy_snappy-java-1.1.8.4.jar has been previously copied to /tmp/spark-06c00f26-c0b0-4adb-91ab-09fc2656b85a/userFiles-4c60f393-d5cb-4c12-9ced-58d178a9c8cf/org.xerial.snappy_snappy-java-1.1.8.4.jar
[2025-09-01 04:12:39,118] {subprocess.py:92} INFO - 25/09/01 04:12:39 INFO Executor: Fetching spark://e66737cfc193:44779/jars/org.apache.spark_spark-sql-kafka-0-10_2.12-3.3.1.jar with timestamp 1756699958171
[2025-09-01 04:12:39,162] {subprocess.py:92} INFO - 25/09/01 04:12:39 INFO TransportClientFactory: Successfully created connection to e66737cfc193/172.20.0.18:44779 after 32 ms (0 ms spent in bootstraps)
[2025-09-01 04:12:39,166] {subprocess.py:92} INFO - 25/09/01 04:12:39 INFO Utils: Fetching spark://e66737cfc193:44779/jars/org.apache.spark_spark-sql-kafka-0-10_2.12-3.3.1.jar to /tmp/spark-06c00f26-c0b0-4adb-91ab-09fc2656b85a/userFiles-4c60f393-d5cb-4c12-9ced-58d178a9c8cf/fetchFileTemp12883152921748648841.tmp
[2025-09-01 04:12:39,189] {subprocess.py:92} INFO - 25/09/01 04:12:39 INFO Utils: /tmp/spark-06c00f26-c0b0-4adb-91ab-09fc2656b85a/userFiles-4c60f393-d5cb-4c12-9ced-58d178a9c8cf/fetchFileTemp12883152921748648841.tmp has been previously copied to /tmp/spark-06c00f26-c0b0-4adb-91ab-09fc2656b85a/userFiles-4c60f393-d5cb-4c12-9ced-58d178a9c8cf/org.apache.spark_spark-sql-kafka-0-10_2.12-3.3.1.jar
[2025-09-01 04:12:39,193] {subprocess.py:92} INFO - 25/09/01 04:12:39 INFO Executor: Adding file:/tmp/spark-06c00f26-c0b0-4adb-91ab-09fc2656b85a/userFiles-4c60f393-d5cb-4c12-9ced-58d178a9c8cf/org.apache.spark_spark-sql-kafka-0-10_2.12-3.3.1.jar to class loader
[2025-09-01 04:12:39,193] {subprocess.py:92} INFO - 25/09/01 04:12:39 INFO Executor: Fetching spark://e66737cfc193:44779/jars/org.xerial.snappy_snappy-java-1.1.8.4.jar with timestamp 1756699958171
[2025-09-01 04:12:39,194] {subprocess.py:92} INFO - 25/09/01 04:12:39 INFO Utils: Fetching spark://e66737cfc193:44779/jars/org.xerial.snappy_snappy-java-1.1.8.4.jar to /tmp/spark-06c00f26-c0b0-4adb-91ab-09fc2656b85a/userFiles-4c60f393-d5cb-4c12-9ced-58d178a9c8cf/fetchFileTemp17388422621767528850.tmp
[2025-09-01 04:12:39,203] {subprocess.py:92} INFO - 25/09/01 04:12:39 INFO Utils: /tmp/spark-06c00f26-c0b0-4adb-91ab-09fc2656b85a/userFiles-4c60f393-d5cb-4c12-9ced-58d178a9c8cf/fetchFileTemp17388422621767528850.tmp has been previously copied to /tmp/spark-06c00f26-c0b0-4adb-91ab-09fc2656b85a/userFiles-4c60f393-d5cb-4c12-9ced-58d178a9c8cf/org.xerial.snappy_snappy-java-1.1.8.4.jar
[2025-09-01 04:12:39,210] {subprocess.py:92} INFO - 25/09/01 04:12:39 INFO Executor: Adding file:/tmp/spark-06c00f26-c0b0-4adb-91ab-09fc2656b85a/userFiles-4c60f393-d5cb-4c12-9ced-58d178a9c8cf/org.xerial.snappy_snappy-java-1.1.8.4.jar to class loader
[2025-09-01 04:12:39,210] {subprocess.py:92} INFO - 25/09/01 04:12:39 INFO Executor: Fetching spark://e66737cfc193:44779/jars/org.apache.commons_commons-pool2-2.11.1.jar with timestamp 1756699958171
[2025-09-01 04:12:39,210] {subprocess.py:92} INFO - 25/09/01 04:12:39 INFO Utils: Fetching spark://e66737cfc193:44779/jars/org.apache.commons_commons-pool2-2.11.1.jar to /tmp/spark-06c00f26-c0b0-4adb-91ab-09fc2656b85a/userFiles-4c60f393-d5cb-4c12-9ced-58d178a9c8cf/fetchFileTemp7479132951243662907.tmp
[2025-09-01 04:12:39,213] {subprocess.py:92} INFO - 25/09/01 04:12:39 INFO Utils: /tmp/spark-06c00f26-c0b0-4adb-91ab-09fc2656b85a/userFiles-4c60f393-d5cb-4c12-9ced-58d178a9c8cf/fetchFileTemp7479132951243662907.tmp has been previously copied to /tmp/spark-06c00f26-c0b0-4adb-91ab-09fc2656b85a/userFiles-4c60f393-d5cb-4c12-9ced-58d178a9c8cf/org.apache.commons_commons-pool2-2.11.1.jar
[2025-09-01 04:12:39,218] {subprocess.py:92} INFO - 25/09/01 04:12:39 INFO Executor: Adding file:/tmp/spark-06c00f26-c0b0-4adb-91ab-09fc2656b85a/userFiles-4c60f393-d5cb-4c12-9ced-58d178a9c8cf/org.apache.commons_commons-pool2-2.11.1.jar to class loader
[2025-09-01 04:12:39,218] {subprocess.py:92} INFO - 25/09/01 04:12:39 INFO Executor: Fetching spark://e66737cfc193:44779/jars/commons-logging_commons-logging-1.1.3.jar with timestamp 1756699958171
[2025-09-01 04:12:39,219] {subprocess.py:92} INFO - 25/09/01 04:12:39 INFO Utils: Fetching spark://e66737cfc193:44779/jars/commons-logging_commons-logging-1.1.3.jar to /tmp/spark-06c00f26-c0b0-4adb-91ab-09fc2656b85a/userFiles-4c60f393-d5cb-4c12-9ced-58d178a9c8cf/fetchFileTemp11163494704331009941.tmp
[2025-09-01 04:12:39,221] {subprocess.py:92} INFO - 25/09/01 04:12:39 INFO Utils: /tmp/spark-06c00f26-c0b0-4adb-91ab-09fc2656b85a/userFiles-4c60f393-d5cb-4c12-9ced-58d178a9c8cf/fetchFileTemp11163494704331009941.tmp has been previously copied to /tmp/spark-06c00f26-c0b0-4adb-91ab-09fc2656b85a/userFiles-4c60f393-d5cb-4c12-9ced-58d178a9c8cf/commons-logging_commons-logging-1.1.3.jar
[2025-09-01 04:12:39,226] {subprocess.py:92} INFO - 25/09/01 04:12:39 INFO Executor: Adding file:/tmp/spark-06c00f26-c0b0-4adb-91ab-09fc2656b85a/userFiles-4c60f393-d5cb-4c12-9ced-58d178a9c8cf/commons-logging_commons-logging-1.1.3.jar to class loader
[2025-09-01 04:12:39,226] {subprocess.py:92} INFO - 25/09/01 04:12:39 INFO Executor: Fetching spark://e66737cfc193:44779/jars/org.spark-project.spark_unused-1.0.0.jar with timestamp 1756699958171
[2025-09-01 04:12:39,227] {subprocess.py:92} INFO - 25/09/01 04:12:39 INFO Utils: Fetching spark://e66737cfc193:44779/jars/org.spark-project.spark_unused-1.0.0.jar to /tmp/spark-06c00f26-c0b0-4adb-91ab-09fc2656b85a/userFiles-4c60f393-d5cb-4c12-9ced-58d178a9c8cf/fetchFileTemp11397520799822353117.tmp
[2025-09-01 04:12:39,229] {subprocess.py:92} INFO - 25/09/01 04:12:39 INFO Utils: /tmp/spark-06c00f26-c0b0-4adb-91ab-09fc2656b85a/userFiles-4c60f393-d5cb-4c12-9ced-58d178a9c8cf/fetchFileTemp11397520799822353117.tmp has been previously copied to /tmp/spark-06c00f26-c0b0-4adb-91ab-09fc2656b85a/userFiles-4c60f393-d5cb-4c12-9ced-58d178a9c8cf/org.spark-project.spark_unused-1.0.0.jar
[2025-09-01 04:12:39,235] {subprocess.py:92} INFO - 25/09/01 04:12:39 INFO Executor: Adding file:/tmp/spark-06c00f26-c0b0-4adb-91ab-09fc2656b85a/userFiles-4c60f393-d5cb-4c12-9ced-58d178a9c8cf/org.spark-project.spark_unused-1.0.0.jar to class loader
[2025-09-01 04:12:39,235] {subprocess.py:92} INFO - 25/09/01 04:12:39 INFO Executor: Fetching spark://e66737cfc193:44779/jars/org.slf4j_slf4j-api-1.7.32.jar with timestamp 1756699958171
[2025-09-01 04:12:39,236] {subprocess.py:92} INFO - 25/09/01 04:12:39 INFO Utils: Fetching spark://e66737cfc193:44779/jars/org.slf4j_slf4j-api-1.7.32.jar to /tmp/spark-06c00f26-c0b0-4adb-91ab-09fc2656b85a/userFiles-4c60f393-d5cb-4c12-9ced-58d178a9c8cf/fetchFileTemp12019848474807069675.tmp
[2025-09-01 04:12:39,239] {subprocess.py:92} INFO - 25/09/01 04:12:39 INFO Utils: /tmp/spark-06c00f26-c0b0-4adb-91ab-09fc2656b85a/userFiles-4c60f393-d5cb-4c12-9ced-58d178a9c8cf/fetchFileTemp12019848474807069675.tmp has been previously copied to /tmp/spark-06c00f26-c0b0-4adb-91ab-09fc2656b85a/userFiles-4c60f393-d5cb-4c12-9ced-58d178a9c8cf/org.slf4j_slf4j-api-1.7.32.jar
[2025-09-01 04:12:39,243] {subprocess.py:92} INFO - 25/09/01 04:12:39 INFO Executor: Adding file:/tmp/spark-06c00f26-c0b0-4adb-91ab-09fc2656b85a/userFiles-4c60f393-d5cb-4c12-9ced-58d178a9c8cf/org.slf4j_slf4j-api-1.7.32.jar to class loader
[2025-09-01 04:12:39,244] {subprocess.py:92} INFO - 25/09/01 04:12:39 INFO Executor: Fetching spark://e66737cfc193:44779/jars/org.apache.spark_spark-token-provider-kafka-0-10_2.12-3.3.1.jar with timestamp 1756699958171
[2025-09-01 04:12:39,244] {subprocess.py:92} INFO - 25/09/01 04:12:39 INFO Utils: Fetching spark://e66737cfc193:44779/jars/org.apache.spark_spark-token-provider-kafka-0-10_2.12-3.3.1.jar to /tmp/spark-06c00f26-c0b0-4adb-91ab-09fc2656b85a/userFiles-4c60f393-d5cb-4c12-9ced-58d178a9c8cf/fetchFileTemp14821770069099189942.tmp
[2025-09-01 04:12:39,246] {subprocess.py:92} INFO - 25/09/01 04:12:39 INFO Utils: /tmp/spark-06c00f26-c0b0-4adb-91ab-09fc2656b85a/userFiles-4c60f393-d5cb-4c12-9ced-58d178a9c8cf/fetchFileTemp14821770069099189942.tmp has been previously copied to /tmp/spark-06c00f26-c0b0-4adb-91ab-09fc2656b85a/userFiles-4c60f393-d5cb-4c12-9ced-58d178a9c8cf/org.apache.spark_spark-token-provider-kafka-0-10_2.12-3.3.1.jar
[2025-09-01 04:12:39,249] {subprocess.py:92} INFO - 25/09/01 04:12:39 INFO Executor: Adding file:/tmp/spark-06c00f26-c0b0-4adb-91ab-09fc2656b85a/userFiles-4c60f393-d5cb-4c12-9ced-58d178a9c8cf/org.apache.spark_spark-token-provider-kafka-0-10_2.12-3.3.1.jar to class loader
[2025-09-01 04:12:39,249] {subprocess.py:92} INFO - 25/09/01 04:12:39 INFO Executor: Fetching spark://e66737cfc193:44779/jars/org.apache.hadoop_hadoop-client-runtime-3.3.2.jar with timestamp 1756699958171
[2025-09-01 04:12:39,250] {subprocess.py:92} INFO - 25/09/01 04:12:39 INFO Utils: Fetching spark://e66737cfc193:44779/jars/org.apache.hadoop_hadoop-client-runtime-3.3.2.jar to /tmp/spark-06c00f26-c0b0-4adb-91ab-09fc2656b85a/userFiles-4c60f393-d5cb-4c12-9ced-58d178a9c8cf/fetchFileTemp12097533316922765719.tmp
[2025-09-01 04:12:39,371] {subprocess.py:92} INFO - 25/09/01 04:12:39 INFO Utils: /tmp/spark-06c00f26-c0b0-4adb-91ab-09fc2656b85a/userFiles-4c60f393-d5cb-4c12-9ced-58d178a9c8cf/fetchFileTemp12097533316922765719.tmp has been previously copied to /tmp/spark-06c00f26-c0b0-4adb-91ab-09fc2656b85a/userFiles-4c60f393-d5cb-4c12-9ced-58d178a9c8cf/org.apache.hadoop_hadoop-client-runtime-3.3.2.jar
[2025-09-01 04:12:39,377] {subprocess.py:92} INFO - 25/09/01 04:12:39 INFO Executor: Adding file:/tmp/spark-06c00f26-c0b0-4adb-91ab-09fc2656b85a/userFiles-4c60f393-d5cb-4c12-9ced-58d178a9c8cf/org.apache.hadoop_hadoop-client-runtime-3.3.2.jar to class loader
[2025-09-01 04:12:39,377] {subprocess.py:92} INFO - 25/09/01 04:12:39 INFO Executor: Fetching spark://e66737cfc193:44779/jars/org.apache.hadoop_hadoop-client-api-3.3.2.jar with timestamp 1756699958171
[2025-09-01 04:12:39,377] {subprocess.py:92} INFO - 25/09/01 04:12:39 INFO Utils: Fetching spark://e66737cfc193:44779/jars/org.apache.hadoop_hadoop-client-api-3.3.2.jar to /tmp/spark-06c00f26-c0b0-4adb-91ab-09fc2656b85a/userFiles-4c60f393-d5cb-4c12-9ced-58d178a9c8cf/fetchFileTemp7953330673928290447.tmp
[2025-09-01 04:12:39,420] {subprocess.py:92} INFO - 25/09/01 04:12:39 INFO Utils: /tmp/spark-06c00f26-c0b0-4adb-91ab-09fc2656b85a/userFiles-4c60f393-d5cb-4c12-9ced-58d178a9c8cf/fetchFileTemp7953330673928290447.tmp has been previously copied to /tmp/spark-06c00f26-c0b0-4adb-91ab-09fc2656b85a/userFiles-4c60f393-d5cb-4c12-9ced-58d178a9c8cf/org.apache.hadoop_hadoop-client-api-3.3.2.jar
[2025-09-01 04:12:39,425] {subprocess.py:92} INFO - 25/09/01 04:12:39 INFO Executor: Adding file:/tmp/spark-06c00f26-c0b0-4adb-91ab-09fc2656b85a/userFiles-4c60f393-d5cb-4c12-9ced-58d178a9c8cf/org.apache.hadoop_hadoop-client-api-3.3.2.jar to class loader
[2025-09-01 04:12:39,425] {subprocess.py:92} INFO - 25/09/01 04:12:39 INFO Executor: Fetching spark://e66737cfc193:44779/jars/org.apache.kafka_kafka-clients-2.8.1.jar with timestamp 1756699958171
[2025-09-01 04:12:39,425] {subprocess.py:92} INFO - 25/09/01 04:12:39 INFO Utils: Fetching spark://e66737cfc193:44779/jars/org.apache.kafka_kafka-clients-2.8.1.jar to /tmp/spark-06c00f26-c0b0-4adb-91ab-09fc2656b85a/userFiles-4c60f393-d5cb-4c12-9ced-58d178a9c8cf/fetchFileTemp4876313098842201623.tmp
[2025-09-01 04:12:39,441] {subprocess.py:92} INFO - 25/09/01 04:12:39 INFO Utils: /tmp/spark-06c00f26-c0b0-4adb-91ab-09fc2656b85a/userFiles-4c60f393-d5cb-4c12-9ced-58d178a9c8cf/fetchFileTemp4876313098842201623.tmp has been previously copied to /tmp/spark-06c00f26-c0b0-4adb-91ab-09fc2656b85a/userFiles-4c60f393-d5cb-4c12-9ced-58d178a9c8cf/org.apache.kafka_kafka-clients-2.8.1.jar
[2025-09-01 04:12:39,445] {subprocess.py:92} INFO - 25/09/01 04:12:39 INFO Executor: Adding file:/tmp/spark-06c00f26-c0b0-4adb-91ab-09fc2656b85a/userFiles-4c60f393-d5cb-4c12-9ced-58d178a9c8cf/org.apache.kafka_kafka-clients-2.8.1.jar to class loader
[2025-09-01 04:12:39,445] {subprocess.py:92} INFO - 25/09/01 04:12:39 INFO Executor: Fetching spark://e66737cfc193:44779/jars/com.google.code.findbugs_jsr305-3.0.0.jar with timestamp 1756699958171
[2025-09-01 04:12:39,446] {subprocess.py:92} INFO - 25/09/01 04:12:39 INFO Utils: Fetching spark://e66737cfc193:44779/jars/com.google.code.findbugs_jsr305-3.0.0.jar to /tmp/spark-06c00f26-c0b0-4adb-91ab-09fc2656b85a/userFiles-4c60f393-d5cb-4c12-9ced-58d178a9c8cf/fetchFileTemp5009083929886895703.tmp
[2025-09-01 04:12:39,447] {subprocess.py:92} INFO - 25/09/01 04:12:39 INFO Utils: /tmp/spark-06c00f26-c0b0-4adb-91ab-09fc2656b85a/userFiles-4c60f393-d5cb-4c12-9ced-58d178a9c8cf/fetchFileTemp5009083929886895703.tmp has been previously copied to /tmp/spark-06c00f26-c0b0-4adb-91ab-09fc2656b85a/userFiles-4c60f393-d5cb-4c12-9ced-58d178a9c8cf/com.google.code.findbugs_jsr305-3.0.0.jar
[2025-09-01 04:12:39,450] {subprocess.py:92} INFO - 25/09/01 04:12:39 INFO Executor: Adding file:/tmp/spark-06c00f26-c0b0-4adb-91ab-09fc2656b85a/userFiles-4c60f393-d5cb-4c12-9ced-58d178a9c8cf/com.google.code.findbugs_jsr305-3.0.0.jar to class loader
[2025-09-01 04:12:39,451] {subprocess.py:92} INFO - 25/09/01 04:12:39 INFO Executor: Fetching spark://e66737cfc193:44779/jars/org.lz4_lz4-java-1.8.0.jar with timestamp 1756699958171
[2025-09-01 04:12:39,451] {subprocess.py:92} INFO - 25/09/01 04:12:39 INFO Utils: Fetching spark://e66737cfc193:44779/jars/org.lz4_lz4-java-1.8.0.jar to /tmp/spark-06c00f26-c0b0-4adb-91ab-09fc2656b85a/userFiles-4c60f393-d5cb-4c12-9ced-58d178a9c8cf/fetchFileTemp1364652650756126814.tmp
[2025-09-01 04:12:39,454] {subprocess.py:92} INFO - 25/09/01 04:12:39 INFO Utils: /tmp/spark-06c00f26-c0b0-4adb-91ab-09fc2656b85a/userFiles-4c60f393-d5cb-4c12-9ced-58d178a9c8cf/fetchFileTemp1364652650756126814.tmp has been previously copied to /tmp/spark-06c00f26-c0b0-4adb-91ab-09fc2656b85a/userFiles-4c60f393-d5cb-4c12-9ced-58d178a9c8cf/org.lz4_lz4-java-1.8.0.jar
[2025-09-01 04:12:39,458] {subprocess.py:92} INFO - 25/09/01 04:12:39 INFO Executor: Adding file:/tmp/spark-06c00f26-c0b0-4adb-91ab-09fc2656b85a/userFiles-4c60f393-d5cb-4c12-9ced-58d178a9c8cf/org.lz4_lz4-java-1.8.0.jar to class loader
[2025-09-01 04:12:39,465] {subprocess.py:92} INFO - 25/09/01 04:12:39 INFO Utils: Successfully started service 'org.apache.spark.network.netty.NettyBlockTransferService' on port 44087.
[2025-09-01 04:12:39,465] {subprocess.py:92} INFO - 25/09/01 04:12:39 INFO NettyBlockTransferService: Server created on e66737cfc193:44087
[2025-09-01 04:12:39,466] {subprocess.py:92} INFO - 25/09/01 04:12:39 INFO BlockManager: Using org.apache.spark.storage.RandomBlockReplicationPolicy for block replication policy
[2025-09-01 04:12:39,471] {subprocess.py:92} INFO - 25/09/01 04:12:39 INFO BlockManagerMaster: Registering BlockManager BlockManagerId(driver, e66737cfc193, 44087, None)
[2025-09-01 04:12:39,475] {subprocess.py:92} INFO - 25/09/01 04:12:39 INFO BlockManagerMasterEndpoint: Registering block manager e66737cfc193:44087 with 434.4 MiB RAM, BlockManagerId(driver, e66737cfc193, 44087, None)
[2025-09-01 04:12:39,477] {subprocess.py:92} INFO - 25/09/01 04:12:39 INFO BlockManagerMaster: Registered BlockManager BlockManagerId(driver, e66737cfc193, 44087, None)
[2025-09-01 04:12:39,478] {subprocess.py:92} INFO - 25/09/01 04:12:39 INFO BlockManager: Initialized BlockManager: BlockManagerId(driver, e66737cfc193, 44087, None)
[2025-09-01 04:12:39,746] {subprocess.py:92} INFO - Connexion à Kafka...
[2025-09-01 04:12:41,147] {subprocess.py:92} INFO - Connexion Kafka réussie (kafka:9092)
[2025-09-01 04:12:41,147] {subprocess.py:92} INFO - Transformation des données JSON...
[2025-09-01 04:12:41,344] {subprocess.py:92} INFO - Démarrage du streaming vers HDFS...
[2025-09-01 04:12:41,910] {subprocess.py:92} INFO - Streaming actif - Données météo sauvegardées dans HDFS:/data/weather
[2025-09-01 04:44:18,903] {base_job.py:229} ERROR - LocalTaskJob heartbeat got an exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 3141, in _wrap_pool_connect
    return fn()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 301, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 755, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 419, in checkout
    rec = pool._do_get()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/impl.py", line 259, in _do_get
    return self._create_connection()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 247, in _create_connection
    return _ConnectionRecord(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 362, in __init__
    self.__connect(first_connect_check=True)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 605, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 72, in __exit__
    with_traceback=exc_tb,
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 599, in __connect
    connection = pool._invoke_creator(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/create.py", line 578, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 583, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.7/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: could not translate host name "postgres" to address: Temporary failure in name resolution


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/jobs/base_job.py", line 219, in heartbeat
    session.merge(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 2877, in merge
    _resolve_conflict_map=_resolve_conflict_map,
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 2950, in _merge
    merged = self.get(mapper.class_, key[1], identity_token=key[2])
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 2702, in get
    identity_token=identity_token,
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 2800, in _get_impl
    load_options=load_options,
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/loading.py", line 535, in load_on_pk_identity
    bind_arguments=bind_arguments,
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 1669, in execute
    conn = self._connection_for_bind(bind, close_with_result=True)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 1520, in _connection_for_bind
    engine, execution_options
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 747, in _connection_for_bind
    conn = bind.connect()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 3095, in connect
    return self._connection_cls(self, close_with_result=close_with_result)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 91, in __init__
    else engine.raw_connection()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 3174, in raw_connection
    return self._wrap_pool_connect(self.pool.connect, _connection)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 3145, in _wrap_pool_connect
    e, dialect, self
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 2004, in _handle_dbapi_exception_noconnection
    sqlalchemy_exception, with_traceback=exc_info[2], from_=e
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 3141, in _wrap_pool_connect
    return fn()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 301, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 755, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 419, in checkout
    rec = pool._do_get()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/impl.py", line 259, in _do_get
    return self._create_connection()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 247, in _create_connection
    return _ConnectionRecord(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 362, in __init__
    self.__connect(first_connect_check=True)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 605, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 72, in __exit__
    with_traceback=exc_tb,
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 599, in __connect
    connection = pool._invoke_creator(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/create.py", line 578, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 583, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.7/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) could not translate host name "postgres" to address: Temporary failure in name resolution

(Background on this error at: http://sqlalche.me/e/14/e3q8)
[2025-09-01 04:47:47,754] {base_job.py:229} ERROR - LocalTaskJob heartbeat got an exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 3141, in _wrap_pool_connect
    return fn()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 301, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 755, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 419, in checkout
    rec = pool._do_get()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/impl.py", line 259, in _do_get
    return self._create_connection()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 247, in _create_connection
    return _ConnectionRecord(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 362, in __init__
    self.__connect(first_connect_check=True)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 605, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 72, in __exit__
    with_traceback=exc_tb,
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 599, in __connect
    connection = pool._invoke_creator(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/create.py", line 578, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 583, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.7/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: could not translate host name "postgres" to address: Temporary failure in name resolution


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/jobs/base_job.py", line 201, in heartbeat
    session.merge(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 2877, in merge
    _resolve_conflict_map=_resolve_conflict_map,
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 2950, in _merge
    merged = self.get(mapper.class_, key[1], identity_token=key[2])
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 2702, in get
    identity_token=identity_token,
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 2800, in _get_impl
    load_options=load_options,
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/loading.py", line 535, in load_on_pk_identity
    bind_arguments=bind_arguments,
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 1669, in execute
    conn = self._connection_for_bind(bind, close_with_result=True)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 1520, in _connection_for_bind
    engine, execution_options
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 747, in _connection_for_bind
    conn = bind.connect()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 3095, in connect
    return self._connection_cls(self, close_with_result=close_with_result)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 91, in __init__
    else engine.raw_connection()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 3174, in raw_connection
    return self._wrap_pool_connect(self.pool.connect, _connection)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 3145, in _wrap_pool_connect
    e, dialect, self
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 2004, in _handle_dbapi_exception_noconnection
    sqlalchemy_exception, with_traceback=exc_info[2], from_=e
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 3141, in _wrap_pool_connect
    return fn()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 301, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 755, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 419, in checkout
    rec = pool._do_get()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/impl.py", line 259, in _do_get
    return self._create_connection()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 247, in _create_connection
    return _ConnectionRecord(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 362, in __init__
    self.__connect(first_connect_check=True)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 605, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 72, in __exit__
    with_traceback=exc_tb,
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 599, in __connect
    connection = pool._invoke_creator(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/create.py", line 578, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 583, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.7/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) could not translate host name "postgres" to address: Temporary failure in name resolution

(Background on this error at: http://sqlalche.me/e/14/e3q8)
[2025-09-01 04:50:45,414] {base_job.py:229} ERROR - LocalTaskJob heartbeat got an exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 3141, in _wrap_pool_connect
    return fn()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 301, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 755, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 419, in checkout
    rec = pool._do_get()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/impl.py", line 259, in _do_get
    return self._create_connection()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 247, in _create_connection
    return _ConnectionRecord(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 362, in __init__
    self.__connect(first_connect_check=True)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 605, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 72, in __exit__
    with_traceback=exc_tb,
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 599, in __connect
    connection = pool._invoke_creator(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/create.py", line 578, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 583, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.7/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: could not translate host name "postgres" to address: Temporary failure in name resolution


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/jobs/base_job.py", line 201, in heartbeat
    session.merge(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 2877, in merge
    _resolve_conflict_map=_resolve_conflict_map,
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 2950, in _merge
    merged = self.get(mapper.class_, key[1], identity_token=key[2])
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 2702, in get
    identity_token=identity_token,
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 2800, in _get_impl
    load_options=load_options,
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/loading.py", line 535, in load_on_pk_identity
    bind_arguments=bind_arguments,
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 1669, in execute
    conn = self._connection_for_bind(bind, close_with_result=True)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 1520, in _connection_for_bind
    engine, execution_options
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 747, in _connection_for_bind
    conn = bind.connect()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 3095, in connect
    return self._connection_cls(self, close_with_result=close_with_result)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 91, in __init__
    else engine.raw_connection()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 3174, in raw_connection
    return self._wrap_pool_connect(self.pool.connect, _connection)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 3145, in _wrap_pool_connect
    e, dialect, self
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 2004, in _handle_dbapi_exception_noconnection
    sqlalchemy_exception, with_traceback=exc_info[2], from_=e
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 3141, in _wrap_pool_connect
    return fn()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 301, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 755, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 419, in checkout
    rec = pool._do_get()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/impl.py", line 259, in _do_get
    return self._create_connection()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 247, in _create_connection
    return _ConnectionRecord(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 362, in __init__
    self.__connect(first_connect_check=True)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 605, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 72, in __exit__
    with_traceback=exc_tb,
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 599, in __connect
    connection = pool._invoke_creator(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/create.py", line 578, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 583, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.7/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) could not translate host name "postgres" to address: Temporary failure in name resolution

(Background on this error at: http://sqlalche.me/e/14/e3q8)
[2025-09-01 04:50:45,721] {subprocess.py:92} INFO - 25/09/01 04:50:45 WARN HeartbeatReceiver: Removing executor driver with no recent heartbeats: 148367 ms exceeds timeout 120000 ms
[2025-09-01 04:50:45,735] {subprocess.py:92} INFO - 25/09/01 04:50:45 WARN Executor: Issue communicating with driver in heartbeater
[2025-09-01 04:50:45,736] {subprocess.py:92} INFO - org.apache.spark.rpc.RpcTimeoutException: Futures timed out after [10000 milliseconds]. This timeout is controlled by spark.executor.heartbeatInterval
[2025-09-01 04:50:45,736] {subprocess.py:92} INFO - 	at org.apache.spark.rpc.RpcTimeout.org$apache$spark$rpc$RpcTimeout$$createRpcTimeoutException(RpcTimeout.scala:47)
[2025-09-01 04:50:45,736] {subprocess.py:92} INFO - 	at org.apache.spark.rpc.RpcTimeout$$anonfun$addMessageIfTimeout$1.applyOrElse(RpcTimeout.scala:62)
[2025-09-01 04:50:45,736] {subprocess.py:92} INFO - 	at org.apache.spark.rpc.RpcTimeout$$anonfun$addMessageIfTimeout$1.applyOrElse(RpcTimeout.scala:58)
[2025-09-01 04:50:45,736] {subprocess.py:92} INFO - 	at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:38)
[2025-09-01 04:50:45,736] {subprocess.py:92} INFO - 	at org.apache.spark.rpc.RpcTimeout.awaitResult(RpcTimeout.scala:76)
[2025-09-01 04:50:45,736] {subprocess.py:92} INFO - 	at org.apache.spark.rpc.RpcEndpointRef.askSync(RpcEndpointRef.scala:103)
[2025-09-01 04:50:45,736] {subprocess.py:92} INFO - 	at org.apache.spark.executor.Executor.reportHeartBeat(Executor.scala:1053)
[2025-09-01 04:50:45,736] {subprocess.py:92} INFO - 	at org.apache.spark.executor.Executor.$anonfun$heartbeater$1(Executor.scala:238)
[2025-09-01 04:50:45,736] {subprocess.py:92} INFO - 	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
[2025-09-01 04:50:45,737] {subprocess.py:92} INFO - 	at org.apache.spark.util.Utils$.logUncaughtExceptions(Utils.scala:2066)
[2025-09-01 04:50:45,737] {subprocess.py:92} INFO - 	at org.apache.spark.Heartbeater$$anon$1.run(Heartbeater.scala:46)
[2025-09-01 04:50:45,737] {subprocess.py:92} INFO - 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[2025-09-01 04:50:45,737] {subprocess.py:92} INFO - 	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
[2025-09-01 04:50:45,737] {subprocess.py:92} INFO - 	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
[2025-09-01 04:50:45,737] {subprocess.py:92} INFO - 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[2025-09-01 04:50:45,737] {subprocess.py:92} INFO - 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[2025-09-01 04:50:45,737] {subprocess.py:92} INFO - 	at java.base/java.lang.Thread.run(Thread.java:829)
[2025-09-01 04:50:45,737] {subprocess.py:92} INFO - Caused by: java.util.concurrent.TimeoutException: Futures timed out after [10000 milliseconds]
[2025-09-01 04:50:45,737] {subprocess.py:92} INFO - 	at scala.concurrent.impl.Promise$DefaultPromise.ready(Promise.scala:259)
[2025-09-01 04:50:45,737] {subprocess.py:92} INFO - 	at scala.concurrent.impl.Promise$DefaultPromise.result(Promise.scala:263)
[2025-09-01 04:50:45,737] {subprocess.py:92} INFO - 	at org.apache.spark.util.ThreadUtils$.awaitResult(ThreadUtils.scala:293)
[2025-09-01 04:50:45,738] {subprocess.py:92} INFO - 	at org.apache.spark.rpc.RpcTimeout.awaitResult(RpcTimeout.scala:75)
[2025-09-01 04:50:45,738] {subprocess.py:92} INFO - 	... 12 more
[2025-09-01 04:50:45,823] {subprocess.py:92} INFO - 25/09/01 04:50:45 WARN SparkContext: Killing executors is not supported by current scheduler.
[2025-09-01 04:50:45,824] {subprocess.py:92} INFO - 25/09/01 04:50:45 WARN NettyRpcEnv: Ignored message: HeartbeatResponse(true)
[2025-09-01 04:50:45,825] {subprocess.py:92} INFO - 25/09/01 04:50:45 WARN KafkaOffsetReaderConsumer: Error in attempt 1 getting Kafka offsets:
[2025-09-01 04:50:45,825] {subprocess.py:92} INFO - org.apache.kafka.common.errors.TimeoutException: Timeout of 60000ms expired before the position for partition weather_dakar-0 could be determined
[2025-09-01 04:50:49,896] {subprocess.py:92} INFO - 25/09/01 04:50:49 WARN ProcessingTimeExecutor: Current batch is falling behind. The trigger interval is 60000 milliseconds, but spent 289831 milliseconds
[2025-09-01 04:50:50,672] {local_task_job.py:209} WARNING - Recorded pid 8044 does not match the current pid 7153
[2025-09-01 04:50:50,678] {process_utils.py:129} INFO - Sending Signals.SIGTERM to group 7153. PIDs of all processes in the group: [7154, 7202, 7153]
[2025-09-01 04:50:50,678] {process_utils.py:80} INFO - Sending the signal Signals.SIGTERM to group 7153
[2025-09-01 04:50:50,680] {taskinstance.py:1541} ERROR - Received SIGTERM. Terminating subprocesses.
[2025-09-01 04:50:50,680] {subprocess.py:103} INFO - Sending SIGTERM signal to process group
[2025-09-01 04:50:50,736] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 189, in execute
    cwd=self.cwd,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/hooks/subprocess.py", line 90, in run_command
    for raw_line in iter(self.sub_process.stdout.readline, b''):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1543, in signal_handler
    raise AirflowException("Task received SIGTERM signal")
airflow.exceptions.AirflowException: Task received SIGTERM signal
[2025-09-01 04:50:50,748] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=send_weather_to_kafka, task_id=stream_hdfs, execution_date=20250901T033900, start_date=20250901T045047, end_date=20250901T045050
[2025-09-01 04:50:50,799] {standard_task_runner.py:97} ERROR - Failed to execute job 451 for task stream_hdfs (Task received SIGTERM signal; 7153)
[2025-09-01 04:50:50,817] {process_utils.py:75} INFO - Process psutil.Process(pid=7153, status='terminated', exitcode=1, started='04:12:34') (7153) terminated with exit code 1
[2025-09-01 04:50:50,818] {process_utils.py:75} INFO - Process psutil.Process(pid=7202, status='terminated', started='04:12:36') (7202) terminated with exit code None
[2025-09-01 04:50:51,064] {process_utils.py:75} INFO - Process psutil.Process(pid=7154, status='terminated', started='04:12:34') (7154) terminated with exit code None
